// Code generated by MockGen. DO NOT EDIT.
// Source: path_assignment.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/path_assignment_mock.go -source path_assignment.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/tutor/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPathAssignmentRepo is a mock of PathAssignmentRepo interface.
type MockPathAssignmentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPathAssignmentRepoMockRecorder
	isgomock struct{}
}

// MockPathAssignmentRepoMockRecorder is the mock recorder for MockPathAssignmentRepo.
type MockPathAssignmentRepoMockRecorder struct {
	mock *MockPathAssignmentRepo
}

// NewMockPathAssignmentRepo creates a new mock instance.
func NewMockPathAssignmentRepo(ctrl *gomock.Controller) *MockPathAssignmentRepo {
	mock := &MockPathAssignmentRepo{ctrl: ctrl}
	mock.recorder = &MockPathAssignmentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPathAssignmentRepo) EXPECT() *MockPathAssignmentRepoMockRecorder {
	return m.recorder
}

// AdvanceStep mocks base method.
func (m *MockPathAssignmentRepo) AdvanceStep(ctx context.Context, requesterID, assignmentID uuid.UUID, now time.Time) (domain.PathAssignment, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdvanceStep", ctx, requesterID, assignmentID, now)
	ret0, _ := ret[0].(domain.PathAssignment)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AdvanceStep indicates an expected call of AdvanceStep.
func (mr *MockPathAssignmentRepoMockRecorder) AdvanceStep(ctx, requesterID, assignmentID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdvanceStep", reflect.TypeOf((*MockPathAssignmentRepo)(nil).AdvanceStep), ctx, requesterID, assignmentID, now)
}

// CreatePathAssignment mocks base method.
func (m *MockPathAssignmentRepo) CreatePathAssignment(ctx context.Context, a domain.PathAssignment) (domain.PathAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePathAssignment", ctx, a)
	ret0, _ := ret[0].(domain.PathAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePathAssignment indicates an expected call of CreatePathAssignment.
func (mr *MockPathAssignmentRepoMockRecorder) CreatePathAssignment(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePathAssignment", reflect.TypeOf((*MockPathAssignmentRepo)(nil).CreatePathAssignment), ctx, a)
}

// GetPathAssignment mocks base method.
func (m *MockPathAssignmentRepo) GetPathAssignment(ctx context.Context, requesterID, assignmentID uuid.UUID) (domain.PathAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPathAssignment", ctx, requesterID, assignmentID)
	ret0, _ := ret[0].(domain.PathAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPathAssignment indicates an expected call of GetPathAssignment.
func (mr *MockPathAssignmentRepoMockRecorder) GetPathAssignment(ctx, requesterID, assignmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPathAssignment", reflect.TypeOf((*MockPathAssignmentRepo)(nil).GetPathAssignment), ctx, requesterID, assignmentID)
}

// IncrementPathAssignedCount mocks base method.
func (m *MockPathAssignmentRepo) IncrementPathAssignedCount(ctx context.Context, pathID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementPathAssignedCount", ctx, pathID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementPathAssignedCount indicates an expected call of IncrementPathAssignedCount.
func (mr *MockPathAssignmentRepoMockRecorder) IncrementPathAssignedCount(ctx, pathID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementPathAssignedCount", reflect.TypeOf((*MockPathAssignmentRepo)(nil).IncrementPathAssignedCount), ctx, pathID)
}

// ListActiveByStudent mocks base method.
func (m *MockPathAssignmentRepo) ListActiveByStudent(ctx context.Context, studentID uuid.UUID) ([]domain.PathAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByStudent", ctx, studentID)
	ret0, _ := ret[0].([]domain.PathAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveByStudent indicates an expected call of ListActiveByStudent.
func (mr *MockPathAssignmentRepoMockRecorder) ListActiveByStudent(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByStudent", reflect.TypeOf((*MockPathAssignmentRepo)(nil).ListActiveByStudent), ctx, studentID)
}
