// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/repo_mock.go -source repo.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/google_calendar/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialsRepo is a mock of CredentialsRepo interface.
type MockCredentialsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsRepoMockRecorder
	isgomock struct{}
}

// MockCredentialsRepoMockRecorder is the mock recorder for MockCredentialsRepo.
type MockCredentialsRepoMockRecorder struct {
	mock *MockCredentialsRepo
}

// NewMockCredentialsRepo creates a new mock instance.
func NewMockCredentialsRepo(ctrl *gomock.Controller) *MockCredentialsRepo {
	mock := &MockCredentialsRepo{ctrl: ctrl}
	mock.recorder = &MockCredentialsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialsRepo) EXPECT() *MockCredentialsRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCredentialsRepo) Delete(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCredentialsRepoMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCredentialsRepo)(nil).Delete), ctx, userID)
}

// Get mocks base method.
func (m *MockCredentialsRepo) Get(ctx context.Context, userID uuid.UUID) (domain.GoogleCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(domain.GoogleCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCredentialsRepoMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCredentialsRepo)(nil).Get), ctx, userID)
}

// ListConnected mocks base method.
func (m *MockCredentialsRepo) ListConnected(ctx context.Context) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnected", ctx)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConnected indicates an expected call of ListConnected.
func (mr *MockCredentialsRepoMockRecorder) ListConnected(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnected", reflect.TypeOf((*MockCredentialsRepo)(nil).ListConnected), ctx)
}

// Upsert mocks base method.
func (m *MockCredentialsRepo) Upsert(ctx context.Context, c domain.GoogleCredentials) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCredentialsRepoMockRecorder) Upsert(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCredentialsRepo)(nil).Upsert), ctx, c)
}

// MockEventsRepo is a mock of EventsRepo interface.
type MockEventsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventsRepoMockRecorder
	isgomock struct{}
}

// MockEventsRepoMockRecorder is the mock recorder for MockEventsRepo.
type MockEventsRepoMockRecorder struct {
	mock *MockEventsRepo
}

// NewMockEventsRepo creates a new mock instance.
func NewMockEventsRepo(ctrl *gomock.Controller) *MockEventsRepo {
	mock := &MockEventsRepo{ctrl: ctrl}
	mock.recorder = &MockEventsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventsRepo) EXPECT() *MockEventsRepoMockRecorder {
	return m.recorder
}

// LastSyncedAt mocks base method.
func (m *MockEventsRepo) LastSyncedAt(ctx context.Context, userID uuid.UUID) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastSyncedAt", ctx, userID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastSyncedAt indicates an expected call of LastSyncedAt.
func (mr *MockEventsRepoMockRecorder) LastSyncedAt(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastSyncedAt", reflect.TypeOf((*MockEventsRepo)(nil).LastSyncedAt), ctx, userID)
}

// List mocks base method.
func (m *MockEventsRepo) List(ctx context.Context, userID uuid.UUID, from, to time.Time) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, from, to)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEventsRepoMockRecorder) List(ctx, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEventsRepo)(nil).List), ctx, userID, from, to)
}

// MarkDeleted mocks base method.
func (m *MockEventsRepo) MarkDeleted(ctx context.Context, userID uuid.UUID, googleEventID string, when time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDeleted", ctx, userID, googleEventID, when)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDeleted indicates an expected call of MarkDeleted.
func (mr *MockEventsRepoMockRecorder) MarkDeleted(ctx, userID, googleEventID, when any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDeleted", reflect.TypeOf((*MockEventsRepo)(nil).MarkDeleted), ctx, userID, googleEventID, when)
}

// Upsert mocks base method.
func (m *MockEventsRepo) Upsert(ctx context.Context, e domain.Event) (domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, e)
	ret0, _ := ret[0].(domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockEventsRepoMockRecorder) Upsert(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockEventsRepo)(nil).Upsert), ctx, e)
}

// MockGoogleAPI is a mock of GoogleAPI interface.
type MockGoogleAPI struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleAPIMockRecorder
	isgomock struct{}
}

// MockGoogleAPIMockRecorder is the mock recorder for MockGoogleAPI.
type MockGoogleAPIMockRecorder struct {
	mock *MockGoogleAPI
}

// NewMockGoogleAPI creates a new mock instance.
func NewMockGoogleAPI(ctrl *gomock.Controller) *MockGoogleAPI {
	mock := &MockGoogleAPI{ctrl: ctrl}
	mock.recorder = &MockGoogleAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleAPI) EXPECT() *MockGoogleAPIMockRecorder {
	return m.recorder
}

// AuthURL mocks base method.
func (m *MockGoogleAPI) AuthURL(state, redirectURI string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthURL", state, redirectURI)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthURL indicates an expected call of AuthURL.
func (mr *MockGoogleAPIMockRecorder) AuthURL(state, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthURL", reflect.TypeOf((*MockGoogleAPI)(nil).AuthURL), state, redirectURI)
}

// DeleteEvent mocks base method.
func (m *MockGoogleAPI) DeleteEvent(ctx context.Context, accessToken, calendarID, googleEventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, accessToken, calendarID, googleEventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockGoogleAPIMockRecorder) DeleteEvent(ctx, accessToken, calendarID, googleEventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockGoogleAPI)(nil).DeleteEvent), ctx, accessToken, calendarID, googleEventID)
}

// ExchangeCode mocks base method.
func (m *MockGoogleAPI) ExchangeCode(ctx context.Context, code, redirectURI string) (domain.GoogleCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code, redirectURI)
	ret0, _ := ret[0].(domain.GoogleCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockGoogleAPIMockRecorder) ExchangeCode(ctx, code, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockGoogleAPI)(nil).ExchangeCode), ctx, code, redirectURI)
}

// InsertEvent mocks base method.
func (m *MockGoogleAPI) InsertEvent(ctx context.Context, accessToken, calendarID string, in domain.EventInput) (domain.GoogleEventDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", ctx, accessToken, calendarID, in)
	ret0, _ := ret[0].(domain.GoogleEventDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockGoogleAPIMockRecorder) InsertEvent(ctx, accessToken, calendarID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvent", reflect.TypeOf((*MockGoogleAPI)(nil).InsertEvent), ctx, accessToken, calendarID, in)
}

// ListEvents mocks base method.
func (m *MockGoogleAPI) ListEvents(ctx context.Context, accessToken, calendarID string, timeMin, timeMax, updatedMin time.Time) ([]domain.GoogleEventDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, accessToken, calendarID, timeMin, timeMax, updatedMin)
	ret0, _ := ret[0].([]domain.GoogleEventDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockGoogleAPIMockRecorder) ListEvents(ctx, accessToken, calendarID, timeMin, timeMax, updatedMin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockGoogleAPI)(nil).ListEvents), ctx, accessToken, calendarID, timeMin, timeMax, updatedMin)
}

// PatchEvent mocks base method.
func (m *MockGoogleAPI) PatchEvent(ctx context.Context, accessToken, calendarID, googleEventID string, in domain.EventInput) (domain.GoogleEventDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchEvent", ctx, accessToken, calendarID, googleEventID, in)
	ret0, _ := ret[0].(domain.GoogleEventDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchEvent indicates an expected call of PatchEvent.
func (mr *MockGoogleAPIMockRecorder) PatchEvent(ctx, accessToken, calendarID, googleEventID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchEvent", reflect.TypeOf((*MockGoogleAPI)(nil).PatchEvent), ctx, accessToken, calendarID, googleEventID, in)
}

// RefreshToken mocks base method.
func (m *MockGoogleAPI) RefreshToken(ctx context.Context, refreshToken string) (string, time.Time, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockGoogleAPIMockRecorder) RefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockGoogleAPI)(nil).RefreshToken), ctx, refreshToken)
}

// RevokeToken mocks base method.
func (m *MockGoogleAPI) RevokeToken(ctx context.Context, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockGoogleAPIMockRecorder) RevokeToken(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockGoogleAPI)(nil).RevokeToken), ctx, accessToken)
}

// MockStateStore is a mock of StateStore interface.
type MockStateStore struct {
	ctrl     *gomock.Controller
	recorder *MockStateStoreMockRecorder
	isgomock struct{}
}

// MockStateStoreMockRecorder is the mock recorder for MockStateStore.
type MockStateStoreMockRecorder struct {
	mock *MockStateStore
}

// NewMockStateStore creates a new mock instance.
func NewMockStateStore(ctrl *gomock.Controller) *MockStateStore {
	mock := &MockStateStore{ctrl: ctrl}
	mock.recorder = &MockStateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateStore) EXPECT() *MockStateStoreMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockStateStore) Consume(ctx context.Context, state string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, state)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockStateStoreMockRecorder) Consume(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockStateStore)(nil).Consume), ctx, state)
}

// Put mocks base method.
func (m *MockStateStore) Put(ctx context.Context, state string, userID uuid.UUID, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, state, userID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockStateStoreMockRecorder) Put(ctx, state, userID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockStateStore)(nil).Put), ctx, state, userID, ttl)
}
