package extractor

import (
	"bytes"
	"fmt"
	"io"
	"strings"
	"unicode/utf8"

	"druz9/documents/domain"

	pdfreader "github.com/ledongthuc/pdf"
)

// ExtractPDF pulls plain text out of a PDF. Exported so TextExtractor's
// dispatcher can call it — the PDF path is opt-in (not wired by default
// in the zero-value TextExtractor) because production deploys may prefer
// to reject PDFs until OCR is in place for scanned files.
//
// Quality envelope:
//   - Works well for text-based PDFs generated by Word/Pages/LaTeX/LibreOffice
//     (CV, JD, reports, exported articles).
//   - Works poorly or not at all for scanned PDFs (image-only pages).
//     We don't OCR here; a scanned CV falls back to domain.ErrEmptyContent
//     and the UI surfaces "extraction failed — try another format".
//   - ledongthuc/pdf occasionally drops whitespace between words; we
//     re-flow whitespace below to keep the embedding layer from seeing
//     "JohnDoeSeniorEngineer" as one token.
func ExtractPDF(content []byte) (string, error) {
	// Guard — PDF files start with "%PDF-". Quick reject of obvious
	// mismatches before we hand to the parser which would OOM on a
	// 10MB-of-zeros payload.
	if !bytes.HasPrefix(content, []byte("%PDF-")) {
		return "", fmt.Errorf("%w: not a PDF (no %%PDF- header)", domain.ErrUnsupportedMIME)
	}

	r, err := pdfreader.NewReader(bytes.NewReader(content), int64(len(content)))
	if err != nil {
		return "", fmt.Errorf("pdf parse: %w", err)
	}

	var b strings.Builder
	b.Grow(len(content) / 4) // text is typically ~25% of PDF bytes for prose

	total := r.NumPage()
	for i := 1; i <= total; i++ {
		page := r.Page(i)
		if page.V.IsNull() {
			continue
		}
		// GetPlainText(nil) returns the page text in reading order with
		// font-spacing heuristics applied. Not perfect (columns still
		// interleave sometimes) but good enough for the single-column
		// prose that CVs/JDs are.
		text, err := page.GetPlainText(nil)
		if err != nil {
			// Don't bail on a single bad page — partial content from a
			// 20-page doc is more useful than zero content. Log-worthy
			// but not fatal.
			continue
		}
		if i > 1 {
			b.WriteByte('\n')
		}
		b.WriteString(text)
	}

	raw := b.String()
	if !utf8.Valid([]byte(raw)) {
		return "", fmt.Errorf("%w: pdf text is not utf-8", domain.ErrUnsupportedMIME)
	}
	cleaned := normalizeWhitespace(raw)
	if strings.TrimSpace(cleaned) == "" {
		// Most common cause: scanned PDF with no embedded text layer.
		// Surfacing the specific cause would require inspecting the PDF
		// object tree — overkill for MVP; the generic "empty" error
		// points the user at the right diagnosis.
		return "", domain.ErrEmptyContent
	}
	return cleaned, nil
}

// normalizeWhitespace collapses runs of spaces/tabs while preserving
// single newlines. Without this, ledongthuc's output can contain long
// runs of non-breaking spaces that inflate token counts and hurt
// embedding quality. Newlines survive so the chunker's sentence
// splitter has paragraph anchors to work with.
func normalizeWhitespace(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	prevIsSpace := false
	for _, r := range s {
		if r == '\n' || r == '\r' {
			b.WriteByte('\n')
			prevIsSpace = true
			continue
		}
		if r == ' ' || r == '\t' || r == '\u00A0' {
			if !prevIsSpace {
				b.WriteByte(' ')
				prevIsSpace = true
			}
			continue
		}
		b.WriteRune(r)
		prevIsSpace = false
	}
	return b.String()
}

// extractPDFReader is a small convenience wrapper so tests/future callers
// can stream from an io.Reader without materializing a full []byte first.
// Kept unexported — not exposed via the Extractor interface because we
// already hold the bytes in memory at the handler boundary.
func extractPDFReader(r io.Reader, size int64) (string, error) {
	buf, err := io.ReadAll(io.LimitReader(r, size))
	if err != nil {
		return "", err
	}
	return ExtractPDF(buf)
}

// Sentinel to silence the unused-function lint in case the convenience
// helper ends up not called; better to keep the option available than
// remove it the first time someone wants to plumb a stream through.
var _ = extractPDFReader
