// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: editor.sql

package editordb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO editor_participants (room_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (room_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING room_id, user_id, role, joined_at
`

type AddParticipantParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (EditorParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipant, arg.RoomID, arg.UserID, arg.Role)
	var i EditorParticipant
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one

INSERT INTO editor_rooms (
    owner_id, type, task_id, language, is_frozen, expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, type, task_id, language, is_frozen, expires_at, created_at
`

type CreateRoomParams struct {
	OwnerID   pgtype.UUID
	Type      string
	TaskID    pgtype.UUID
	Language  string
	IsFrozen  bool
	ExpiresAt pgtype.Timestamptz
}

// Queries consumed by sqlc for the editor domain. Mirrors the hand-rolled
// adapter in infra/postgres.go.
//
// NOTE: the editor domain never needs tasks.solution_hint — the TaskPublic
// projection built elsewhere (e.g. /daily, /arena) is used when the caller
// wants task details attached to the room. Keeping tasks out of this file
// entirely avoids any risk of hint leakage from here.
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (EditorRoom, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.OwnerID,
		arg.Type,
		arg.TaskID,
		arg.Language,
		arg.IsFrozen,
		arg.ExpiresAt,
	)
	var i EditorRoom
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.TaskID,
		&i.Language,
		&i.IsFrozen,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const extendRoomExpires = `-- name: ExtendRoomExpires :execrows
UPDATE editor_rooms
   SET expires_at = $2
 WHERE id = $1
`

type ExtendRoomExpiresParams struct {
	ID        pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ExtendRoomExpires(ctx context.Context, arg ExtendRoomExpiresParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendRoomExpires, arg.ID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getParticipantRole = `-- name: GetParticipantRole :one
SELECT role
  FROM editor_participants
 WHERE room_id = $1 AND user_id = $2
`

type GetParticipantRoleParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetParticipantRole(ctx context.Context, arg GetParticipantRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getParticipantRole, arg.RoomID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, owner_id, type, task_id, language, is_frozen, expires_at, created_at
  FROM editor_rooms
 WHERE id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id pgtype.UUID) (EditorRoom, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i EditorRoom
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.TaskID,
		&i.Language,
		&i.IsFrozen,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listParticipants = `-- name: ListParticipants :many
SELECT room_id, user_id, role, joined_at
  FROM editor_participants
 WHERE room_id = $1
 ORDER BY joined_at ASC
`

func (q *Queries) ListParticipants(ctx context.Context, roomID pgtype.UUID) ([]EditorParticipant, error) {
	rows, err := q.db.Query(ctx, listParticipants, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EditorParticipant{}
	for rows.Next() {
		var i EditorParticipant
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomFreeze = `-- name: UpdateRoomFreeze :one
UPDATE editor_rooms
   SET is_frozen = $2
 WHERE id = $1
 RETURNING id, owner_id, type, task_id, language, is_frozen, expires_at, created_at
`

type UpdateRoomFreezeParams struct {
	ID       pgtype.UUID
	IsFrozen bool
}

func (q *Queries) UpdateRoomFreeze(ctx context.Context, arg UpdateRoomFreezeParams) (EditorRoom, error) {
	row := q.db.QueryRow(ctx, updateRoomFreeze, arg.ID, arg.IsFrozen)
	var i EditorRoom
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.TaskID,
		&i.Language,
		&i.IsFrozen,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
