// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package notifydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearTelegramChatID(ctx context.Context, userID pgtype.UUID) error
	FindUserIDByUsername(ctx context.Context, username string) (pgtype.UUID, error)
	// notify queries consumed by sqlc (emitted into services/notify/infra/db).
	//
	// v2:
	//   * notification_preferences merged into notification_prefs (single table)
	//   * notifications_log dropped (was event-log, nobody reads)
	//   * channels[] / quiet_hours_* removed (channel state lives in
	//     channel_enabled jsonb; quiet hours are silence_until timestamptz)
	GetPreferences(ctx context.Context, userID pgtype.UUID) (NotificationPref, error)
	GetUserLocale(ctx context.Context, id pgtype.UUID) (string, error)
	ListWeeklyReportEnabled(ctx context.Context) ([]pgtype.UUID, error)
	SetTelegramChatID(ctx context.Context, arg SetTelegramChatIDParams) error
	UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (NotificationPref, error)
}

var _ Querier = (*Queries)(nil)
