// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package notifydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearTelegramChatID(ctx context.Context, userID pgtype.UUID) error
	FindUserIDByUsername(ctx context.Context, username string) (pgtype.UUID, error)
	// notify queries consumed by sqlc (emitted into services/notify/infra/db).
	GetPreferences(ctx context.Context, userID pgtype.UUID) (NotificationPreference, error)
	GetUserLocale(ctx context.Context, id pgtype.UUID) (string, error)
	InsertLog(ctx context.Context, arg InsertLogParams) (NotificationsLog, error)
	ListWeeklyReportEnabled(ctx context.Context) ([]pgtype.UUID, error)
	MarkLogFailed(ctx context.Context, arg MarkLogFailedParams) error
	MarkLogSent(ctx context.Context, arg MarkLogSentParams) error
	RecentLogByType(ctx context.Context, arg RecentLogByTypeParams) ([]NotificationsLog, error)
	SetTelegramChatID(ctx context.Context, arg SetTelegramChatIDParams) error
	UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (NotificationPreference, error)
}

var _ Querier = (*Queries)(nil)
