// Code generated by MockGen. DO NOT EDIT.
// Source: auto_promote.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/auto_promote_mock.go -source auto_promote.go PromotionReader,PromotionWriter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	app "druz9/curation/app"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPromotionReader is a mock of PromotionReader interface.
type MockPromotionReader struct {
	ctrl     *gomock.Controller
	recorder *MockPromotionReaderMockRecorder
	isgomock struct{}
}

// MockPromotionReaderMockRecorder is the mock recorder for MockPromotionReader.
type MockPromotionReaderMockRecorder struct {
	mock *MockPromotionReader
}

// NewMockPromotionReader creates a new mock instance.
func NewMockPromotionReader(ctrl *gomock.Controller) *MockPromotionReader {
	mock := &MockPromotionReader{ctrl: ctrl}
	mock.recorder = &MockPromotionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromotionReader) EXPECT() *MockPromotionReaderMockRecorder {
	return m.recorder
}

// AggregateSignal mocks base method.
func (m *MockPromotionReader) AggregateSignal(ctx context.Context, url string) (app.SignalRefresh, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateSignal", ctx, url)
	ret0, _ := ret[0].(app.SignalRefresh)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AggregateSignal indicates an expected call of AggregateSignal.
func (mr *MockPromotionReaderMockRecorder) AggregateSignal(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateSignal", reflect.TypeOf((*MockPromotionReader)(nil).AggregateSignal), ctx, url)
}

// DeprecateCandidates mocks base method.
func (m *MockPromotionReader) DeprecateCandidates(ctx context.Context, minUsers int, maxBadQuality float32) ([]app.PromotionSignal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeprecateCandidates", ctx, minUsers, maxBadQuality)
	ret0, _ := ret[0].([]app.PromotionSignal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeprecateCandidates indicates an expected call of DeprecateCandidates.
func (mr *MockPromotionReaderMockRecorder) DeprecateCandidates(ctx, minUsers, maxBadQuality any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeprecateCandidates", reflect.TypeOf((*MockPromotionReader)(nil).DeprecateCandidates), ctx, minUsers, maxBadQuality)
}

// PromoteCandidates mocks base method.
func (m *MockPromotionReader) PromoteCandidates(ctx context.Context, minUsers int, minQuality float32) ([]app.PromotionSignal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteCandidates", ctx, minUsers, minQuality)
	ret0, _ := ret[0].([]app.PromotionSignal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromoteCandidates indicates an expected call of PromoteCandidates.
func (mr *MockPromotionReaderMockRecorder) PromoteCandidates(ctx, minUsers, minQuality any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteCandidates", reflect.TypeOf((*MockPromotionReader)(nil).PromoteCandidates), ctx, minUsers, minQuality)
}

// RecentLoggedURLs mocks base method.
func (m *MockPromotionReader) RecentLoggedURLs(ctx context.Context, since time.Time) ([]app.LoggedResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentLoggedURLs", ctx, since)
	ret0, _ := ret[0].([]app.LoggedResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentLoggedURLs indicates an expected call of RecentLoggedURLs.
func (mr *MockPromotionReaderMockRecorder) RecentLoggedURLs(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentLoggedURLs", reflect.TypeOf((*MockPromotionReader)(nil).RecentLoggedURLs), ctx, since)
}

// MockPromotionWriter is a mock of PromotionWriter interface.
type MockPromotionWriter struct {
	ctrl     *gomock.Controller
	recorder *MockPromotionWriterMockRecorder
	isgomock struct{}
}

// MockPromotionWriterMockRecorder is the mock recorder for MockPromotionWriter.
type MockPromotionWriterMockRecorder struct {
	mock *MockPromotionWriter
}

// NewMockPromotionWriter creates a new mock instance.
func NewMockPromotionWriter(ctrl *gomock.Controller) *MockPromotionWriter {
	mock := &MockPromotionWriter{ctrl: ctrl}
	mock.recorder = &MockPromotionWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromotionWriter) EXPECT() *MockPromotionWriterMockRecorder {
	return m.recorder
}

// AppendAtlasResource mocks base method.
func (m *MockPromotionWriter) AppendAtlasResource(ctx context.Context, atlasNodeID, url string, userCount int, avgQuality float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendAtlasResource", ctx, atlasNodeID, url, userCount, avgQuality)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendAtlasResource indicates an expected call of AppendAtlasResource.
func (mr *MockPromotionWriterMockRecorder) AppendAtlasResource(ctx, atlasNodeID, url, userCount, avgQuality any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAtlasResource", reflect.TypeOf((*MockPromotionWriter)(nil).AppendAtlasResource), ctx, atlasNodeID, url, userCount, avgQuality)
}

// MarkDeprecated mocks base method.
func (m *MockPromotionWriter) MarkDeprecated(ctx context.Context, url, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDeprecated", ctx, url, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDeprecated indicates an expected call of MarkDeprecated.
func (mr *MockPromotionWriterMockRecorder) MarkDeprecated(ctx, url, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDeprecated", reflect.TypeOf((*MockPromotionWriter)(nil).MarkDeprecated), ctx, url, reason)
}

// MarkPromoted mocks base method.
func (m *MockPromotionWriter) MarkPromoted(ctx context.Context, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPromoted", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPromoted indicates an expected call of MarkPromoted.
func (mr *MockPromotionWriterMockRecorder) MarkPromoted(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPromoted", reflect.TypeOf((*MockPromotionWriter)(nil).MarkPromoted), ctx, url)
}

// RefreshSignal mocks base method.
func (m *MockPromotionWriter) RefreshSignal(ctx context.Context, in app.SignalRefresh) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshSignal", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshSignal indicates an expected call of RefreshSignal.
func (mr *MockPromotionWriterMockRecorder) RefreshSignal(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshSignal", reflect.TypeOf((*MockPromotionWriter)(nil).RefreshSignal), ctx, in)
}
