// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/repo_mock.go -source repo.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/rating/domain"
	enums "druz9/shared/enums"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRatingRepo is a mock of RatingRepo interface.
type MockRatingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRatingRepoMockRecorder
	isgomock struct{}
}

// MockRatingRepoMockRecorder is the mock recorder for MockRatingRepo.
type MockRatingRepoMockRecorder struct {
	mock *MockRatingRepo
}

// NewMockRatingRepo creates a new mock instance.
func NewMockRatingRepo(ctrl *gomock.Controller) *MockRatingRepo {
	mock := &MockRatingRepo{ctrl: ctrl}
	mock.recorder = &MockRatingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingRepo) EXPECT() *MockRatingRepoMockRecorder {
	return m.recorder
}

// CountSection mocks base method.
func (m *MockRatingRepo) CountSection(ctx context.Context, section enums.Section) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSection", ctx, section)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSection indicates an expected call of CountSection.
func (mr *MockRatingRepoMockRecorder) CountSection(ctx, section any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSection", reflect.TypeOf((*MockRatingRepo)(nil).CountSection), ctx, section)
}

// FindRank mocks base method.
func (m *MockRatingRepo) FindRank(ctx context.Context, userID uuid.UUID, section enums.Section) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRank", ctx, userID, section)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRank indicates an expected call of FindRank.
func (mr *MockRatingRepoMockRecorder) FindRank(ctx, userID, section any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRank", reflect.TypeOf((*MockRatingRepo)(nil).FindRank), ctx, userID, section)
}

// HistoryLast12Weeks mocks base method.
func (m *MockRatingRepo) HistoryLast12Weeks(ctx context.Context, userID uuid.UUID) ([]domain.HistorySample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HistoryLast12Weeks", ctx, userID)
	ret0, _ := ret[0].([]domain.HistorySample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HistoryLast12Weeks indicates an expected call of HistoryLast12Weeks.
func (mr *MockRatingRepoMockRecorder) HistoryLast12Weeks(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HistoryLast12Weeks", reflect.TypeOf((*MockRatingRepo)(nil).HistoryLast12Weeks), ctx, userID)
}

// List mocks base method.
func (m *MockRatingRepo) List(ctx context.Context, userID uuid.UUID) ([]domain.SectionRating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]domain.SectionRating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRatingRepoMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRatingRepo)(nil).List), ctx, userID)
}

// Top mocks base method.
func (m *MockRatingRepo) Top(ctx context.Context, section enums.Section, limit int) ([]domain.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Top", ctx, section, limit)
	ret0, _ := ret[0].([]domain.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Top indicates an expected call of Top.
func (mr *MockRatingRepoMockRecorder) Top(ctx, section, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Top", reflect.TypeOf((*MockRatingRepo)(nil).Top), ctx, section, limit)
}

// Upsert mocks base method.
func (m *MockRatingRepo) Upsert(ctx context.Context, r domain.SectionRating) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRatingRepoMockRecorder) Upsert(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRatingRepo)(nil).Upsert), ctx, r)
}

// MockLeaderboardCache is a mock of LeaderboardCache interface.
type MockLeaderboardCache struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardCacheMockRecorder
	isgomock struct{}
}

// MockLeaderboardCacheMockRecorder is the mock recorder for MockLeaderboardCache.
type MockLeaderboardCacheMockRecorder struct {
	mock *MockLeaderboardCache
}

// NewMockLeaderboardCache creates a new mock instance.
func NewMockLeaderboardCache(ctrl *gomock.Controller) *MockLeaderboardCache {
	mock := &MockLeaderboardCache{ctrl: ctrl}
	mock.recorder = &MockLeaderboardCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboardCache) EXPECT() *MockLeaderboardCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLeaderboardCache) Get(ctx context.Context, section enums.Section, limit int) ([]domain.LeaderboardEntry, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, section, limit)
	ret0, _ := ret[0].([]domain.LeaderboardEntry)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockLeaderboardCacheMockRecorder) Get(ctx, section, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLeaderboardCache)(nil).Get), ctx, section, limit)
}

// Put mocks base method.
func (m *MockLeaderboardCache) Put(ctx context.Context, section enums.Section, entries []domain.LeaderboardEntry, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, section, entries, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockLeaderboardCacheMockRecorder) Put(ctx, section, entries, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockLeaderboardCache)(nil).Put), ctx, section, entries, ttl)
}
