// Code generated by MockGen. DO NOT EDIT.
// Source: canvas_draft.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/canvas_draft_mock.go -source canvas_draft.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/mock_interview/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCanvasDraftStore is a mock of CanvasDraftStore interface.
type MockCanvasDraftStore struct {
	ctrl     *gomock.Controller
	recorder *MockCanvasDraftStoreMockRecorder
	isgomock struct{}
}

// MockCanvasDraftStoreMockRecorder is the mock recorder for MockCanvasDraftStore.
type MockCanvasDraftStoreMockRecorder struct {
	mock *MockCanvasDraftStore
}

// NewMockCanvasDraftStore creates a new mock instance.
func NewMockCanvasDraftStore(ctrl *gomock.Controller) *MockCanvasDraftStore {
	mock := &MockCanvasDraftStore{ctrl: ctrl}
	mock.recorder = &MockCanvasDraftStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCanvasDraftStore) EXPECT() *MockCanvasDraftStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCanvasDraftStore) Delete(ctx context.Context, attemptID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, attemptID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCanvasDraftStoreMockRecorder) Delete(ctx, attemptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCanvasDraftStore)(nil).Delete), ctx, attemptID)
}

// Get mocks base method.
func (m *MockCanvasDraftStore) Get(ctx context.Context, attemptID uuid.UUID) (domain.CanvasDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, attemptID)
	ret0, _ := ret[0].(domain.CanvasDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCanvasDraftStoreMockRecorder) Get(ctx, attemptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCanvasDraftStore)(nil).Get), ctx, attemptID)
}

// Save mocks base method.
func (m *MockCanvasDraftStore) Save(ctx context.Context, attemptID uuid.UUID, draft domain.CanvasDraft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, attemptID, draft)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCanvasDraftStoreMockRecorder) Save(ctx, attemptID, draft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCanvasDraftStore)(nil).Save), ctx, attemptID, draft)
}
