// Code generated by MockGen. DO NOT EDIT.
// Source: leaderboard.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/leaderboard_mock.go -source leaderboard.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/mock_interview/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockLeaderboardRepo is a mock of LeaderboardRepo interface.
type MockLeaderboardRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardRepoMockRecorder
	isgomock struct{}
}

// MockLeaderboardRepoMockRecorder is the mock recorder for MockLeaderboardRepo.
type MockLeaderboardRepoMockRecorder struct {
	mock *MockLeaderboardRepo
}

// NewMockLeaderboardRepo creates a new mock instance.
func NewMockLeaderboardRepo(ctrl *gomock.Controller) *MockLeaderboardRepo {
	mock := &MockLeaderboardRepo{ctrl: ctrl}
	mock.recorder = &MockLeaderboardRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboardRepo) EXPECT() *MockLeaderboardRepoMockRecorder {
	return m.recorder
}

// Top mocks base method.
func (m *MockLeaderboardRepo) Top(ctx context.Context, companyID *uuid.UUID, limit int) ([]domain.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Top", ctx, companyID, limit)
	ret0, _ := ret[0].([]domain.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Top indicates an expected call of Top.
func (mr *MockLeaderboardRepoMockRecorder) Top(ctx, companyID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Top", reflect.TypeOf((*MockLeaderboardRepo)(nil).Top), ctx, companyID, limit)
}
