// Code generated by MockGen. DO NOT EDIT.
// Source: memory_hook.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/memory_hook_mock.go -source memory_hook.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/mock_interview/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMemoryHook is a mock of MemoryHook interface.
type MockMemoryHook struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryHookMockRecorder
	isgomock struct{}
}

// MockMemoryHookMockRecorder is the mock recorder for MockMemoryHook.
type MockMemoryHookMockRecorder struct {
	mock *MockMemoryHook
}

// NewMockMemoryHook creates a new mock instance.
func NewMockMemoryHook(ctrl *gomock.Controller) *MockMemoryHook {
	mock := &MockMemoryHook{ctrl: ctrl}
	mock.recorder = &MockMemoryHookMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryHook) EXPECT() *MockMemoryHookMockRecorder {
	return m.recorder
}

// OnPipelineFinished mocks base method.
func (m *MockMemoryHook) OnPipelineFinished(ctx context.Context, userID, pipelineID uuid.UUID, verdict domain.PipelineVerdict, totalScore *float32, stages []domain.PipelineStage, occurredAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnPipelineFinished", ctx, userID, pipelineID, verdict, totalScore, stages, occurredAt)
}

// OnPipelineFinished indicates an expected call of OnPipelineFinished.
func (mr *MockMemoryHookMockRecorder) OnPipelineFinished(ctx, userID, pipelineID, verdict, totalScore, stages, occurredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPipelineFinished", reflect.TypeOf((*MockMemoryHook)(nil).OnPipelineFinished), ctx, userID, pipelineID, verdict, totalScore, stages, occurredAt)
}
