// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/repo_mock.go -source repo.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/mock_interview/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCompanyRepo is a mock of CompanyRepo interface.
type MockCompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyRepoMockRecorder
	isgomock struct{}
}

// MockCompanyRepoMockRecorder is the mock recorder for MockCompanyRepo.
type MockCompanyRepoMockRecorder struct {
	mock *MockCompanyRepo
}

// NewMockCompanyRepo creates a new mock instance.
func NewMockCompanyRepo(ctrl *gomock.Controller) *MockCompanyRepo {
	mock := &MockCompanyRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyRepo) EXPECT() *MockCompanyRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCompanyRepo) Create(ctx context.Context, c domain.Company) (domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCompanyRepoMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCompanyRepo)(nil).Create), ctx, c)
}

// Get mocks base method.
func (m *MockCompanyRepo) Get(ctx context.Context, id uuid.UUID) (domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompanyRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompanyRepo)(nil).Get), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockCompanyRepo) GetBySlug(ctx context.Context, slug string) (domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockCompanyRepoMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockCompanyRepo)(nil).GetBySlug), ctx, slug)
}

// List mocks base method.
func (m *MockCompanyRepo) List(ctx context.Context, onlyActive bool) ([]domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, onlyActive)
	ret0, _ := ret[0].([]domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCompanyRepoMockRecorder) List(ctx, onlyActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCompanyRepo)(nil).List), ctx, onlyActive)
}

// SetActive mocks base method.
func (m *MockCompanyRepo) SetActive(ctx context.Context, id uuid.UUID, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockCompanyRepoMockRecorder) SetActive(ctx, id, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockCompanyRepo)(nil).SetActive), ctx, id, active)
}

// Update mocks base method.
func (m *MockCompanyRepo) Update(ctx context.Context, c domain.Company) (domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCompanyRepoMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCompanyRepo)(nil).Update), ctx, c)
}

// MockStrictnessRepo is a mock of StrictnessRepo interface.
type MockStrictnessRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStrictnessRepoMockRecorder
	isgomock struct{}
}

// MockStrictnessRepoMockRecorder is the mock recorder for MockStrictnessRepo.
type MockStrictnessRepoMockRecorder struct {
	mock *MockStrictnessRepo
}

// NewMockStrictnessRepo creates a new mock instance.
func NewMockStrictnessRepo(ctrl *gomock.Controller) *MockStrictnessRepo {
	mock := &MockStrictnessRepo{ctrl: ctrl}
	mock.recorder = &MockStrictnessRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrictnessRepo) EXPECT() *MockStrictnessRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStrictnessRepo) Create(ctx context.Context, p domain.AIStrictnessProfile) (domain.AIStrictnessProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(domain.AIStrictnessProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStrictnessRepoMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStrictnessRepo)(nil).Create), ctx, p)
}

// Get mocks base method.
func (m *MockStrictnessRepo) Get(ctx context.Context, id uuid.UUID) (domain.AIStrictnessProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.AIStrictnessProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStrictnessRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStrictnessRepo)(nil).Get), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockStrictnessRepo) GetBySlug(ctx context.Context, slug string) (domain.AIStrictnessProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(domain.AIStrictnessProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockStrictnessRepoMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockStrictnessRepo)(nil).GetBySlug), ctx, slug)
}

// List mocks base method.
func (m *MockStrictnessRepo) List(ctx context.Context, onlyActive bool) ([]domain.AIStrictnessProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, onlyActive)
	ret0, _ := ret[0].([]domain.AIStrictnessProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStrictnessRepoMockRecorder) List(ctx, onlyActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStrictnessRepo)(nil).List), ctx, onlyActive)
}

// SetActive mocks base method.
func (m *MockStrictnessRepo) SetActive(ctx context.Context, id uuid.UUID, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockStrictnessRepoMockRecorder) SetActive(ctx, id, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockStrictnessRepo)(nil).SetActive), ctx, id, active)
}

// Update mocks base method.
func (m *MockStrictnessRepo) Update(ctx context.Context, p domain.AIStrictnessProfile) (domain.AIStrictnessProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(domain.AIStrictnessProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStrictnessRepoMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStrictnessRepo)(nil).Update), ctx, p)
}

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
	isgomock struct{}
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTaskRepo) Create(ctx context.Context, t domain.MockTask) (domain.MockTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(domain.MockTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepoMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepo)(nil).Create), ctx, t)
}

// Get mocks base method.
func (m *MockTaskRepo) Get(ctx context.Context, id uuid.UUID) (domain.MockTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.MockTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaskRepo)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockTaskRepo) List(ctx context.Context, f domain.TaskFilter) ([]domain.MockTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, f)
	ret0, _ := ret[0].([]domain.MockTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTaskRepoMockRecorder) List(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepo)(nil).List), ctx, f)
}

// PickRandom mocks base method.
func (m *MockTaskRepo) PickRandom(ctx context.Context, stageKind domain.StageKind, languagePool []domain.TaskLanguage, taskPoolIDs []uuid.UUID) (domain.MockTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PickRandom", ctx, stageKind, languagePool, taskPoolIDs)
	ret0, _ := ret[0].(domain.MockTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PickRandom indicates an expected call of PickRandom.
func (mr *MockTaskRepoMockRecorder) PickRandom(ctx, stageKind, languagePool, taskPoolIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PickRandom", reflect.TypeOf((*MockTaskRepo)(nil).PickRandom), ctx, stageKind, languagePool, taskPoolIDs)
}

// SetActive mocks base method.
func (m *MockTaskRepo) SetActive(ctx context.Context, id uuid.UUID, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockTaskRepoMockRecorder) SetActive(ctx, id, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockTaskRepo)(nil).SetActive), ctx, id, active)
}

// Update mocks base method.
func (m *MockTaskRepo) Update(ctx context.Context, t domain.MockTask) (domain.MockTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, t)
	ret0, _ := ret[0].(domain.MockTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepoMockRecorder) Update(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepo)(nil).Update), ctx, t)
}

// MockQuestionRepo is a mock of QuestionRepo interface.
type MockQuestionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepoMockRecorder
	isgomock struct{}
}

// MockQuestionRepoMockRecorder is the mock recorder for MockQuestionRepo.
type MockQuestionRepoMockRecorder struct {
	mock *MockQuestionRepo
}

// NewMockQuestionRepo creates a new mock instance.
func NewMockQuestionRepo(ctrl *gomock.Controller) *MockQuestionRepo {
	mock := &MockQuestionRepo{ctrl: ctrl}
	mock.recorder = &MockQuestionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepo) EXPECT() *MockQuestionRepoMockRecorder {
	return m.recorder
}

// CreateCompanyQuestion mocks base method.
func (m *MockQuestionRepo) CreateCompanyQuestion(ctx context.Context, q domain.CompanyQuestion) (domain.CompanyQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompanyQuestion", ctx, q)
	ret0, _ := ret[0].(domain.CompanyQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCompanyQuestion indicates an expected call of CreateCompanyQuestion.
func (mr *MockQuestionRepoMockRecorder) CreateCompanyQuestion(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompanyQuestion", reflect.TypeOf((*MockQuestionRepo)(nil).CreateCompanyQuestion), ctx, q)
}

// CreateDefaultQuestion mocks base method.
func (m *MockQuestionRepo) CreateDefaultQuestion(ctx context.Context, q domain.DefaultQuestion) (domain.DefaultQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDefaultQuestion", ctx, q)
	ret0, _ := ret[0].(domain.DefaultQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDefaultQuestion indicates an expected call of CreateDefaultQuestion.
func (mr *MockQuestionRepoMockRecorder) CreateDefaultQuestion(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDefaultQuestion", reflect.TypeOf((*MockQuestionRepo)(nil).CreateDefaultQuestion), ctx, q)
}

// CreateTaskQuestion mocks base method.
func (m *MockQuestionRepo) CreateTaskQuestion(ctx context.Context, q domain.TaskQuestion) (domain.TaskQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskQuestion", ctx, q)
	ret0, _ := ret[0].(domain.TaskQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaskQuestion indicates an expected call of CreateTaskQuestion.
func (mr *MockQuestionRepoMockRecorder) CreateTaskQuestion(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskQuestion", reflect.TypeOf((*MockQuestionRepo)(nil).CreateTaskQuestion), ctx, q)
}

// DeleteCompanyQuestion mocks base method.
func (m *MockQuestionRepo) DeleteCompanyQuestion(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompanyQuestion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCompanyQuestion indicates an expected call of DeleteCompanyQuestion.
func (mr *MockQuestionRepoMockRecorder) DeleteCompanyQuestion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompanyQuestion", reflect.TypeOf((*MockQuestionRepo)(nil).DeleteCompanyQuestion), ctx, id)
}

// DeleteDefaultQuestion mocks base method.
func (m *MockQuestionRepo) DeleteDefaultQuestion(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDefaultQuestion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDefaultQuestion indicates an expected call of DeleteDefaultQuestion.
func (mr *MockQuestionRepoMockRecorder) DeleteDefaultQuestion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDefaultQuestion", reflect.TypeOf((*MockQuestionRepo)(nil).DeleteDefaultQuestion), ctx, id)
}

// DeleteTaskQuestion mocks base method.
func (m *MockQuestionRepo) DeleteTaskQuestion(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaskQuestion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaskQuestion indicates an expected call of DeleteTaskQuestion.
func (mr *MockQuestionRepoMockRecorder) DeleteTaskQuestion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaskQuestion", reflect.TypeOf((*MockQuestionRepo)(nil).DeleteTaskQuestion), ctx, id)
}

// ListCompanyQuestions mocks base method.
func (m *MockQuestionRepo) ListCompanyQuestions(ctx context.Context, companyID uuid.UUID, stage domain.StageKind) ([]domain.CompanyQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompanyQuestions", ctx, companyID, stage)
	ret0, _ := ret[0].([]domain.CompanyQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompanyQuestions indicates an expected call of ListCompanyQuestions.
func (mr *MockQuestionRepoMockRecorder) ListCompanyQuestions(ctx, companyID, stage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompanyQuestions", reflect.TypeOf((*MockQuestionRepo)(nil).ListCompanyQuestions), ctx, companyID, stage)
}

// ListDefaultQuestions mocks base method.
func (m *MockQuestionRepo) ListDefaultQuestions(ctx context.Context, stage domain.StageKind, onlyActive bool) ([]domain.DefaultQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDefaultQuestions", ctx, stage, onlyActive)
	ret0, _ := ret[0].([]domain.DefaultQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDefaultQuestions indicates an expected call of ListDefaultQuestions.
func (mr *MockQuestionRepoMockRecorder) ListDefaultQuestions(ctx, stage, onlyActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDefaultQuestions", reflect.TypeOf((*MockQuestionRepo)(nil).ListDefaultQuestions), ctx, stage, onlyActive)
}

// ListTaskQuestions mocks base method.
func (m *MockQuestionRepo) ListTaskQuestions(ctx context.Context, taskID uuid.UUID) ([]domain.TaskQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskQuestions", ctx, taskID)
	ret0, _ := ret[0].([]domain.TaskQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaskQuestions indicates an expected call of ListTaskQuestions.
func (mr *MockQuestionRepoMockRecorder) ListTaskQuestions(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskQuestions", reflect.TypeOf((*MockQuestionRepo)(nil).ListTaskQuestions), ctx, taskID)
}

// SampleCompanyQuestions mocks base method.
func (m *MockQuestionRepo) SampleCompanyQuestions(ctx context.Context, companyID uuid.UUID, stage domain.StageKind, limit int) ([]domain.CompanyQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SampleCompanyQuestions", ctx, companyID, stage, limit)
	ret0, _ := ret[0].([]domain.CompanyQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SampleCompanyQuestions indicates an expected call of SampleCompanyQuestions.
func (mr *MockQuestionRepoMockRecorder) SampleCompanyQuestions(ctx, companyID, stage, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SampleCompanyQuestions", reflect.TypeOf((*MockQuestionRepo)(nil).SampleCompanyQuestions), ctx, companyID, stage, limit)
}

// SampleDefaultQuestions mocks base method.
func (m *MockQuestionRepo) SampleDefaultQuestions(ctx context.Context, stage domain.StageKind, limit int) ([]domain.DefaultQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SampleDefaultQuestions", ctx, stage, limit)
	ret0, _ := ret[0].([]domain.DefaultQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SampleDefaultQuestions indicates an expected call of SampleDefaultQuestions.
func (mr *MockQuestionRepoMockRecorder) SampleDefaultQuestions(ctx, stage, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SampleDefaultQuestions", reflect.TypeOf((*MockQuestionRepo)(nil).SampleDefaultQuestions), ctx, stage, limit)
}

// UpdateCompanyQuestion mocks base method.
func (m *MockQuestionRepo) UpdateCompanyQuestion(ctx context.Context, q domain.CompanyQuestion) (domain.CompanyQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompanyQuestion", ctx, q)
	ret0, _ := ret[0].(domain.CompanyQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCompanyQuestion indicates an expected call of UpdateCompanyQuestion.
func (mr *MockQuestionRepoMockRecorder) UpdateCompanyQuestion(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompanyQuestion", reflect.TypeOf((*MockQuestionRepo)(nil).UpdateCompanyQuestion), ctx, q)
}

// UpdateDefaultQuestion mocks base method.
func (m *MockQuestionRepo) UpdateDefaultQuestion(ctx context.Context, q domain.DefaultQuestion) (domain.DefaultQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDefaultQuestion", ctx, q)
	ret0, _ := ret[0].(domain.DefaultQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDefaultQuestion indicates an expected call of UpdateDefaultQuestion.
func (mr *MockQuestionRepoMockRecorder) UpdateDefaultQuestion(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDefaultQuestion", reflect.TypeOf((*MockQuestionRepo)(nil).UpdateDefaultQuestion), ctx, q)
}

// UpdateTaskQuestion mocks base method.
func (m *MockQuestionRepo) UpdateTaskQuestion(ctx context.Context, q domain.TaskQuestion) (domain.TaskQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskQuestion", ctx, q)
	ret0, _ := ret[0].(domain.TaskQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskQuestion indicates an expected call of UpdateTaskQuestion.
func (mr *MockQuestionRepoMockRecorder) UpdateTaskQuestion(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskQuestion", reflect.TypeOf((*MockQuestionRepo)(nil).UpdateTaskQuestion), ctx, q)
}

// MockCompanyStageRepo is a mock of CompanyStageRepo interface.
type MockCompanyStageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyStageRepoMockRecorder
	isgomock struct{}
}

// MockCompanyStageRepoMockRecorder is the mock recorder for MockCompanyStageRepo.
type MockCompanyStageRepoMockRecorder struct {
	mock *MockCompanyStageRepo
}

// NewMockCompanyStageRepo creates a new mock instance.
func NewMockCompanyStageRepo(ctrl *gomock.Controller) *MockCompanyStageRepo {
	mock := &MockCompanyStageRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyStageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyStageRepo) EXPECT() *MockCompanyStageRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCompanyStageRepo) Delete(ctx context.Context, companyID uuid.UUID, stage domain.StageKind) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, companyID, stage)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCompanyStageRepoMockRecorder) Delete(ctx, companyID, stage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCompanyStageRepo)(nil).Delete), ctx, companyID, stage)
}

// GetForCompany mocks base method.
func (m *MockCompanyStageRepo) GetForCompany(ctx context.Context, companyID uuid.UUID) ([]domain.CompanyStage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForCompany", ctx, companyID)
	ret0, _ := ret[0].([]domain.CompanyStage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForCompany indicates an expected call of GetForCompany.
func (mr *MockCompanyStageRepoMockRecorder) GetForCompany(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForCompany", reflect.TypeOf((*MockCompanyStageRepo)(nil).GetForCompany), ctx, companyID)
}

// ReplaceAll mocks base method.
func (m *MockCompanyStageRepo) ReplaceAll(ctx context.Context, companyID uuid.UUID, stages []domain.CompanyStage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAll", ctx, companyID, stages)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceAll indicates an expected call of ReplaceAll.
func (mr *MockCompanyStageRepoMockRecorder) ReplaceAll(ctx, companyID, stages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAll", reflect.TypeOf((*MockCompanyStageRepo)(nil).ReplaceAll), ctx, companyID, stages)
}

// Upsert mocks base method.
func (m *MockCompanyStageRepo) Upsert(ctx context.Context, s domain.CompanyStage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCompanyStageRepoMockRecorder) Upsert(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCompanyStageRepo)(nil).Upsert), ctx, s)
}

// MockPipelineRepo is a mock of PipelineRepo interface.
type MockPipelineRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineRepoMockRecorder
	isgomock struct{}
}

// MockPipelineRepoMockRecorder is the mock recorder for MockPipelineRepo.
type MockPipelineRepoMockRecorder struct {
	mock *MockPipelineRepo
}

// NewMockPipelineRepo creates a new mock instance.
func NewMockPipelineRepo(ctrl *gomock.Controller) *MockPipelineRepo {
	mock := &MockPipelineRepo{ctrl: ctrl}
	mock.recorder = &MockPipelineRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelineRepo) EXPECT() *MockPipelineRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPipelineRepo) Create(ctx context.Context, p domain.MockPipeline) (domain.MockPipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(domain.MockPipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPipelineRepoMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPipelineRepo)(nil).Create), ctx, p)
}

// Get mocks base method.
func (m *MockPipelineRepo) Get(ctx context.Context, id uuid.UUID) (domain.MockPipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.MockPipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPipelineRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPipelineRepo)(nil).Get), ctx, id)
}

// IncrementStageIdx mocks base method.
func (m *MockPipelineRepo) IncrementStageIdx(ctx context.Context, id uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementStageIdx", ctx, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementStageIdx indicates an expected call of IncrementStageIdx.
func (mr *MockPipelineRepoMockRecorder) IncrementStageIdx(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementStageIdx", reflect.TypeOf((*MockPipelineRepo)(nil).IncrementStageIdx), ctx, id)
}

// ListByUser mocks base method.
func (m *MockPipelineRepo) ListByUser(ctx context.Context, userID uuid.UUID, limit int) ([]domain.MockPipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.MockPipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockPipelineRepoMockRecorder) ListByUser(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockPipelineRepo)(nil).ListByUser), ctx, userID, limit)
}

// UpdateVerdict mocks base method.
func (m *MockPipelineRepo) UpdateVerdict(ctx context.Context, id uuid.UUID, verdict domain.PipelineVerdict, totalScore *float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerdict", ctx, id, verdict, totalScore)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVerdict indicates an expected call of UpdateVerdict.
func (mr *MockPipelineRepoMockRecorder) UpdateVerdict(ctx, id, verdict, totalScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerdict", reflect.TypeOf((*MockPipelineRepo)(nil).UpdateVerdict), ctx, id, verdict, totalScore)
}

// MockPipelineStageRepo is a mock of PipelineStageRepo interface.
type MockPipelineStageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineStageRepoMockRecorder
	isgomock struct{}
}

// MockPipelineStageRepoMockRecorder is the mock recorder for MockPipelineStageRepo.
type MockPipelineStageRepoMockRecorder struct {
	mock *MockPipelineStageRepo
}

// NewMockPipelineStageRepo creates a new mock instance.
func NewMockPipelineStageRepo(ctrl *gomock.Controller) *MockPipelineStageRepo {
	mock := &MockPipelineStageRepo{ctrl: ctrl}
	mock.recorder = &MockPipelineStageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelineStageRepo) EXPECT() *MockPipelineStageRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPipelineStageRepo) Create(ctx context.Context, s domain.PipelineStage) (domain.PipelineStage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(domain.PipelineStage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPipelineStageRepoMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPipelineStageRepo)(nil).Create), ctx, s)
}

// FinishStage mocks base method.
func (m *MockPipelineStageRepo) FinishStage(ctx context.Context, id uuid.UUID, score float32, verdict domain.StageVerdict, feedback string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishStage", ctx, id, score, verdict, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishStage indicates an expected call of FinishStage.
func (mr *MockPipelineStageRepoMockRecorder) FinishStage(ctx, id, score, verdict, feedback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishStage", reflect.TypeOf((*MockPipelineStageRepo)(nil).FinishStage), ctx, id, score, verdict, feedback)
}

// Get mocks base method.
func (m *MockPipelineStageRepo) Get(ctx context.Context, id uuid.UUID) (domain.PipelineStage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.PipelineStage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPipelineStageRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPipelineStageRepo)(nil).Get), ctx, id)
}

// ListByPipeline mocks base method.
func (m *MockPipelineStageRepo) ListByPipeline(ctx context.Context, pipelineID uuid.UUID) ([]domain.PipelineStage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPipeline", ctx, pipelineID)
	ret0, _ := ret[0].([]domain.PipelineStage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPipeline indicates an expected call of ListByPipeline.
func (mr *MockPipelineStageRepoMockRecorder) ListByPipeline(ctx, pipelineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPipeline", reflect.TypeOf((*MockPipelineStageRepo)(nil).ListByPipeline), ctx, pipelineID)
}

// UpdateStartStage mocks base method.
func (m *MockPipelineStageRepo) UpdateStartStage(ctx context.Context, id, profileID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStartStage", ctx, id, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStartStage indicates an expected call of UpdateStartStage.
func (mr *MockPipelineStageRepoMockRecorder) UpdateStartStage(ctx, id, profileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStartStage", reflect.TypeOf((*MockPipelineStageRepo)(nil).UpdateStartStage), ctx, id, profileID)
}

// UpdateStatus mocks base method.
func (m *MockPipelineStageRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.StageStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPipelineStageRepoMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPipelineStageRepo)(nil).UpdateStatus), ctx, id, status)
}

// MockPipelineAttemptRepo is a mock of PipelineAttemptRepo interface.
type MockPipelineAttemptRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineAttemptRepoMockRecorder
	isgomock struct{}
}

// MockPipelineAttemptRepoMockRecorder is the mock recorder for MockPipelineAttemptRepo.
type MockPipelineAttemptRepoMockRecorder struct {
	mock *MockPipelineAttemptRepo
}

// NewMockPipelineAttemptRepo creates a new mock instance.
func NewMockPipelineAttemptRepo(ctrl *gomock.Controller) *MockPipelineAttemptRepo {
	mock := &MockPipelineAttemptRepo{ctrl: ctrl}
	mock.recorder = &MockPipelineAttemptRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelineAttemptRepo) EXPECT() *MockPipelineAttemptRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPipelineAttemptRepo) Create(ctx context.Context, a domain.PipelineAttempt) (domain.PipelineAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(domain.PipelineAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPipelineAttemptRepoMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPipelineAttemptRepo)(nil).Create), ctx, a)
}

// Get mocks base method.
func (m *MockPipelineAttemptRepo) Get(ctx context.Context, id uuid.UUID) (domain.PipelineAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.PipelineAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPipelineAttemptRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPipelineAttemptRepo)(nil).Get), ctx, id)
}

// GetWithQuestion mocks base method.
func (m *MockPipelineAttemptRepo) GetWithQuestion(ctx context.Context, id uuid.UUID) (domain.AttemptWithQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithQuestion", ctx, id)
	ret0, _ := ret[0].(domain.AttemptWithQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithQuestion indicates an expected call of GetWithQuestion.
func (mr *MockPipelineAttemptRepoMockRecorder) GetWithQuestion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithQuestion", reflect.TypeOf((*MockPipelineAttemptRepo)(nil).GetWithQuestion), ctx, id)
}

// ListByStage mocks base method.
func (m *MockPipelineAttemptRepo) ListByStage(ctx context.Context, pipelineStageID uuid.UUID) ([]domain.PipelineAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStage", ctx, pipelineStageID)
	ret0, _ := ret[0].([]domain.PipelineAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStage indicates an expected call of ListByStage.
func (mr *MockPipelineAttemptRepoMockRecorder) ListByStage(ctx, pipelineStageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStage", reflect.TypeOf((*MockPipelineAttemptRepo)(nil).ListByStage), ctx, pipelineStageID)
}

// UpdateCanvasResult mocks base method.
func (m *MockPipelineAttemptRepo) UpdateCanvasResult(ctx context.Context, id uuid.UUID, in domain.CanvasResultUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCanvasResult", ctx, id, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCanvasResult indicates an expected call of UpdateCanvasResult.
func (mr *MockPipelineAttemptRepoMockRecorder) UpdateCanvasResult(ctx, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCanvasResult", reflect.TypeOf((*MockPipelineAttemptRepo)(nil).UpdateCanvasResult), ctx, id, in)
}

// UpdateJudgeResult mocks base method.
func (m *MockPipelineAttemptRepo) UpdateJudgeResult(ctx context.Context, id uuid.UUID, userAnswerMD string, score, waterScore float32, verdict domain.AttemptVerdict, feedback string, missingPoints []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJudgeResult", ctx, id, userAnswerMD, score, waterScore, verdict, feedback, missingPoints)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJudgeResult indicates an expected call of UpdateJudgeResult.
func (mr *MockPipelineAttemptRepoMockRecorder) UpdateJudgeResult(ctx, id, userAnswerMD, score, waterScore, verdict, feedback, missingPoints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJudgeResult", reflect.TypeOf((*MockPipelineAttemptRepo)(nil).UpdateJudgeResult), ctx, id, userAnswerMD, score, waterScore, verdict, feedback, missingPoints)
}
