// Code generated by MockGen. DO NOT EDIT.
// Source: sandbox.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/sandbox_mock.go -source sandbox.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/mock_interview/domain"
	enums "druz9/shared/enums"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMockTaskTestCaseRepo is a mock of MockTaskTestCaseRepo interface.
type MockMockTaskTestCaseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMockTaskTestCaseRepoMockRecorder
	isgomock struct{}
}

// MockMockTaskTestCaseRepoMockRecorder is the mock recorder for MockMockTaskTestCaseRepo.
type MockMockTaskTestCaseRepoMockRecorder struct {
	mock *MockMockTaskTestCaseRepo
}

// NewMockMockTaskTestCaseRepo creates a new mock instance.
func NewMockMockTaskTestCaseRepo(ctrl *gomock.Controller) *MockMockTaskTestCaseRepo {
	mock := &MockMockTaskTestCaseRepo{ctrl: ctrl}
	mock.recorder = &MockMockTaskTestCaseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMockTaskTestCaseRepo) EXPECT() *MockMockTaskTestCaseRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMockTaskTestCaseRepo) Create(ctx context.Context, tc domain.MockTaskTestCase) (domain.MockTaskTestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tc)
	ret0, _ := ret[0].(domain.MockTaskTestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMockTaskTestCaseRepoMockRecorder) Create(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMockTaskTestCaseRepo)(nil).Create), ctx, tc)
}

// Delete mocks base method.
func (m *MockMockTaskTestCaseRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMockTaskTestCaseRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMockTaskTestCaseRepo)(nil).Delete), ctx, id)
}

// ListForTask mocks base method.
func (m *MockMockTaskTestCaseRepo) ListForTask(ctx context.Context, taskID uuid.UUID) ([]domain.MockTaskTestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForTask", ctx, taskID)
	ret0, _ := ret[0].([]domain.MockTaskTestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForTask indicates an expected call of ListForTask.
func (mr *MockMockTaskTestCaseRepoMockRecorder) ListForTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForTask", reflect.TypeOf((*MockMockTaskTestCaseRepo)(nil).ListForTask), ctx, taskID)
}

// Update mocks base method.
func (m *MockMockTaskTestCaseRepo) Update(ctx context.Context, tc domain.MockTaskTestCase) (domain.MockTaskTestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tc)
	ret0, _ := ret[0].(domain.MockTaskTestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMockTaskTestCaseRepoMockRecorder) Update(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMockTaskTestCaseRepo)(nil).Update), ctx, tc)
}

// MockSandboxExecutor is a mock of SandboxExecutor interface.
type MockSandboxExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockSandboxExecutorMockRecorder
	isgomock struct{}
}

// MockSandboxExecutorMockRecorder is the mock recorder for MockSandboxExecutor.
type MockSandboxExecutorMockRecorder struct {
	mock *MockSandboxExecutor
}

// NewMockSandboxExecutor creates a new mock instance.
func NewMockSandboxExecutor(ctrl *gomock.Controller) *MockSandboxExecutor {
	mock := &MockSandboxExecutor{ctrl: ctrl}
	mock.recorder = &MockSandboxExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSandboxExecutor) EXPECT() *MockSandboxExecutorMockRecorder {
	return m.recorder
}

// Available mocks base method.
func (m *MockSandboxExecutor) Available() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Available")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Available indicates an expected call of Available.
func (mr *MockSandboxExecutorMockRecorder) Available() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Available", reflect.TypeOf((*MockSandboxExecutor)(nil).Available))
}

// Submit mocks base method.
func (m *MockSandboxExecutor) Submit(ctx context.Context, code string, language enums.Language, taskID uuid.UUID) (domain.SandboxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, code, language, taskID)
	ret0, _ := ret[0].(domain.SandboxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockSandboxExecutorMockRecorder) Submit(ctx, code, language, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockSandboxExecutor)(nil).Submit), ctx, code, language, taskID)
}

// MockDetailedSandboxExecutor is a mock of DetailedSandboxExecutor interface.
type MockDetailedSandboxExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockDetailedSandboxExecutorMockRecorder
	isgomock struct{}
}

// MockDetailedSandboxExecutorMockRecorder is the mock recorder for MockDetailedSandboxExecutor.
type MockDetailedSandboxExecutorMockRecorder struct {
	mock *MockDetailedSandboxExecutor
}

// NewMockDetailedSandboxExecutor creates a new mock instance.
func NewMockDetailedSandboxExecutor(ctrl *gomock.Controller) *MockDetailedSandboxExecutor {
	mock := &MockDetailedSandboxExecutor{ctrl: ctrl}
	mock.recorder = &MockDetailedSandboxExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetailedSandboxExecutor) EXPECT() *MockDetailedSandboxExecutorMockRecorder {
	return m.recorder
}

// Available mocks base method.
func (m *MockDetailedSandboxExecutor) Available() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Available")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Available indicates an expected call of Available.
func (mr *MockDetailedSandboxExecutorMockRecorder) Available() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Available", reflect.TypeOf((*MockDetailedSandboxExecutor)(nil).Available))
}

// Submit mocks base method.
func (m *MockDetailedSandboxExecutor) Submit(ctx context.Context, code string, language enums.Language, taskID uuid.UUID) (domain.SandboxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, code, language, taskID)
	ret0, _ := ret[0].(domain.SandboxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockDetailedSandboxExecutorMockRecorder) Submit(ctx, code, language, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockDetailedSandboxExecutor)(nil).Submit), ctx, code, language, taskID)
}

// SubmitDetailed mocks base method.
func (m *MockDetailedSandboxExecutor) SubmitDetailed(ctx context.Context, code string, language enums.Language, taskID uuid.UUID) ([]domain.SandboxCaseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitDetailed", ctx, code, language, taskID)
	ret0, _ := ret[0].([]domain.SandboxCaseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitDetailed indicates an expected call of SubmitDetailed.
func (mr *MockDetailedSandboxExecutorMockRecorder) SubmitDetailed(ctx, code, language, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitDetailed", reflect.TypeOf((*MockDetailedSandboxExecutor)(nil).SubmitDetailed), ctx, code, language, taskID)
}
