// Code generated by MockGen. DO NOT EDIT.
// Source: skill_writer.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/skill_writer_mock.go -source skill_writer.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSkillNodeWriter is a mock of SkillNodeWriter interface.
type MockSkillNodeWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSkillNodeWriterMockRecorder
	isgomock struct{}
}

// MockSkillNodeWriterMockRecorder is the mock recorder for MockSkillNodeWriter.
type MockSkillNodeWriterMockRecorder struct {
	mock *MockSkillNodeWriter
}

// NewMockSkillNodeWriter creates a new mock instance.
func NewMockSkillNodeWriter(ctrl *gomock.Controller) *MockSkillNodeWriter {
	mock := &MockSkillNodeWriter{ctrl: ctrl}
	mock.recorder = &MockSkillNodeWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillNodeWriter) EXPECT() *MockSkillNodeWriterMockRecorder {
	return m.recorder
}

// UpsertSkillNode mocks base method.
func (m *MockSkillNodeWriter) UpsertSkillNode(ctx context.Context, userID uuid.UUID, nodeKey string, progress int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSkillNode", ctx, userID, nodeKey, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSkillNode indicates an expected call of UpsertSkillNode.
func (mr *MockSkillNodeWriterMockRecorder) UpsertSkillNode(ctx, userID, nodeKey, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSkillNode", reflect.TypeOf((*MockSkillNodeWriter)(nil).UpsertSkillNode), ctx, userID, nodeKey, progress)
}
