// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/repo_mock.go -source repo.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/whiteboard_rooms/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomRepo is a mock of RoomRepo interface.
type MockRoomRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRepoMockRecorder
	isgomock struct{}
}

// MockRoomRepoMockRecorder is the mock recorder for MockRoomRepo.
type MockRoomRepoMockRecorder struct {
	mock *MockRoomRepo
}

// NewMockRoomRepo creates a new mock instance.
func NewMockRoomRepo(ctrl *gomock.Controller) *MockRoomRepo {
	mock := &MockRoomRepo{ctrl: ctrl}
	mock.recorder = &MockRoomRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRepo) EXPECT() *MockRoomRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomRepo) Create(ctx context.Context, r domain.Room) (domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRoomRepoMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomRepo)(nil).Create), ctx, r)
}

// Delete mocks base method.
func (m *MockRoomRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoomRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoomRepo)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockRoomRepo) Get(ctx context.Context, id uuid.UUID) (domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoomRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoomRepo)(nil).Get), ctx, id)
}

// ListByUser mocks base method.
func (m *MockRoomRepo) ListByUser(ctx context.Context, userID uuid.UUID) ([]domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockRoomRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockRoomRepo)(nil).ListByUser), ctx, userID)
}

// SetVisibility mocks base method.
func (m *MockRoomRepo) SetVisibility(ctx context.Context, id uuid.UUID, visibility domain.Visibility) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVisibility", ctx, id, visibility)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVisibility indicates an expected call of SetVisibility.
func (mr *MockRoomRepoMockRecorder) SetVisibility(ctx, id, visibility any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVisibility", reflect.TypeOf((*MockRoomRepo)(nil).SetVisibility), ctx, id, visibility)
}

// UpdateSnapshot mocks base method.
func (m *MockRoomRepo) UpdateSnapshot(ctx context.Context, id uuid.UUID, snapshot []byte, expires time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSnapshot", ctx, id, snapshot, expires)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSnapshot indicates an expected call of UpdateSnapshot.
func (mr *MockRoomRepoMockRecorder) UpdateSnapshot(ctx, id, snapshot, expires any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSnapshot", reflect.TypeOf((*MockRoomRepo)(nil).UpdateSnapshot), ctx, id, snapshot, expires)
}

// MockParticipantRepo is a mock of ParticipantRepo interface.
type MockParticipantRepo struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantRepoMockRecorder
	isgomock struct{}
}

// MockParticipantRepoMockRecorder is the mock recorder for MockParticipantRepo.
type MockParticipantRepoMockRecorder struct {
	mock *MockParticipantRepo
}

// NewMockParticipantRepo creates a new mock instance.
func NewMockParticipantRepo(ctrl *gomock.Controller) *MockParticipantRepo {
	mock := &MockParticipantRepo{ctrl: ctrl}
	mock.recorder = &MockParticipantRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantRepo) EXPECT() *MockParticipantRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockParticipantRepo) Add(ctx context.Context, p domain.Participant) (domain.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, p)
	ret0, _ := ret[0].(domain.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockParticipantRepoMockRecorder) Add(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockParticipantRepo)(nil).Add), ctx, p)
}

// Exists mocks base method.
func (m *MockParticipantRepo) Exists(ctx context.Context, roomID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, roomID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockParticipantRepoMockRecorder) Exists(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockParticipantRepo)(nil).Exists), ctx, roomID, userID)
}

// List mocks base method.
func (m *MockParticipantRepo) List(ctx context.Context, roomID uuid.UUID) ([]domain.ParticipantWithUsername, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, roomID)
	ret0, _ := ret[0].([]domain.ParticipantWithUsername)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockParticipantRepoMockRecorder) List(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockParticipantRepo)(nil).List), ctx, roomID)
}

// MockTokenVerifier is a mock of TokenVerifier interface.
type MockTokenVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockTokenVerifierMockRecorder
	isgomock struct{}
}

// MockTokenVerifierMockRecorder is the mock recorder for MockTokenVerifier.
type MockTokenVerifierMockRecorder struct {
	mock *MockTokenVerifier
}

// NewMockTokenVerifier creates a new mock instance.
func NewMockTokenVerifier(ctrl *gomock.Controller) *MockTokenVerifier {
	mock := &MockTokenVerifier{ctrl: ctrl}
	mock.recorder = &MockTokenVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenVerifier) EXPECT() *MockTokenVerifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockTokenVerifier) Verify(raw string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", raw)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockTokenVerifierMockRecorder) Verify(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockTokenVerifier)(nil).Verify), raw)
}

// VerifyScoped mocks base method.
func (m *MockTokenVerifier) VerifyScoped(raw, expectedScope string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyScoped", raw, expectedScope)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyScoped indicates an expected call of VerifyScoped.
func (mr *MockTokenVerifierMockRecorder) VerifyScoped(raw, expectedScope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyScoped", reflect.TypeOf((*MockTokenVerifier)(nil).VerifyScoped), raw, expectedScope)
}
