// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild.sql

package guilddb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentWarForGuild = `-- name: GetCurrentWarForGuild :one
SELECT id, guild_a_id, guild_b_id, week_start, week_end,
       scores_a, scores_b, winner_id, created_at
  FROM guild_wars
 WHERE (guild_a_id = $1 OR guild_b_id = $1)
   AND week_start <= $2::date
   AND week_end   >  $2::date
 ORDER BY week_start DESC
 LIMIT 1
`

type GetCurrentWarForGuildParams struct {
	GuildAID pgtype.UUID
	Column2  pgtype.Date
}

// A war is "current" for a guild when the given instant falls between its
// week_start (inclusive) and week_end (exclusive). We cast `now` to a DATE
// because the migration stores week bounds as DATE, not TIMESTAMPTZ.
func (q *Queries) GetCurrentWarForGuild(ctx context.Context, arg GetCurrentWarForGuildParams) (GuildWar, error) {
	row := q.db.QueryRow(ctx, getCurrentWarForGuild, arg.GuildAID, arg.Column2)
	var i GuildWar
	err := row.Scan(
		&i.ID,
		&i.GuildAID,
		&i.GuildBID,
		&i.WeekStart,
		&i.WeekEnd,
		&i.ScoresA,
		&i.ScoresB,
		&i.WinnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getGuild = `-- name: GetGuild :one
SELECT id, owner_id, name, emblem, guild_elo, created_at
  FROM guilds WHERE id = $1
`

type GetGuildRow struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Emblem    pgtype.Text
	GuildElo  int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetGuild(ctx context.Context, id pgtype.UUID) (GetGuildRow, error) {
	row := q.db.QueryRow(ctx, getGuild, id)
	var i GetGuildRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Emblem,
		&i.GuildElo,
		&i.CreatedAt,
	)
	return i, err
}

const getGuildMember = `-- name: GetGuildMember :one
SELECT gm.guild_id,
       gm.user_id,
       u.username,
       gm.role,
       gm.assigned_section,
       gm.joined_at
  FROM guild_members gm
  JOIN users u ON u.id = gm.user_id
 WHERE gm.guild_id = $1 AND gm.user_id = $2
`

type GetGuildMemberParams struct {
	GuildID pgtype.UUID
	UserID  pgtype.UUID
}

type GetGuildMemberRow struct {
	GuildID         pgtype.UUID
	UserID          pgtype.UUID
	Username        string
	Role            string
	AssignedSection pgtype.Text
	JoinedAt        pgtype.Timestamptz
}

func (q *Queries) GetGuildMember(ctx context.Context, arg GetGuildMemberParams) (GetGuildMemberRow, error) {
	row := q.db.QueryRow(ctx, getGuildMember, arg.GuildID, arg.UserID)
	var i GetGuildMemberRow
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.AssignedSection,
		&i.JoinedAt,
	)
	return i, err
}

const getMyGuild = `-- name: GetMyGuild :one
SELECT g.id, g.owner_id, g.name, g.emblem, g.guild_elo, g.created_at
  FROM guilds g
  JOIN guild_members gm ON gm.guild_id = g.id
 WHERE gm.user_id = $1
 LIMIT 1
`

type GetMyGuildRow struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Emblem    pgtype.Text
	GuildElo  int32
	CreatedAt pgtype.Timestamptz
}

// Resolve the single guild a user belongs to (guild_members has a UNIQUE index
// on user_id, so at most one row matches).
func (q *Queries) GetMyGuild(ctx context.Context, userID pgtype.UUID) (GetMyGuildRow, error) {
	row := q.db.QueryRow(ctx, getMyGuild, userID)
	var i GetMyGuildRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Emblem,
		&i.GuildElo,
		&i.CreatedAt,
	)
	return i, err
}

const getWar = `-- name: GetWar :one
SELECT id, guild_a_id, guild_b_id, week_start, week_end,
       scores_a, scores_b, winner_id, created_at
  FROM guild_wars WHERE id = $1
`

func (q *Queries) GetWar(ctx context.Context, id pgtype.UUID) (GuildWar, error) {
	row := q.db.QueryRow(ctx, getWar, id)
	var i GuildWar
	err := row.Scan(
		&i.ID,
		&i.GuildAID,
		&i.GuildBID,
		&i.WeekStart,
		&i.WeekEnd,
		&i.ScoresA,
		&i.ScoresB,
		&i.WinnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listGuildMembers = `-- name: ListGuildMembers :many
SELECT gm.guild_id,
       gm.user_id,
       u.username,
       gm.role,
       gm.assigned_section,
       gm.joined_at
  FROM guild_members gm
  JOIN users u ON u.id = gm.user_id
 WHERE gm.guild_id = $1
 ORDER BY gm.joined_at
`

type ListGuildMembersRow struct {
	GuildID         pgtype.UUID
	UserID          pgtype.UUID
	Username        string
	Role            string
	AssignedSection pgtype.Text
	JoinedAt        pgtype.Timestamptz
}

func (q *Queries) ListGuildMembers(ctx context.Context, guildID pgtype.UUID) ([]ListGuildMembersRow, error) {
	rows, err := q.db.Query(ctx, listGuildMembers, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildMembersRow{}
	for rows.Next() {
		var i ListGuildMembersRow
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.AssignedSection,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopGuilds = `-- name: ListTopGuilds :many
SELECT g.id,
       g.name,
       g.emblem,
       g.guild_elo,
       (SELECT COUNT(*)::int FROM guild_members gm WHERE gm.guild_id = g.id)        AS members_count,
       (SELECT COUNT(*)::int FROM guild_wars gw WHERE gw.winner_id = g.id)          AS wars_won
  FROM guilds g
 ORDER BY g.guild_elo DESC, g.id ASC
 LIMIT $1
`

type ListTopGuildsRow struct {
	ID           pgtype.UUID
	Name         string
	Emblem       pgtype.Text
	GuildElo     int32
	MembersCount int32
	WarsWon      int32
}

// Global guild leaderboard. We surface the existing guild_elo column as the
// primary ranking metric (the bible's "elo_total" — guilds carry a single
// ELO, members aren't summed, so this is the right pivot). members_count is
// a simple correlated count. wars_won counts every guild_wars row where
// this guild is the recorded winner. The ORDER BY is deterministic on ties
// (elo desc, id asc) so the cache is consistent across reads.
func (q *Queries) ListTopGuilds(ctx context.Context, limit int32) ([]ListTopGuildsRow, error) {
	rows, err := q.db.Query(ctx, listTopGuilds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopGuildsRow{}
	for rows.Next() {
		var i ListTopGuildsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Emblem,
			&i.GuildElo,
			&i.MembersCount,
			&i.WarsWon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWarWinner = `-- name: SetWarWinner :execrows
UPDATE guild_wars
   SET winner_id = $2
 WHERE id = $1
`

type SetWarWinnerParams struct {
	ID       pgtype.UUID
	WinnerID pgtype.UUID
}

func (q *Queries) SetWarWinner(ctx context.Context, arg SetWarWinnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWarWinner, arg.ID, arg.WinnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertGuild = `-- name: UpsertGuild :one

INSERT INTO guilds(owner_id, name, emblem, guild_elo)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE
    SET emblem    = EXCLUDED.emblem,
        guild_elo = EXCLUDED.guild_elo
RETURNING id, owner_id, name, emblem, guild_elo, created_at
`

type UpsertGuildParams struct {
	OwnerID  pgtype.UUID
	Name     string
	Emblem   pgtype.Text
	GuildElo int32
}

type UpsertGuildRow struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Emblem    pgtype.Text
	GuildElo  int32
	CreatedAt pgtype.Timestamptz
}

// guild queries consumed by sqlc (emitted into services/guild/infra/db).
// Contribution row storage is STUBBED in-memory at the infra layer — the
// current migration does not have a war_contributions table. The queries
// below cover what the domain persists on Postgres today.
func (q *Queries) UpsertGuild(ctx context.Context, arg UpsertGuildParams) (UpsertGuildRow, error) {
	row := q.db.QueryRow(ctx, upsertGuild,
		arg.OwnerID,
		arg.Name,
		arg.Emblem,
		arg.GuildElo,
	)
	var i UpsertGuildRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Emblem,
		&i.GuildElo,
		&i.CreatedAt,
	)
	return i, err
}

const upsertWarScoreA = `-- name: UpsertWarScoreA :execrows
UPDATE guild_wars
   SET scores_a = jsonb_set(
       scores_a,
       ARRAY[$2::text],
       to_jsonb(COALESCE((scores_a->>$2)::int, 0) + $3::int),
       true
   )
 WHERE id = $1
`

type UpsertWarScoreAParams struct {
	ID      pgtype.UUID
	Column2 string
	Column3 int32
}

// Add `delta` to scores_a[section] (JSONB). COALESCE handles first-write.
func (q *Queries) UpsertWarScoreA(ctx context.Context, arg UpsertWarScoreAParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertWarScoreA, arg.ID, arg.Column2, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWarScoreB = `-- name: UpsertWarScoreB :execrows
UPDATE guild_wars
   SET scores_b = jsonb_set(
       scores_b,
       ARRAY[$2::text],
       to_jsonb(COALESCE((scores_b->>$2)::int, 0) + $3::int),
       true
   )
 WHERE id = $1
`

type UpsertWarScoreBParams struct {
	ID      pgtype.UUID
	Column2 string
	Column3 int32
}

func (q *Queries) UpsertWarScoreB(ctx context.Context, arg UpsertWarScoreBParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertWarScoreB, arg.ID, arg.Column2, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
