// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package subscriptiondb

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ClubAttendeeStatus string

const (
	ClubAttendeeStatusRsvpYes  ClubAttendeeStatus = "rsvp_yes"
	ClubAttendeeStatusRsvpNo   ClubAttendeeStatus = "rsvp_no"
	ClubAttendeeStatusAttended ClubAttendeeStatus = "attended"
	ClubAttendeeStatusNoShow   ClubAttendeeStatus = "no_show"
)

func (e *ClubAttendeeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClubAttendeeStatus(s)
	case string:
		*e = ClubAttendeeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ClubAttendeeStatus: %T", src)
	}
	return nil
}

type NullClubAttendeeStatus struct {
	ClubAttendeeStatus ClubAttendeeStatus
	Valid              bool // Valid is true if ClubAttendeeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClubAttendeeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ClubAttendeeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClubAttendeeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClubAttendeeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClubAttendeeStatus), nil
}

type ClubSessionStatus string

const (
	ClubSessionStatusScheduled ClubSessionStatus = "scheduled"
	ClubSessionStatusLive      ClubSessionStatus = "live"
	ClubSessionStatusDone      ClubSessionStatus = "done"
	ClubSessionStatusCancelled ClubSessionStatus = "cancelled"
)

func (e *ClubSessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClubSessionStatus(s)
	case string:
		*e = ClubSessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ClubSessionStatus: %T", src)
	}
	return nil
}

type NullClubSessionStatus struct {
	ClubSessionStatus ClubSessionStatus
	Valid             bool // Valid is true if ClubSessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClubSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ClubSessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClubSessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClubSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClubSessionStatus), nil
}

type InsightSeverity string

const (
	InsightSeverityCruise   InsightSeverity = "cruise"
	InsightSeverityNudge    InsightSeverity = "nudge"
	InsightSeverityWarn     InsightSeverity = "warn"
	InsightSeverityCritical InsightSeverity = "critical"
)

func (e *InsightSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InsightSeverity(s)
	case string:
		*e = InsightSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for InsightSeverity: %T", src)
	}
	return nil
}

type NullInsightSeverity struct {
	InsightSeverity InsightSeverity
	Valid           bool // Valid is true if InsightSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInsightSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.InsightSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InsightSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInsightSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InsightSeverity), nil
}

type MockPipelineVerdict string

const (
	MockPipelineVerdictInProgress MockPipelineVerdict = "in_progress"
	MockPipelineVerdictPass       MockPipelineVerdict = "pass"
	MockPipelineVerdictFail       MockPipelineVerdict = "fail"
	MockPipelineVerdictCancelled  MockPipelineVerdict = "cancelled"
)

func (e *MockPipelineVerdict) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MockPipelineVerdict(s)
	case string:
		*e = MockPipelineVerdict(s)
	default:
		return fmt.Errorf("unsupported scan type for MockPipelineVerdict: %T", src)
	}
	return nil
}

type NullMockPipelineVerdict struct {
	MockPipelineVerdict MockPipelineVerdict
	Valid               bool // Valid is true if MockPipelineVerdict is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMockPipelineVerdict) Scan(value interface{}) error {
	if value == nil {
		ns.MockPipelineVerdict, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MockPipelineVerdict.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMockPipelineVerdict) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MockPipelineVerdict), nil
}

type PersonalEventKind string

const (
	PersonalEventKindInterview          PersonalEventKind = "interview"
	PersonalEventKindDeadline           PersonalEventKind = "deadline"
	PersonalEventKindExam               PersonalEventKind = "exam"
	PersonalEventKindClubSession        PersonalEventKind = "club_session"
	PersonalEventKindStudyBlock         PersonalEventKind = "study_block"
	PersonalEventKindInterviewPrepBlock PersonalEventKind = "interview_prep_block"
)

func (e *PersonalEventKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PersonalEventKind(s)
	case string:
		*e = PersonalEventKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PersonalEventKind: %T", src)
	}
	return nil
}

type NullPersonalEventKind struct {
	PersonalEventKind PersonalEventKind
	Valid             bool // Valid is true if PersonalEventKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPersonalEventKind) Scan(value interface{}) error {
	if value == nil {
		ns.PersonalEventKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PersonalEventKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPersonalEventKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PersonalEventKind), nil
}

type PersonalEventReminderHorizon string

const (
	PersonalEventReminderHorizonT24h PersonalEventReminderHorizon = "t24h"
	PersonalEventReminderHorizonT1h  PersonalEventReminderHorizon = "t1h"
	PersonalEventReminderHorizonNow  PersonalEventReminderHorizon = "now"
)

func (e *PersonalEventReminderHorizon) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PersonalEventReminderHorizon(s)
	case string:
		*e = PersonalEventReminderHorizon(s)
	default:
		return fmt.Errorf("unsupported scan type for PersonalEventReminderHorizon: %T", src)
	}
	return nil
}

type NullPersonalEventReminderHorizon struct {
	PersonalEventReminderHorizon PersonalEventReminderHorizon
	Valid                        bool // Valid is true if PersonalEventReminderHorizon is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPersonalEventReminderHorizon) Scan(value interface{}) error {
	if value == nil {
		ns.PersonalEventReminderHorizon, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PersonalEventReminderHorizon.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPersonalEventReminderHorizon) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PersonalEventReminderHorizon), nil
}

type PersonalEventStatus string

const (
	PersonalEventStatusPlanned   PersonalEventStatus = "planned"
	PersonalEventStatusLive      PersonalEventStatus = "live"
	PersonalEventStatusDone      PersonalEventStatus = "done"
	PersonalEventStatusCancelled PersonalEventStatus = "cancelled"
	PersonalEventStatusNoShow    PersonalEventStatus = "no_show"
)

func (e *PersonalEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PersonalEventStatus(s)
	case string:
		*e = PersonalEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PersonalEventStatus: %T", src)
	}
	return nil
}

type NullPersonalEventStatus struct {
	PersonalEventStatus PersonalEventStatus
	Valid               bool // Valid is true if PersonalEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPersonalEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PersonalEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PersonalEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPersonalEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PersonalEventStatus), nil
}

type TrackKind string

const (
	TrackKindDev            TrackKind = "dev"
	TrackKindDevSenior      TrackKind = "dev_senior"
	TrackKindSysanalyst     TrackKind = "sysanalyst"
	TrackKindProductAnalyst TrackKind = "product_analyst"
	TrackKindQa             TrackKind = "qa"
	TrackKindEnglish        TrackKind = "english"
)

func (e *TrackKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrackKind(s)
	case string:
		*e = TrackKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TrackKind: %T", src)
	}
	return nil
}

type NullTrackKind struct {
	TrackKind TrackKind
	Valid     bool // Valid is true if TrackKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrackKind) Scan(value interface{}) error {
	if value == nil {
		ns.TrackKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrackKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrackKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrackKind), nil
}

type TrackStepKind string

const (
	TrackStepKindKata       TrackStepKind = "kata"
	TrackStepKindArena      TrackStepKind = "arena"
	TrackStepKindMock       TrackStepKind = "mock"
	TrackStepKindCodexRead  TrackStepKind = "codex_read"
	TrackStepKindFocusBlock TrackStepKind = "focus_block"
)

func (e *TrackStepKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrackStepKind(s)
	case string:
		*e = TrackStepKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TrackStepKind: %T", src)
	}
	return nil
}

type NullTrackStepKind struct {
	TrackStepKind TrackStepKind
	Valid         bool // Valid is true if TrackStepKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrackStepKind) Scan(value interface{}) error {
	if value == nil {
		ns.TrackStepKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrackStepKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrackStepKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrackStepKind), nil
}

type UserGoalKind string

const (
	UserGoalKindJobTarget   UserGoalKind = "job_target"
	UserGoalKindSkillTarget UserGoalKind = "skill_target"
	UserGoalKindTrackTarget UserGoalKind = "track_target"
)

func (e *UserGoalKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserGoalKind(s)
	case string:
		*e = UserGoalKind(s)
	default:
		return fmt.Errorf("unsupported scan type for UserGoalKind: %T", src)
	}
	return nil
}

type NullUserGoalKind struct {
	UserGoalKind UserGoalKind
	Valid        bool // Valid is true if UserGoalKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserGoalKind) Scan(value interface{}) error {
	if value == nil {
		ns.UserGoalKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserGoalKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserGoalKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserGoalKind), nil
}

type UserGoalStatus string

const (
	UserGoalStatusActive    UserGoalStatus = "active"
	UserGoalStatusPaused    UserGoalStatus = "paused"
	UserGoalStatusDone      UserGoalStatus = "done"
	UserGoalStatusAbandoned UserGoalStatus = "abandoned"
)

func (e *UserGoalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserGoalStatus(s)
	case string:
		*e = UserGoalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserGoalStatus: %T", src)
	}
	return nil
}

type NullUserGoalStatus struct {
	UserGoalStatus UserGoalStatus
	Valid          bool // Valid is true if UserGoalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserGoalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserGoalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserGoalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserGoalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserGoalStatus), nil
}

type AiCredit struct {
	UserID    pgtype.UUID
	Balance   int32
	UpdatedAt pgtype.Timestamptz
}

type AiStrictnessProfile struct {
	ID                   pgtype.UUID
	Slug                 string
	Name                 string
	OffTopicPenalty      float64
	MustMentionPenalty   float64
	HallucinationPenalty float64
	BiasTowardFail       float64
	CustomPromptTemplate pgtype.Text
	Active               bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type AnticheatSignal struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	MatchID   pgtype.UUID
	Type      string
	Severity  string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type ArenaMatch struct {
	ID            pgtype.UUID
	TaskID        pgtype.UUID
	TaskVersion   int32
	Section       string
	Mode          string
	Status        string
	WinnerID      pgtype.UUID
	WinningTeamID pgtype.Int2
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type ArenaParticipant struct {
	MatchID        pgtype.UUID
	UserID         pgtype.UUID
	Team           int32
	EloBefore      int32
	EloAfter       pgtype.Int4
	SuspicionScore pgtype.Numeric
	SubmittedAt    pgtype.Timestamptz
}

type AtlasEdge struct {
	ID     int64
	FromID string
	ToID   string
	Kind   string
}

type AtlasNode struct {
	ID          string
	Title       string
	Section     string
	Kind        string
	Cluster     string
	Description string
	TotalCount  int32
	PosX        pgtype.Int4
	PosY        pgtype.Int4
	SortOrder   int32
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	TrackKind   TrackKind
}

type Booking struct {
	ID          pgtype.UUID
	SlotID      pgtype.UUID
	CandidateID pgtype.UUID
	MeetUrl     pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
}

type Circle struct {
	ID          pgtype.UUID
	Name        string
	Slug        pgtype.Text
	Description string
	OwnerID     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CircleMember struct {
	CircleID pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	JoinedAt pgtype.Timestamptz
}

type Club struct {
	ID              pgtype.UUID
	CircleID        pgtype.UUID
	Slug            string
	Name            string
	TopicTag        string
	CuratorUserID   pgtype.UUID
	CurriculumMd    string
	ScheduleKind    string
	DefaultZoomLink string
	TgAnchorUrl     string
	CoverImageUrl   string
	IsPublic        bool
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ClubAttendee struct {
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	Status    ClubAttendeeStatus
	NotesMd   string
	RsvpAt    pgtype.Timestamptz
}

type ClubMaterial struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	Kind      string
	Label     string
	Url       string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
}

type ClubSession struct {
	ID                 pgtype.UUID
	ClubID             pgtype.UUID
	ScheduledAt        pgtype.Timestamptz
	DurationMin        int32
	TopicTitle         string
	TopicMd            string
	PresenterHandle    string
	ZoomLink           string
	TgPostUrl          string
	RecordingUrl       string
	PreReadMd          string
	SummaryMd          string
	TakeawaysMd        string
	Status             ClubSessionStatus
	AttachedCodexSlugs []string
	AttachedEventIds   []pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type CoachEpisode struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Kind             string
	Summary          string
	Payload          []byte
	Embedding        []float32
	EmbeddingVec     pgvector.Vector
	EmbeddingModelID pgtype.Int4
	EmbeddedAt       pgtype.Timestamptz
	OccurredAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type CodexArticle struct {
	ID           pgtype.UUID
	Slug         string
	Title        string
	Description  string
	Category     string
	Href         string
	Source       string
	ReadMin      int32
	SortOrder    int32
	Active       bool
	QuizQuestion pgtype.Text
	QuizAnswer   pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type CodexCategory struct {
	Slug        string
	Label       string
	Description string
	SortOrder   int32
	Active      bool
	CreatedAt   pgtype.Timestamptz
}

type Company struct {
	ID               pgtype.UUID
	Slug             string
	Name             string
	Difficulty       string
	MinLevelRequired int32
	Sections         []string
	LogoUrl          pgtype.Text
	Description      string
	Active           bool
	SortOrder        int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type CompanyQuestion struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	StageKind         string
	Body              string
	ExpectedAnswerMd  string
	ReferenceCriteria []byte
	Active            bool
	SortOrder         int32
	CreatedAt         pgtype.Timestamptz
}

type CompanyStage struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Name      string
	SortOrder int32
}

type CopilotConversation struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	SessionID      pgtype.UUID
	Title          string
	Model          string
	RunningSummary string
	SummaryModel   string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CopilotMessage struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Content        string
	HasScreenshot  bool
	TokensIn       int32
	TokensOut      int32
	LatencyMs      int32
	Rating         pgtype.Int2
	CreatedAt      pgtype.Timestamptz
}

type CopilotQuota struct {
	UserID        pgtype.UUID
	Plan          string
	RequestsUsed  int32
	RequestsCap   int32
	ResetsAt      pgtype.Timestamptz
	ModelsAllowed []string
	UpdatedAt     pgtype.Timestamptz
}

type CopilotSession struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Kind        string
	DocumentIds []pgtype.UUID
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	ByokOnly    bool
}

type CopilotSessionReport struct {
	SessionID       pgtype.UUID
	Status          string
	OverallScore    int32
	SectionScores   []byte
	Weaknesses      []byte
	Recommendations []byte
	Links           []byte
	ReportMarkdown  string
	ReportUrl       string
	ErrorMessage    string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Analysis        []byte
	Title           string
}

type DailyKataHistory struct {
	UserID       pgtype.UUID
	KataDate     pgtype.Date
	TaskID       pgtype.UUID
	IsCursed     bool
	IsWeeklyBoss bool
	Passed       pgtype.Bool
	FreezeUsed   bool
	SubmittedAt  pgtype.Timestamptz
}

type DailyStreak struct {
	UserID        pgtype.UUID
	CurrentStreak int32
	LongestStreak int32
	FreezeTokens  int32
	LastKataDate  pgtype.Date
	UpdatedAt     pgtype.Timestamptz
}

type Device struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	Platform   string
	LastSeenAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type DocChunk struct {
	ID           pgtype.UUID
	DocID        pgtype.UUID
	Ord          int32
	Content      string
	Embedding    []float32
	EmbeddingVec pgvector.Vector
	TokenCount   int32
	CreatedAt    pgtype.Timestamptz
}

type Document struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Filename     string
	Mime         string
	SizeBytes    int64
	Sha256       string
	SourceUrl    string
	Status       string
	ErrorMessage string
	ChunkCount   int32
	TokenCount   int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type DynamicConfig struct {
	Key         string
	Value       []byte
	Type        string
	Description pgtype.Text
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   pgtype.UUID
}

type EditorParticipant struct {
	RoomID   pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	JoinedAt pgtype.Timestamptz
}

type EditorRoom struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	Type       string
	TaskID     pgtype.UUID
	Language   string
	IsFrozen   bool
	ExpiresAt  pgtype.Timestamptz
	Visibility string
	CreatedAt  pgtype.Timestamptz
}

type EloSnapshotsDaily struct {
	UserID        pgtype.UUID
	Section       string
	SnapshotDate  pgtype.Date
	Elo           int32
	MatchesPlayed int32
}

type EmbeddingModel struct {
	ID   int32
	Name string
	Dim  int32
}

type Event struct {
	ID               pgtype.UUID
	CircleID         pgtype.UUID
	Title            string
	Description      string
	StartsAt         pgtype.Timestamptz
	DurationMin      int32
	EditorRoomID     pgtype.UUID
	WhiteboardRoomID pgtype.UUID
	RecurrenceRule   pgtype.Text
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

type EventNotificationSent struct {
	EventID pgtype.UUID
	UserID  pgtype.UUID
	Kind    string
	SentAt  pgtype.Timestamptz
}

type EventParticipant struct {
	EventID  pgtype.UUID
	UserID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

type FollowUpQuestion struct {
	ID         pgtype.UUID
	TaskID     pgtype.UUID
	QuestionRu string
	QuestionEn string
	AnswerHint pgtype.Text
	OrderNum   int32
}

type HoneDailyBrief struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	BriefDate   pgtype.Date
	Payload     []byte
	GeneratedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type HoneDailyPlan struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	PlanDate      pgtype.Date
	Items         []byte
	RegeneratedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type HoneFocusSession struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	PlanID             pgtype.UUID
	PlanItemID         string
	PinnedTitle        string
	Mode               string
	StartedAt          pgtype.Timestamptz
	EndedAt            pgtype.Timestamptz
	PomodorosCompleted int32
	SecondsFocused     int32
	CreatedAt          pgtype.Timestamptz
}

type HoneListeningMaterial struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Title        string
	AudioUrl     string
	TranscriptMd string
	ArchivedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type HoneNote struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Title            string
	BodyMd           string
	SizeBytes        int32
	FolderID         pgtype.UUID
	Kind             string
	RawAnalysisJson  []byte
	Encrypted        bool
	PublicSlug       pgtype.Text
	PublishedAt      pgtype.Timestamptz
	Embedding        []float32
	EmbeddingVec     pgvector.Vector
	EmbeddingModelID pgtype.Int4
	EmbeddedAt       pgtype.Timestamptz
	FilePath         pgtype.Text
	StartedAt        pgtype.Timestamptz
	ImportedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type HoneNoteFolder struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	ParentID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type HonePlanSkip struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	SkillKey  string
	SkippedAt pgtype.Timestamptz
}

type HoneQueueItem struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Source    string
	Status    string
	ItemDate  pgtype.Date
	SkillKey  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type HoneReadingMaterial struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	SourceKind string
	SourceUrl  string
	Title      string
	BodyMd     string
	TotalChars int32
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type HoneReadingSession struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	MaterialID     pgtype.UUID
	CharsRead      int32
	CharsTotal     int32
	StartedAt      pgtype.Timestamptz
	EndedAt        pgtype.Timestamptz
	AiSummaryScore pgtype.Int4
	SummaryMd      string
}

type HoneStreakDay struct {
	UserID          pgtype.UUID
	Day             pgtype.Date
	FocusedSeconds  int32
	SessionsCount   int32
	QualifiesStreak bool
}

type HoneStreakState struct {
	UserID        pgtype.UUID
	CurrentStreak int32
	LongestStreak int32
	LastQualified pgtype.Date
	UpdatedAt     pgtype.Timestamptz
}

type HoneTask struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Status             string
	Kind               string
	Source             string
	Title              string
	BriefMd            string
	SkillKey           pgtype.Text
	DeepLink           string
	RecommendedReading []string
	Priority           int16
	DueAt              pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	DismissedAt        pgtype.Timestamptz
}

type HoneTaskComment struct {
	ID         pgtype.UUID
	TaskID     pgtype.UUID
	AuthorKind string
	BodyMd     string
	CreatedAt  pgtype.Timestamptz
}

type HoneVocabQueue struct {
	UserID         pgtype.UUID
	Word           string
	Translation    string
	ContextMd      string
	SourceMaterial pgtype.UUID
	Box            int16
	NextReviewAt   pgtype.Timestamptz
	ReviewedCount  int32
	LearnedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type HoneWhiteboard struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	StateJson []byte
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Incident struct {
	ID               pgtype.UUID
	StartedAt        pgtype.Timestamptz
	EndedAt          pgtype.Timestamptz
	Severity         string
	Title            string
	Description      string
	AffectedServices []string
	CreatedAt        pgtype.Timestamptz
}

type IntelligenceInsight struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Surface     string
	Severity    InsightSeverity
	Anchor      string
	Headline    string
	Evidence    string
	Interpret   string
	Lever       string
	DeepLink    string
	EventID     pgtype.UUID
	SkillKey    string
	CodexSlug   string
	TrackID     pgtype.UUID
	DismissedAt pgtype.Timestamptz
	ActedAt     pgtype.Timestamptz
	GeneratedAt pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type InterviewerApplication struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Motivation   string
	Status       string
	ReviewedBy   pgtype.UUID
	ReviewedAt   pgtype.Timestamptz
	DecisionNote string
	CreatedAt    pgtype.Timestamptz
}

type LlmConfig struct {
	ID          pgtype.UUID
	ScopeType   string
	ScopeID     pgtype.Text
	Model       string
	Temperature pgtype.Numeric
	MaxTokens   int32
	CreatedAt   pgtype.Timestamptz
}

type LlmModel struct {
	ID                 int64
	ModelID            string
	Label              string
	Provider           string
	ProviderID         string
	IsVirtual          bool
	Tier               string
	IsEnabled          bool
	ContextWindow      pgtype.Int4
	CostPer1kInputUsd  pgtype.Numeric
	CostPer1kOutputUsd pgtype.Numeric
	UseForArena        bool
	UseForInsight      bool
	UseForMock         bool
	UseForVacancies    bool
	SortOrder          int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type LlmRuntimeConfig struct {
	ID            int32
	ChainOrder    []string
	TaskMap       []byte
	VirtualChains []byte
	Version       int32
	UpdatedAt     pgtype.Timestamptz
}

type Lobby struct {
	ID           pgtype.UUID
	Code         string
	OwnerID      pgtype.UUID
	Mode         string
	Section      string
	Difficulty   string
	Visibility   string
	MaxMembers   int16
	AiAllowed    bool
	TimeLimitMin int16
	Status       string
	MatchID      pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SkillFilter  []string
}

type LobbyMember struct {
	LobbyID  pgtype.UUID
	UserID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
	Role     string
	Team     int16
}

type MentorSession struct {
	ID          pgtype.UUID
	MenteeID    pgtype.UUID
	MentorID    pgtype.UUID
	SlotAt      pgtype.Timestamptz
	DurationMin int32
	Status      string
	EscrowState string
	PriceCents  int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type MockMessage struct {
	ID             pgtype.UUID
	SessionID      pgtype.UUID
	Role           string
	Content        string
	CodeSnapshot   pgtype.Text
	StressSnapshot []byte
	TokensUsed     pgtype.Int4
	CreatedAt      pgtype.Timestamptz
}

type MockPipeline struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	CompanyID       pgtype.UUID
	RoleLabel       string
	Section         string
	AiAssist        bool
	CurrentStageIdx int16
	Verdict         MockPipelineVerdict
	TotalScore      pgtype.Float4
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type MockSession struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	CompanyID      pgtype.UUID
	TaskID         pgtype.UUID
	Section        string
	Difficulty     string
	Status         string
	DurationMin    int32
	VoiceMode      bool
	PairedUserID   pgtype.UUID
	LlmModel       pgtype.Text
	StressProfile  []byte
	AiReport       []byte
	AiAssist       bool
	RunningSummary string
	SummaryModel   string
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type MockTask struct {
	ID                       pgtype.UUID
	StageKind                string
	Language                 string
	Difficulty               int16
	Title                    string
	BodyMd                   string
	SampleIoMd               string
	ReferenceCriteria        []byte
	ReferenceSolutionMd      string
	FunctionalRequirementsMd string
	TimeLimitMin             int32
	AiStrictnessProfileID    pgtype.UUID
	LlmModel                 pgtype.Text
	Active                   bool
	CreatedByAdminID         pgtype.UUID
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type MockTaskTestCase struct {
	ID             pgtype.UUID
	TaskID         pgtype.UUID
	Input          string
	ExpectedOutput string
	IsHidden       bool
	Ordinal        int32
	CreatedAt      pgtype.Timestamptz
}

type NoteYjsUpdate struct {
	Seq        int64
	NoteID     pgtype.UUID
	UserID     pgtype.UUID
	UpdateData []byte
	CreatedAt  pgtype.Timestamptz
}

type NotificationPref struct {
	UserID                    pgtype.UUID
	TelegramChatID            pgtype.Text
	ChannelEnabled            []byte
	WeeklyReportEnabled       bool
	SkillDecayWarningsEnabled bool
	SilenceUntil              pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type OauthAccount struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Provider        string
	ProviderUserID  string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	TokenExpiresAt  pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type OnboardingProgress struct {
	UserID      pgtype.UUID
	Step        int32
	Answers     []byte
	CompletedAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Persona struct {
	ID            string
	Label         string
	Hint          string
	IconEmoji     string
	BrandGradient string
	SuggestedTask string
	SystemPrompt  string
	SortOrder     int32
	IsEnabled     bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type PersonalEvent struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Kind             PersonalEventKind
	Title            string
	DescriptionMd    string
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	AllDay           bool
	CompanyID        pgtype.UUID
	Role             string
	CurrentLevel     string
	ReadinessPct     int16
	CodexArticleSlug string
	TrackID          pgtype.UUID
	ClubSessionID    pgtype.UUID
	Status           PersonalEventStatus
	OutcomeMd        string
	FeltScore        pgtype.Int2
	FinishedAt       pgtype.Timestamptz
	Source           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type PersonalEventRemindersSent struct {
	EventID pgtype.UUID
	Horizon PersonalEventReminderHorizon
	Channel string
	SentAt  pgtype.Timestamptz
}

type PipelineAttempt struct {
	ID         pgtype.UUID
	StageID    pgtype.UUID
	UserAnswer pgtype.Text
	AiFeedback []byte
	Score      pgtype.Int4
	CreatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type PipelineStage struct {
	ID         pgtype.UUID
	PipelineID pgtype.UUID
	Kind       string
	SortOrder  int32
	Status     string
	CreatedAt  pgtype.Timestamptz
}

type Podcast struct {
	ID          pgtype.UUID
	TitleRu     string
	TitleEn     string
	Description pgtype.Text
	Section     string
	DurationSec int32
	AudioKey    string
	IsPublished bool
	Host        pgtype.Text
	CategoryID  pgtype.UUID
	EpisodeNum  pgtype.Int4
	CoverUrl    pgtype.Text
	PublishedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PodcastCategory struct {
	ID        pgtype.UUID
	Slug      string
	Name      string
	Color     string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
}

type PodcastProgress struct {
	UserID      pgtype.UUID
	PodcastID   pgtype.UUID
	ListenedSec int32
	CompletedAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Profile struct {
	UserID           pgtype.UUID
	CharClass        string
	Title            pgtype.Text
	AvatarFrame      pgtype.Text
	CareerStage      string
	Intellect        int32
	Strength         int32
	Dexterity        int32
	Will             int32
	IsMentor         bool
	MentorHourlyRate int32
	MentorBio        string
	MentorLanguages  []string
	MentorVerified   bool
	UpdatedAt        pgtype.Timestamptz
}

type ProviderLink struct {
	UserID       pgtype.UUID
	Provider     string
	ExternalID   string
	ExternalTier pgtype.Text
	VerifiedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Rating struct {
	UserID       pgtype.UUID
	Section      string
	Elo          int32
	MatchesCount int32
	LastMatchAt  pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Review struct {
	BookingID     pgtype.UUID
	Direction     string
	ReviewerID    pgtype.UUID
	InterviewerID pgtype.UUID
	SubjectID     pgtype.UUID
	Rating        int32
	Feedback      pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type SavedVacancy struct {
	ID           int64
	UserID       pgtype.UUID
	Source       string
	ExternalID   string
	SnapshotJson []byte
	Status       string
	Notes        pgtype.Text
	SavedAt      pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type SessionDocument struct {
	SessionID  pgtype.UUID
	DocumentID pgtype.UUID
}

type SkillNode struct {
	UserID     pgtype.UUID
	NodeKey    string
	Progress   int32
	UnlockedAt pgtype.Timestamptz
	DecayedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Slot struct {
	ID            pgtype.UUID
	InterviewerID pgtype.UUID
	StartsAt      pgtype.Timestamptz
	DurationMin   int32
	Section       string
	Difficulty    pgtype.Text
	Language      string
	PriceRub      int32
	Status        string
	CreatedAt     pgtype.Timestamptz
	MeetUrl       pgtype.Text
}

type StageDefaultQuestion struct {
	ID                pgtype.UUID
	StageKind         string
	Body              string
	ExpectedAnswerMd  string
	ReferenceCriteria []byte
	Active            bool
	SortOrder         int32
	CreatedAt         pgtype.Timestamptz
}

type Subscription struct {
	UserID           pgtype.UUID
	Plan             string
	Status           string
	Provider         pgtype.Text
	ProviderSubID    pgtype.Text
	CurrentPeriodEnd pgtype.Timestamptz
	GraceUntil       pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type SupportTicket struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	ContactKind  string
	ContactValue string
	Subject      string
	Message      string
	Status       string
	InternalNote string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ResolvedAt   pgtype.Timestamptz
}

type SyncTombstone struct {
	ID             int64
	UserID         pgtype.UUID
	TableName      string
	RowID          pgtype.UUID
	DeletedAt      pgtype.Timestamptz
	OriginDeviceID pgtype.UUID
}

type Task struct {
	ID            pgtype.UUID
	Slug          string
	TitleRu       string
	TitleEn       string
	DescriptionRu string
	DescriptionEn string
	Difficulty    string
	Section       string
	TimeLimitSec  int32
	MemoryLimitMb int32
	SolutionHint  pgtype.Text
	Version       int32
	IsActive      bool
	AvgRating     pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	SkillKeys     []string
}

type TaskQuestion struct {
	ID                pgtype.UUID
	TaskID            pgtype.UUID
	Body              string
	ExpectedAnswerMd  string
	ReferenceCriteria []byte
	SortOrder         int32
	CreatedAt         pgtype.Timestamptz
}

type TaskRating struct {
	TaskID    pgtype.UUID
	UserID    pgtype.UUID
	Stars     int32
	CreatedAt pgtype.Timestamptz
}

type TaskTemplate struct {
	TaskID      pgtype.UUID
	Language    string
	StarterCode string
}

type TestCase struct {
	ID             pgtype.UUID
	TaskID         pgtype.UUID
	Input          string
	ExpectedOutput string
	IsHidden       bool
	OrderNum       int32
}

type TgLinkToken struct {
	Token     string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type TgUserLink struct {
	UserID      pgtype.UUID
	ChatID      int64
	TgUsername  pgtype.Text
	LinkedAt    pgtype.Timestamptz
	Locale      string
	PushLocalHh int32
	PushTz      string
	PausedUntil pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}

type Track struct {
	ID             pgtype.UUID
	Slug           string
	Name           string
	Tagline        string
	DescriptionMd  string
	CoverImageUrl  string
	AccentColor    string
	CuratorID      pgtype.UUID
	EstimatedWeeks int16
	Difficulty     string
	IsCurated      bool
	IsActive       bool
	Tags           []string
	CompanyFocus   []string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type TrackStep struct {
	TrackID            pgtype.UUID
	StepIndex          int16
	Title              string
	DescriptionMd      string
	SkillKeys          []string
	RequiredKind       TrackStepKind
	RequiredCount      int32
	RecommendedReading []string
	EstimatedMinutes   int32
}

type TutorAssignment struct {
	ID          pgtype.UUID
	TutorID     pgtype.UUID
	StudentID   pgtype.UUID
	Title       string
	BodyMd      string
	DueAt       pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
}

type TutorInvite struct {
	ID         pgtype.UUID
	TutorID    pgtype.UUID
	Code       string
	Note       string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	AcceptedBy pgtype.UUID
	AcceptedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type TutorStudent struct {
	ID        pgtype.UUID
	TutorID   pgtype.UUID
	StudentID pgtype.UUID
	InviteID  pgtype.UUID
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	Note      string
}

type User struct {
	ID                    pgtype.UUID
	Username              string
	Role                  string
	Locale                string
	DisplayName           pgtype.Text
	AvatarUrl             string
	AiInsightModel        pgtype.Text
	AiVacanciesModel      pgtype.Text
	OnboardingCompletedAt pgtype.Timestamptz
	FocusClass            string
	StorageQuotaBytes     int64
	StorageUsedBytes      int64
	StorageTier           string
	StorageRecomputedAt   pgtype.Timestamptz
	VaultKdfSalt          []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type UserBan struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Reason    string
	IssuedBy  pgtype.UUID
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	LiftedAt  pgtype.Timestamptz
	LiftedBy  pgtype.UUID
}

type UserGoal struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Kind        UserGoalKind
	Status      UserGoalStatus
	Title       string
	NotesMd     string
	Deadline    pgtype.Date
	TrackID     pgtype.UUID
	SkillKeys   []string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

type UserNotification struct {
	ID        int64
	UserID    pgtype.UUID
	Channel   string
	Type      string
	Title     string
	Body      pgtype.Text
	Payload   []byte
	Priority  int32
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type UserPersonaTrack struct {
	UserID       pgtype.UUID
	Track        TrackKind
	Seniority    pgtype.Text
	PrimaryTrack bool
	StartedAt    pgtype.Timestamptz
	LastActiveAt pgtype.Timestamptz
}

type UserReport struct {
	ID          pgtype.UUID
	ReporterID  pgtype.UUID
	ReportedID  pgtype.UUID
	Reason      string
	Description string
	Status      string
	ResolvedAt  pgtype.Timestamptz
	ResolvedBy  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type UserTrack struct {
	UserID      pgtype.UUID
	TrackID     pgtype.UUID
	JoinedAt    pgtype.Timestamptz
	CurrentStep int16
	Progress    []byte
	PausedAt    pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

type UserXp struct {
	UserID    pgtype.UUID
	TotalXp   int64
	Level     int32
	LastXpAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WeeklyShareToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	WeekIso    string
	Token      string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ViewsCount int32
}

type WhiteboardRoom struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	Title      string
	Snapshot   []byte
	ExpiresAt  pgtype.Timestamptz
	Visibility string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type WhiteboardRoomParticipant struct {
	RoomID   pgtype.UUID
	UserID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

type WhiteboardYjsUpdate struct {
	Seq          int64
	WhiteboardID pgtype.UUID
	UserID       pgtype.UUID
	UpdateData   []byte
	CreatedAt    pgtype.Timestamptz
}

type XpEvent struct {
	ID        int64
	UserID    pgtype.UUID
	Amount    int32
	Source    string
	SourceID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
