// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscription.sql

package subscriptiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscription = `-- name: GetSubscription :one

SELECT user_id, plan, status, provider, provider_sub_id,
       current_period_end, grace_until, updated_at
  FROM subscriptions
 WHERE user_id = $1
`

// subscription queries, consumed by sqlc → services/subscription/infra/db/.
// v2: started_at + boosty_level dropped from subscriptions.
func (q *Queries) GetSubscription(ctx context.Context, userID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.Provider,
		&i.ProviderSubID,
		&i.CurrentPeriodEnd,
		&i.GraceUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptionsByPlan = `-- name: ListSubscriptionsByPlan :many
SELECT user_id, plan, status, provider, provider_sub_id,
       current_period_end, grace_until, updated_at
  FROM subscriptions
 WHERE plan = $1 AND status = 'active'
 ORDER BY updated_at DESC
 LIMIT $2 OFFSET $3
`

type ListSubscriptionsByPlanParams struct {
	Plan   string
	Limit  int32
	Offset int32
}

// Hot path for admin dashboard. The partial index
// idx_subscriptions_plan_active keeps this <10ms over hundreds of thousands.
func (q *Queries) ListSubscriptionsByPlan(ctx context.Context, arg ListSubscriptionsByPlanParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByPlan, arg.Plan, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.UserID,
			&i.Plan,
			&i.Status,
			&i.Provider,
			&i.ProviderSubID,
			&i.CurrentPeriodEnd,
			&i.GraceUntil,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpiredSubscriptions = `-- name: MarkExpiredSubscriptions :execrows
UPDATE subscriptions
   SET status     = 'expired',
       updated_at = now()
 WHERE status = 'active'
   AND grace_until IS NOT NULL
   AND grace_until < $1
`

// Batch-update lapsed subscriptions (grace_until < $1). Hourly cron.
func (q *Queries) MarkExpiredSubscriptions(ctx context.Context, graceUntil pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, markExpiredSubscriptions, graceUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions(
    user_id, plan, status, provider, provider_sub_id,
    current_period_end, grace_until, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE
   SET plan               = EXCLUDED.plan,
       status             = EXCLUDED.status,
       provider           = EXCLUDED.provider,
       provider_sub_id    = EXCLUDED.provider_sub_id,
       current_period_end = EXCLUDED.current_period_end,
       grace_until        = EXCLUDED.grace_until,
       updated_at         = EXCLUDED.updated_at
`

type UpsertSubscriptionParams struct {
	UserID           pgtype.UUID
	Plan             string
	Status           string
	Provider         pgtype.Text
	ProviderSubID    pgtype.Text
	CurrentPeriodEnd pgtype.Timestamptz
	GraceUntil       pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Idempotent write. Used by Admin SetTier and the Boosty/yookassa sync.
// Set every column explicitly so NULLs don't accidentally overwrite (e.g.
// provider_sub_id during manual admin grants).
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.UserID,
		arg.Plan,
		arg.Status,
		arg.Provider,
		arg.ProviderSubID,
		arg.CurrentPeriodEnd,
		arg.GraceUntil,
		arg.UpdatedAt,
	)
	return err
}
