// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ratingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Use a CTE that ranks every row within a section, then filter to the user.
	FindRank(ctx context.Context, arg FindRankParams) (int32, error)
	// rating queries consumed by sqlc (emitted into services/rating/infra/db).
	GetRatingsByUser(ctx context.Context, userID pgtype.UUID) ([]Rating, error)
	TopLeaderboard(ctx context.Context, arg TopLeaderboardParams) ([]TopLeaderboardRow, error)
	UpsertRating(ctx context.Context, arg UpsertRatingParams) error
}

var _ Querier = (*Queries)(nil)
