// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package admindb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTasksBase = `-- name: CountTasksBase :one
SELECT COUNT(*)::bigint AS total FROM tasks
`

func (q *Queries) CountTasksBase(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksBase)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    slug, title_ru, title_en, description_ru, description_en,
    difficulty, section, time_limit_sec, memory_limit_mb,
    solution_hint, is_active
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, slug, title_ru, title_en, description_ru, description_en,
          difficulty, section, time_limit_sec, memory_limit_mb,
          solution_hint, version, is_active, created_at, updated_at
`

type CreateTaskParams struct {
	Slug          string
	TitleRu       string
	TitleEn       string
	DescriptionRu string
	DescriptionEn string
	Difficulty    string
	Section       string
	TimeLimitSec  int32
	MemoryLimitMb int32
	SolutionHint  pgtype.Text
	IsActive      bool
}

type CreateTaskRow struct {
	ID            pgtype.UUID
	Slug          string
	TitleRu       string
	TitleEn       string
	DescriptionRu string
	DescriptionEn string
	Difficulty    string
	Section       string
	TimeLimitSec  int32
	MemoryLimitMb int32
	SolutionHint  pgtype.Text
	Version       int32
	IsActive      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Slug,
		arg.TitleRu,
		arg.TitleEn,
		arg.DescriptionRu,
		arg.DescriptionEn,
		arg.Difficulty,
		arg.Section,
		arg.TimeLimitSec,
		arg.MemoryLimitMb,
		arg.SolutionHint,
		arg.IsActive,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleRu,
		&i.TitleEn,
		&i.DescriptionRu,
		&i.DescriptionEn,
		&i.Difficulty,
		&i.Section,
		&i.TimeLimitSec,
		&i.MemoryLimitMb,
		&i.SolutionHint,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFollowUpQuestions = `-- name: DeleteFollowUpQuestions :exec
DELETE FROM follow_up_questions WHERE task_id = $1
`

func (q *Queries) DeleteFollowUpQuestions(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFollowUpQuestions, taskID)
	return err
}

const deleteTaskTemplates = `-- name: DeleteTaskTemplates :exec
DELETE FROM task_templates WHERE task_id = $1
`

func (q *Queries) DeleteTaskTemplates(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskTemplates, taskID)
	return err
}

const deleteTestCases = `-- name: DeleteTestCases :exec
DELETE FROM test_cases WHERE task_id = $1
`

func (q *Queries) DeleteTestCases(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTestCases, taskID)
	return err
}

const getDynamicConfig = `-- name: GetDynamicConfig :one
SELECT key, value, type, description, updated_at, updated_by
  FROM dynamic_config
 WHERE key = $1
`

func (q *Queries) GetDynamicConfig(ctx context.Context, key string) (DynamicConfig, error) {
	row := q.db.QueryRow(ctx, getDynamicConfig, key)
	var i DynamicConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Type,
		&i.Description,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one


SELECT id, slug, title_ru, title_en, description_ru, description_en,
       difficulty, section, time_limit_sec, memory_limit_mb,
       solution_hint, version, is_active, created_at, updated_at
  FROM tasks
 WHERE id = $1
`

type GetTaskByIDRow struct {
	ID            pgtype.UUID
	Slug          string
	TitleRu       string
	TitleEn       string
	DescriptionRu string
	DescriptionEn string
	Difficulty    string
	Section       string
	TimeLimitSec  int32
	MemoryLimitMb int32
	SolutionHint  pgtype.Text
	Version       int32
	IsActive      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Queries consumed by sqlc for the admin domain.
//
// NOTE: the task-listing and anticheat-listing endpoints require optional
// predicates (section, difficulty, is_active / severity, from). sqlc cannot
// elegantly model a WHERE clause that flips predicates in and out, so those
// two are hand-rolled in postgres.go (same pattern as slot/daily). Every
// other query in this file is sqlc-generated.
//
// The admin domain is the ONLY caller that reads tasks.solution_hint off the
// API boundary (bible §3.14). Other domains use TaskPublic projections.
// ─────────────────────────────────────────────────────────────────────────
// Tasks
// ─────────────────────────────────────────────────────────────────────────
func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleRu,
		&i.TitleEn,
		&i.DescriptionRu,
		&i.DescriptionEn,
		&i.Difficulty,
		&i.Section,
		&i.TimeLimitSec,
		&i.MemoryLimitMb,
		&i.SolutionHint,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFollowUpQuestion = `-- name: InsertFollowUpQuestion :one
INSERT INTO follow_up_questions (task_id, question_ru, question_en, answer_hint, order_num)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, question_ru, question_en, answer_hint, order_num
`

type InsertFollowUpQuestionParams struct {
	TaskID     pgtype.UUID
	QuestionRu string
	QuestionEn string
	AnswerHint pgtype.Text
	OrderNum   int32
}

func (q *Queries) InsertFollowUpQuestion(ctx context.Context, arg InsertFollowUpQuestionParams) (FollowUpQuestion, error) {
	row := q.db.QueryRow(ctx, insertFollowUpQuestion,
		arg.TaskID,
		arg.QuestionRu,
		arg.QuestionEn,
		arg.AnswerHint,
		arg.OrderNum,
	)
	var i FollowUpQuestion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.QuestionRu,
		&i.QuestionEn,
		&i.AnswerHint,
		&i.OrderNum,
	)
	return i, err
}

const insertTestCase = `-- name: InsertTestCase :one
INSERT INTO test_cases (task_id, input, expected_output, is_hidden, order_num)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, input, expected_output, is_hidden, order_num
`

type InsertTestCaseParams struct {
	TaskID         pgtype.UUID
	Input          string
	ExpectedOutput string
	IsHidden       bool
	OrderNum       int32
}

func (q *Queries) InsertTestCase(ctx context.Context, arg InsertTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, insertTestCase,
		arg.TaskID,
		arg.Input,
		arg.ExpectedOutput,
		arg.IsHidden,
		arg.OrderNum,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Input,
		&i.ExpectedOutput,
		&i.IsHidden,
		&i.OrderNum,
	)
	return i, err
}

const listAnticheatSignalsBase = `-- name: ListAnticheatSignalsBase :many

SELECT s.id, s.user_id, u.username, s.match_id, s.type, s.severity,
       s.metadata, s.created_at
  FROM anticheat_signals s
  LEFT JOIN users u ON u.id = s.user_id
 ORDER BY s.created_at DESC
 LIMIT $1
`

type ListAnticheatSignalsBaseRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Username  pgtype.Text
	MatchID   pgtype.UUID
	Type      string
	Severity  string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

// ─────────────────────────────────────────────────────────────────────────
// Anticheat — base-case ordering; filtered variants live in postgres.go.
// ─────────────────────────────────────────────────────────────────────────
func (q *Queries) ListAnticheatSignalsBase(ctx context.Context, limit int32) ([]ListAnticheatSignalsBaseRow, error) {
	rows, err := q.db.Query(ctx, listAnticheatSignalsBase, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnticheatSignalsBaseRow{}
	for rows.Next() {
		var i ListAnticheatSignalsBaseRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.MatchID,
			&i.Type,
			&i.Severity,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanies = `-- name: ListCompanies :many

SELECT id, slug, name, logo_url, description, active, sort_order, created_at
  FROM companies
 ORDER BY sort_order ASC, name ASC
`

type ListCompaniesRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	LogoUrl     pgtype.Text
	Description string
	Active      bool
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}

// ─────────────────────────────────────────────────────────────────────────
// Companies
// ─────────────────────────────────────────────────────────────────────────
// companies теперь живут под mock-interview pipeline shape
// (logo_url/description/active/sort_order — см. 00043). Старая
// difficulty/min_level_required/sections больше не существует, в отличие
// от arena-фазы. Sort by sort_order чтобы куратор управлял порядком на
// mock-interview витрине.
func (q *Queries) ListCompanies(ctx context.Context) ([]ListCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesRow{}
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.LogoUrl,
			&i.Description,
			&i.Active,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDynamicConfig = `-- name: ListDynamicConfig :many

SELECT key, value, type, description, updated_at, updated_by
  FROM dynamic_config
 ORDER BY key ASC
`

// ─────────────────────────────────────────────────────────────────────────
// Dynamic config
// ─────────────────────────────────────────────────────────────────────────
func (q *Queries) ListDynamicConfig(ctx context.Context) ([]DynamicConfig, error) {
	rows, err := q.db.Query(ctx, listDynamicConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DynamicConfig{}
	for rows.Next() {
		var i DynamicConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Type,
			&i.Description,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowUpQuestions = `-- name: ListFollowUpQuestions :many
SELECT id, task_id, question_ru, question_en, answer_hint, order_num
  FROM follow_up_questions
 WHERE task_id = $1
 ORDER BY order_num ASC, id ASC
`

func (q *Queries) ListFollowUpQuestions(ctx context.Context, taskID pgtype.UUID) ([]FollowUpQuestion, error) {
	rows, err := q.db.Query(ctx, listFollowUpQuestions, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowUpQuestion{}
	for rows.Next() {
		var i FollowUpQuestion
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.QuestionRu,
			&i.QuestionEn,
			&i.AnswerHint,
			&i.OrderNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTemplates = `-- name: ListTaskTemplates :many
SELECT task_id, language, starter_code
  FROM task_templates
 WHERE task_id = $1
 ORDER BY language ASC
`

func (q *Queries) ListTaskTemplates(ctx context.Context, taskID pgtype.UUID) ([]TaskTemplate, error) {
	rows, err := q.db.Query(ctx, listTaskTemplates, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskTemplate{}
	for rows.Next() {
		var i TaskTemplate
		if err := rows.Scan(&i.TaskID, &i.Language, &i.StarterCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCases = `-- name: ListTestCases :many
SELECT id, task_id, input, expected_output, is_hidden, order_num
  FROM test_cases
 WHERE task_id = $1
 ORDER BY order_num ASC, id ASC
`

func (q *Queries) ListTestCases(ctx context.Context, taskID pgtype.UUID) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCases, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Input,
			&i.ExpectedOutput,
			&i.IsHidden,
			&i.OrderNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
   SET slug            = $2,
       title_ru        = $3,
       title_en        = $4,
       description_ru  = $5,
       description_en  = $6,
       difficulty      = $7,
       section         = $8,
       time_limit_sec  = $9,
       memory_limit_mb = $10,
       solution_hint   = $11,
       is_active       = $12,
       version         = version + 1,
       updated_at      = now()
 WHERE id = $1
RETURNING id, slug, title_ru, title_en, description_ru, description_en,
          difficulty, section, time_limit_sec, memory_limit_mb,
          solution_hint, version, is_active, created_at, updated_at
`

type UpdateTaskParams struct {
	ID            pgtype.UUID
	Slug          string
	TitleRu       string
	TitleEn       string
	DescriptionRu string
	DescriptionEn string
	Difficulty    string
	Section       string
	TimeLimitSec  int32
	MemoryLimitMb int32
	SolutionHint  pgtype.Text
	IsActive      bool
}

type UpdateTaskRow struct {
	ID            pgtype.UUID
	Slug          string
	TitleRu       string
	TitleEn       string
	DescriptionRu string
	DescriptionEn string
	Difficulty    string
	Section       string
	TimeLimitSec  int32
	MemoryLimitMb int32
	SolutionHint  pgtype.Text
	Version       int32
	IsActive      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Version is bumped monotonically on every UPDATE so downstream caches
// (editor task cache / ai-mock prompt cache) can detect a task edit.
func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Slug,
		arg.TitleRu,
		arg.TitleEn,
		arg.DescriptionRu,
		arg.DescriptionEn,
		arg.Difficulty,
		arg.Section,
		arg.TimeLimitSec,
		arg.MemoryLimitMb,
		arg.SolutionHint,
		arg.IsActive,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleRu,
		&i.TitleEn,
		&i.DescriptionRu,
		&i.DescriptionEn,
		&i.Difficulty,
		&i.Section,
		&i.TimeLimitSec,
		&i.MemoryLimitMb,
		&i.SolutionHint,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompany = `-- name: UpsertCompany :one
INSERT INTO companies (slug, name, logo_url, description, active)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (slug) DO UPDATE
    SET name        = EXCLUDED.name,
        logo_url    = EXCLUDED.logo_url,
        description = EXCLUDED.description,
        active      = EXCLUDED.active,
        updated_at  = now()
RETURNING id, slug, name, logo_url, description, active, sort_order, created_at
`

type UpsertCompanyParams struct {
	Slug        string
	Name        string
	LogoUrl     pgtype.Text
	Description string
	Active      bool
}

type UpsertCompanyRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	LogoUrl     pgtype.Text
	Description string
	Active      bool
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}

// Curator edit-by-slug flow. Туннель такой же простой как раньше — name +
// logo_url + description + active. sort_order/created_at управляются БД.
func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (UpsertCompanyRow, error) {
	row := q.db.QueryRow(ctx, upsertCompany,
		arg.Slug,
		arg.Name,
		arg.LogoUrl,
		arg.Description,
		arg.Active,
	)
	var i UpsertCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.LogoUrl,
		&i.Description,
		&i.Active,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDynamicConfig = `-- name: UpsertDynamicConfig :one
INSERT INTO dynamic_config (key, value, type, description, updated_at, updated_by)
VALUES ($1, $2, $3, $4, now(), $5)
ON CONFLICT (key) DO UPDATE
    SET value       = EXCLUDED.value,
        type        = EXCLUDED.type,
        description = COALESCE(EXCLUDED.description, dynamic_config.description),
        updated_at  = now(),
        updated_by  = EXCLUDED.updated_by
RETURNING key, value, type, description, updated_at, updated_by
`

type UpsertDynamicConfigParams struct {
	Key         string
	Value       []byte
	Type        string
	Description pgtype.Text
	UpdatedBy   pgtype.UUID
}

func (q *Queries) UpsertDynamicConfig(ctx context.Context, arg UpsertDynamicConfigParams) (DynamicConfig, error) {
	row := q.db.QueryRow(ctx, upsertDynamicConfig,
		arg.Key,
		arg.Value,
		arg.Type,
		arg.Description,
		arg.UpdatedBy,
	)
	var i DynamicConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Type,
		&i.Description,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertTaskTemplate = `-- name: UpsertTaskTemplate :exec
INSERT INTO task_templates (task_id, language, starter_code)
VALUES ($1, $2, $3)
ON CONFLICT (task_id, language) DO UPDATE SET starter_code = EXCLUDED.starter_code
`

type UpsertTaskTemplateParams struct {
	TaskID      pgtype.UUID
	Language    string
	StarterCode string
}

func (q *Queries) UpsertTaskTemplate(ctx context.Context, arg UpsertTaskTemplateParams) error {
	_, err := q.db.Exec(ctx, upsertTaskTemplate, arg.TaskID, arg.Language, arg.StarterCode)
	return err
}
