-- +goose Up
-- +goose StatementBegin
--
-- 00039 — drop the 12 fake seed podcasts from migration 00009.
--
-- User report (production /podcasts): "Удали плиз хардкор/нереальные
-- подкасты. Если подкастов нет, то поставь заглушку."
--
-- Migration 00009 seeded 12 fake podcasts (consistent-hashing.mp3,
-- cap-theorem.mp3, rate-limiter.mp3, etc.) into the `podcasts` table to
-- exercise the catalogue UI. The audio files were never uploaded to
-- MinIO — clicking play would 404. They were demo content, not real
-- product. Anti-fallback policy: ship empty rather than fake.
--
-- Frontend already handles podcasts.length === 0 with a friendly
-- EmptyState (PodcastsPage.tsx line 543) — Headphones icon +
-- t('podcasts.empty') copy. So removing the rows surfaces the right UX
-- automatically; no frontend change needed.
--
-- We DELETE rather than UPDATE is_published=false because:
--   1. The audio_key paths are bogus (audio doesn't exist) — keeping
--      them flagged-off pollutes admin search and clutters analytics.
--   2. Listening progress rows for these IDs (if any QA users hit them)
--      cascade-delete via FK ON DELETE CASCADE on listening_progress.
--   3. When real podcasts are produced, they get fresh UUIDs — no risk
--      of accidentally resurrecting a fake one.
--
-- Idempotent: targets only the audio_key prefix the seed used. Real
-- podcasts uploaded later won't match (they'll live under their own
-- prefix per the upload pipeline).

DELETE FROM podcasts WHERE audio_key LIKE 'podcasts/%';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Down is a deliberate noop — these were demo data, not user content;
-- restoring them would re-introduce the bug. If the seed is ever needed
-- for local dev again, copy the INSERT block from 00009.
SELECT 1;
-- +goose StatementEnd
