// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package slotdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelBookingBySlotID(ctx context.Context, slotID pgtype.UUID) (int64, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	// slot queries consumed by sqlc (emitted into services/slot/infra/db).
	CreateSlot(ctx context.Context, arg CreateSlotParams) (Slot, error)
	GetBookingBySlotID(ctx context.Context, slotID pgtype.UUID) (Booking, error)
	GetSlot(ctx context.Context, id pgtype.UUID) (Slot, error)
	// SELECT ... FOR UPDATE inside a transaction so the book flow can atomically
	// flip status=available → booked without racing against concurrent callers.
	GetSlotForUpdate(ctx context.Context, id pgtype.UUID) (Slot, error)
	// Base listing used when the caller does not pass optional filters. The
	// use-case layer composes richer filters via a hand-rolled SQL in postgres.go
	// (daily / arena do the same for dynamic WHERE clauses sqlc cannot represent).
	ListAvailableSlotsBase(ctx context.Context, limit int32) ([]Slot, error)
	// Returns every slot owned by the interviewer whose [starts_at, ends_at)
	// overlaps the [from, to) window. Used for conflict detection at create time.
	ListByInterviewerInRange(ctx context.Context, arg ListByInterviewerInRangeParams) ([]Slot, error)
	UpdateSlotStatus(ctx context.Context, arg UpdateSlotStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
