// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slot.sql

package slotdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBookingBySlotID = `-- name: CancelBookingBySlotID :execrows
UPDATE bookings SET status = 'cancelled' WHERE slot_id = $1
`

func (q *Queries) CancelBookingBySlotID(ctx context.Context, slotID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBookingBySlotID, slotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings(slot_id, candidate_id, meet_url, status)
VALUES ($1, $2, $3, 'confirmed')
RETURNING id, slot_id, candidate_id, meet_url, status, created_at
`

type CreateBookingParams struct {
	SlotID      pgtype.UUID
	CandidateID pgtype.UUID
	MeetUrl     pgtype.Text
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.SlotID, arg.CandidateID, arg.MeetUrl)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.CandidateID,
		&i.MeetUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createSlot = `-- name: CreateSlot :one

INSERT INTO slots(interviewer_id, starts_at, duration_min, section, difficulty, language, price_rub, meet_url, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, NULLIF($8::text, ''), 'available')
RETURNING id, interviewer_id, starts_at, duration_min, section, difficulty, language, price_rub, status, created_at, meet_url
`

type CreateSlotParams struct {
	InterviewerID pgtype.UUID
	StartsAt      pgtype.Timestamptz
	DurationMin   int32
	Section       string
	Difficulty    pgtype.Text
	Language      string
	PriceRub      int32
	Column8       string
}

// slot queries consumed by sqlc (emitted into services/slot/infra/db).
func (q *Queries) CreateSlot(ctx context.Context, arg CreateSlotParams) (Slot, error) {
	row := q.db.QueryRow(ctx, createSlot,
		arg.InterviewerID,
		arg.StartsAt,
		arg.DurationMin,
		arg.Section,
		arg.Difficulty,
		arg.Language,
		arg.PriceRub,
		arg.Column8,
	)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.InterviewerID,
		&i.StartsAt,
		&i.DurationMin,
		&i.Section,
		&i.Difficulty,
		&i.Language,
		&i.PriceRub,
		&i.Status,
		&i.CreatedAt,
		&i.MeetUrl,
	)
	return i, err
}

const getBookingBySlotID = `-- name: GetBookingBySlotID :one
SELECT id, slot_id, candidate_id, meet_url, status, created_at
  FROM bookings WHERE slot_id = $1
`

func (q *Queries) GetBookingBySlotID(ctx context.Context, slotID pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingBySlotID, slotID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.CandidateID,
		&i.MeetUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSlot = `-- name: GetSlot :one
SELECT id, interviewer_id, starts_at, duration_min, section, difficulty, language, price_rub, status, created_at, meet_url
  FROM slots WHERE id = $1
`

func (q *Queries) GetSlot(ctx context.Context, id pgtype.UUID) (Slot, error) {
	row := q.db.QueryRow(ctx, getSlot, id)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.InterviewerID,
		&i.StartsAt,
		&i.DurationMin,
		&i.Section,
		&i.Difficulty,
		&i.Language,
		&i.PriceRub,
		&i.Status,
		&i.CreatedAt,
		&i.MeetUrl,
	)
	return i, err
}

const getSlotForUpdate = `-- name: GetSlotForUpdate :one
SELECT id, interviewer_id, starts_at, duration_min, section, difficulty, language, price_rub, status, created_at, meet_url
  FROM slots WHERE id = $1 FOR UPDATE
`

// SELECT ... FOR UPDATE inside a transaction so the book flow can atomically
// flip status=available → booked without racing against concurrent callers.
func (q *Queries) GetSlotForUpdate(ctx context.Context, id pgtype.UUID) (Slot, error) {
	row := q.db.QueryRow(ctx, getSlotForUpdate, id)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.InterviewerID,
		&i.StartsAt,
		&i.DurationMin,
		&i.Section,
		&i.Difficulty,
		&i.Language,
		&i.PriceRub,
		&i.Status,
		&i.CreatedAt,
		&i.MeetUrl,
	)
	return i, err
}

const listAvailableSlotsBase = `-- name: ListAvailableSlotsBase :many
SELECT id, interviewer_id, starts_at, duration_min, section, difficulty, language, price_rub, status, created_at, meet_url
  FROM slots
 WHERE status = 'available'
   AND starts_at > now()
 ORDER BY starts_at ASC
 LIMIT $1
`

// Base listing used when the caller does not pass optional filters. The
// use-case layer composes richer filters via a hand-rolled SQL in postgres.go
// (daily / arena do the same for dynamic WHERE clauses sqlc cannot represent).
func (q *Queries) ListAvailableSlotsBase(ctx context.Context, limit int32) ([]Slot, error) {
	rows, err := q.db.Query(ctx, listAvailableSlotsBase, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.InterviewerID,
			&i.StartsAt,
			&i.DurationMin,
			&i.Section,
			&i.Difficulty,
			&i.Language,
			&i.PriceRub,
			&i.Status,
			&i.CreatedAt,
			&i.MeetUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByInterviewerInRange = `-- name: ListByInterviewerInRange :many
SELECT id, interviewer_id, starts_at, duration_min, section, difficulty, language, price_rub, status, created_at, meet_url
  FROM slots
 WHERE interviewer_id = $1
   AND starts_at < $3::timestamptz
   AND (starts_at + make_interval(mins => duration_min)) > $2::timestamptz
 ORDER BY starts_at ASC
`

type ListByInterviewerInRangeParams struct {
	InterviewerID pgtype.UUID
	Column2       pgtype.Timestamptz
	Column3       pgtype.Timestamptz
}

// Returns every slot owned by the interviewer whose [starts_at, ends_at)
// overlaps the [from, to) window. Used for conflict detection at create time.
func (q *Queries) ListByInterviewerInRange(ctx context.Context, arg ListByInterviewerInRangeParams) ([]Slot, error) {
	rows, err := q.db.Query(ctx, listByInterviewerInRange, arg.InterviewerID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.InterviewerID,
			&i.StartsAt,
			&i.DurationMin,
			&i.Section,
			&i.Difficulty,
			&i.Language,
			&i.PriceRub,
			&i.Status,
			&i.CreatedAt,
			&i.MeetUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSlotStatus = `-- name: UpdateSlotStatus :execrows
UPDATE slots SET status = $2 WHERE id = $1
`

type UpdateSlotStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateSlotStatus(ctx context.Context, arg UpdateSlotStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSlotStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
