// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package profiledb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWeeklyActivity = `-- name: CountWeeklyActivity :one
SELECT
  (SELECT COUNT(*)::int FROM daily_kata_history dkh WHERE dkh.user_id = $1 AND dkh.passed = true AND dkh.submitted_at >= $2)::int AS katas_passed,
  (SELECT COUNT(*)::int FROM arena_matches m
     JOIN arena_participants ap ON ap.match_id = m.id
    WHERE ap.user_id = $1 AND m.winner_id = $1 AND m.finished_at >= $2)::int AS matches_won,
  (SELECT COALESCE(SUM(ms.duration_min),0)::int FROM mock_sessions ms
    WHERE ms.user_id = $1 AND ms.finished_at >= $2)::int AS mock_minutes
`

type CountWeeklyActivityParams struct {
	UserID      pgtype.UUID
	SubmittedAt pgtype.Timestamptz
}

type CountWeeklyActivityRow struct {
	KatasPassed int32
	MatchesWon  int32
	MockMinutes int32
}

func (q *Queries) CountWeeklyActivity(ctx context.Context, arg CountWeeklyActivityParams) (CountWeeklyActivityRow, error) {
	row := q.db.QueryRow(ctx, countWeeklyActivity, arg.UserID, arg.SubmittedAt)
	var i CountWeeklyActivityRow
	err := row.Scan(&i.KatasPassed, &i.MatchesWon, &i.MockMinutes)
	return i, err
}

const ensureAICredits = `-- name: EnsureAICredits :exec
INSERT INTO ai_credits(user_id, balance) VALUES ($1, 0)
  ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureAICredits(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureAICredits, userID)
	return err
}

const ensureNotificationPrefs = `-- name: EnsureNotificationPrefs :exec
INSERT INTO notification_preferences(user_id) VALUES ($1)
  ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureNotificationPrefs(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureNotificationPrefs, userID)
	return err
}

const ensureProfile = `-- name: EnsureProfile :exec
INSERT INTO profiles(user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureProfile(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureProfile, userID)
	return err
}

const ensureSubscription = `-- name: EnsureSubscription :exec
INSERT INTO subscriptions(user_id, plan, status) VALUES ($1, 'free', 'active')
  ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureSubscription(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureSubscription, userID)
	return err
}

const getProfileBundle = `-- name: GetProfileBundle :one

SELECT u.id, u.email, u.username, u.role, u.locale, u.display_name, u.created_at,
       p.char_class, p.level, p.xp, p.title, p.avatar_frame,
       p.career_stage, p.intellect, p.strength, p.dexterity, p.will, p.updated_at,
       s.plan, s.status, s.current_period_end,
       c.balance
  FROM users u
  JOIN profiles p           ON p.user_id = u.id
  LEFT JOIN subscriptions s ON s.user_id = u.id
  LEFT JOIN ai_credits c    ON c.user_id = u.id
 WHERE u.id = $1
`

type GetProfileBundleRow struct {
	ID               pgtype.UUID
	Email            pgtype.Text
	Username         string
	Role             string
	Locale           string
	DisplayName      pgtype.Text
	CreatedAt        pgtype.Timestamptz
	CharClass        string
	Level            int32
	Xp               int64
	Title            pgtype.Text
	AvatarFrame      pgtype.Text
	CareerStage      string
	Intellect        int32
	Strength         int32
	Dexterity        int32
	Will             int32
	UpdatedAt        pgtype.Timestamptz
	Plan             pgtype.Text
	Status           pgtype.Text
	CurrentPeriodEnd pgtype.Timestamptz
	Balance          pgtype.Int4
}

// Queries consumed by sqlc; mirror the hand-rolled pgx code in infra/postgres.go.
func (q *Queries) GetProfileBundle(ctx context.Context, id pgtype.UUID) (GetProfileBundleRow, error) {
	row := q.db.QueryRow(ctx, getProfileBundle, id)
	var i GetProfileBundleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.Locale,
		&i.DisplayName,
		&i.CreatedAt,
		&i.CharClass,
		&i.Level,
		&i.Xp,
		&i.Title,
		&i.AvatarFrame,
		&i.CareerStage,
		&i.Intellect,
		&i.Strength,
		&i.Dexterity,
		&i.Will,
		&i.UpdatedAt,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.Balance,
	)
	return i, err
}

const getProfilePublic = `-- name: GetProfilePublic :one
SELECT u.id, u.username, u.display_name, u.created_at,
       p.char_class, p.level, p.xp, p.title, p.avatar_frame, p.career_stage
  FROM users u
  JOIN profiles p ON p.user_id = u.id
 WHERE u.username = $1
`

type GetProfilePublicRow struct {
	ID          pgtype.UUID
	Username    string
	DisplayName pgtype.Text
	CreatedAt   pgtype.Timestamptz
	CharClass   string
	Level       int32
	Xp          int64
	Title       pgtype.Text
	AvatarFrame pgtype.Text
	CareerStage string
}

func (q *Queries) GetProfilePublic(ctx context.Context, username string) (GetProfilePublicRow, error) {
	row := q.db.QueryRow(ctx, getProfilePublic, username)
	var i GetProfilePublicRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.CharClass,
		&i.Level,
		&i.Xp,
		&i.Title,
		&i.AvatarFrame,
		&i.CareerStage,
	)
	return i, err
}

const listRatings = `-- name: ListRatings :many
SELECT section, elo, matches_count, last_match_at
  FROM ratings WHERE user_id = $1
`

type ListRatingsRow struct {
	Section      string
	Elo          int32
	MatchesCount int32
	LastMatchAt  pgtype.Timestamptz
}

func (q *Queries) ListRatings(ctx context.Context, userID pgtype.UUID) ([]ListRatingsRow, error) {
	rows, err := q.db.Query(ctx, listRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRatingsRow{}
	for rows.Next() {
		var i ListRatingsRow
		if err := rows.Scan(
			&i.Section,
			&i.Elo,
			&i.MatchesCount,
			&i.LastMatchAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillNodes = `-- name: ListSkillNodes :many
SELECT node_key, progress, unlocked_at, decayed_at, updated_at
  FROM skill_nodes WHERE user_id = $1
`

type ListSkillNodesRow struct {
	NodeKey    string
	Progress   int32
	UnlockedAt pgtype.Timestamptz
	DecayedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListSkillNodes(ctx context.Context, userID pgtype.UUID) ([]ListSkillNodesRow, error) {
	rows, err := q.db.Query(ctx, listSkillNodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillNodesRow{}
	for rows.Next() {
		var i ListSkillNodesRow
		if err := rows.Scan(
			&i.NodeKey,
			&i.Progress,
			&i.UnlockedAt,
			&i.DecayedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCareerStage = `-- name: UpdateCareerStage :exec
UPDATE profiles SET career_stage = $2, updated_at = now() WHERE user_id = $1
`

type UpdateCareerStageParams struct {
	UserID      pgtype.UUID
	CareerStage string
}

func (q *Queries) UpdateCareerStage(ctx context.Context, arg UpdateCareerStageParams) error {
	_, err := q.db.Exec(ctx, updateCareerStage, arg.UserID, arg.CareerStage)
	return err
}

const updateProfileXPLevel = `-- name: UpdateProfileXPLevel :exec
UPDATE profiles
   SET level = $2, xp = $3, updated_at = now()
 WHERE user_id = $1
`

type UpdateProfileXPLevelParams struct {
	UserID pgtype.UUID
	Level  int32
	Xp     int64
}

func (q *Queries) UpdateProfileXPLevel(ctx context.Context, arg UpdateProfileXPLevelParams) error {
	_, err := q.db.Exec(ctx, updateProfileXPLevel, arg.UserID, arg.Level, arg.Xp)
	return err
}
