// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package profiledb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountWeeklyActivity(ctx context.Context, arg CountWeeklyActivityParams) (CountWeeklyActivityRow, error)
	EnsureAICredits(ctx context.Context, userID pgtype.UUID) error
	EnsureNotificationPrefs(ctx context.Context, userID pgtype.UUID) error
	EnsureProfile(ctx context.Context, userID pgtype.UUID) error
	EnsureSubscription(ctx context.Context, userID pgtype.UUID) error
	// Queries consumed by sqlc; mirror the hand-rolled pgx code in infra/postgres.go.
	GetProfileBundle(ctx context.Context, id pgtype.UUID) (GetProfileBundleRow, error)
	GetProfilePublic(ctx context.Context, username string) (GetProfilePublicRow, error)
	ListRatings(ctx context.Context, userID pgtype.UUID) ([]ListRatingsRow, error)
	ListSkillNodes(ctx context.Context, userID pgtype.UUID) ([]ListSkillNodesRow, error)
	UpdateCareerStage(ctx context.Context, arg UpdateCareerStageParams) error
	UpdateProfileXPLevel(ctx context.Context, arg UpdateProfileXPLevelParams) error
}

var _ Querier = (*Queries)(nil)
