// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package profiledb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApproveInterviewerApplication(ctx context.Context, arg ApproveInterviewerApplicationParams) (InterviewerApplication, error)
	// Used by RecordAppInstall trial-grant gate: «is this the very first
	// install row for the user (any app)». Returns the count BEFORE the
	// caller wrote the new row, so caller checks count == 0.
	CountUserAppInstalls(ctx context.Context, userID pgtype.UUID) (int64, error)
	// matches_won/katas_passed остаются в proto-shape но возвращают 0.
	CountWeeklyActivity(ctx context.Context, arg CountWeeklyActivityParams) (CountWeeklyActivityRow, error)
	EnsureNotificationPrefs(ctx context.Context, userID pgtype.UUID) error
	EnsureProfile(ctx context.Context, userID pgtype.UUID) error
	EnsureSubscription(ctx context.Context, userID pgtype.UUID) error
	EnsureUserXP(ctx context.Context, userID pgtype.UUID) error
	GetInterviewerApplicationByID(ctx context.Context, id pgtype.UUID) (InterviewerApplication, error)
	// Most-recent application for the user (any status).
	GetMyInterviewerApplication(ctx context.Context, userID pgtype.UUID) (InterviewerApplication, error)
	// Queries consumed by sqlc; mirror the hand-rolled pgx code in infra/postgres.go.
	// v2: email column dropped from users; xp/level moved to user_xp.
	// tutor_mode_enabled surfaced for AppShell RBAC.
	GetProfileBundle(ctx context.Context, id pgtype.UUID) (GetProfileBundleRow, error)
	GetProfilePublic(ctx context.Context, username string) (GetProfilePublicRow, error)
	ListAppInstalls(ctx context.Context, userID pgtype.UUID) ([]UserAppInstall, error)
	// Admin queue. Sorted oldest-first inside a status group so the FIFO
	// principle is obvious to moderators.
	ListInterviewerApplications(ctx context.Context, status string) ([]ListInterviewerApplicationsRow, error)
	ListSkillNodes(ctx context.Context, userID pgtype.UUID) ([]ListSkillNodesRow, error)
	RejectInterviewerApplication(ctx context.Context, arg RejectInterviewerApplicationParams) (InterviewerApplication, error)
	// Idempotent: if there's already a pending row for the user, return it
	// (the partial unique index would otherwise fire 23505). Approved/
	// rejected history rows do not block re-application.
	SubmitInterviewerApplication(ctx context.Context, arg SubmitInterviewerApplicationParams) (InterviewerApplication, error)
	// v2: xp/level live in user_xp table.
	UpdateProfileXPLevel(ctx context.Context, arg UpdateProfileXPLevelParams) error
	// Idempotent heartbeat from web / Hone / Cue.
	// xmax = 0 on the returned row means INSERT path; xmax != 0 means UPDATE
	// path (existing row touched). That bit drives the «is this the first
	// install row for the user across all 3 apps» trial-grant check upstream.
	UpsertAppInstall(ctx context.Context, arg UpsertAppInstallParams) (UpsertAppInstallRow, error)
}

var _ Querier = (*Queries)(nil)
