// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :exec
INSERT INTO oauth_accounts(
    user_id, provider, provider_user_id,
    access_token_enc, refresh_token_enc, token_expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOAuthAccountParams struct {
	UserID          pgtype.UUID
	Provider        string
	ProviderUserID  string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	TokenExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error {
	_, err := q.db.Exec(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.TokenExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(email, username, role, locale, display_name)
VALUES (NULLIF($1::text, ''), $2, $3, $4, NULLIF($5::text, ''))
RETURNING id, email, username, role, locale, display_name, created_at, updated_at
`

type CreateUserParams struct {
	Column1  string
	Username string
	Role     string
	Locale   string
	Column5  string
}

type CreateUserRow struct {
	ID          pgtype.UUID
	Email       pgtype.Text
	Username    string
	Role        string
	Locale      string
	DisplayName pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Column1,
		arg.Username,
		arg.Role,
		arg.Locale,
		arg.Column5,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.Locale,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOAuthLink = `-- name: FindOAuthLink :one
SELECT user_id
FROM oauth_accounts
WHERE provider = $1 AND provider_user_id = $2
`

type FindOAuthLinkParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) FindOAuthLink(ctx context.Context, arg FindOAuthLinkParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findOAuthLink, arg.Provider, arg.ProviderUserID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const findUserByID = `-- name: FindUserByID :one

SELECT id, email, username, role, locale, display_name, created_at, updated_at
FROM users
WHERE id = $1
`

type FindUserByIDRow struct {
	ID          pgtype.UUID
	Email       pgtype.Text
	Username    string
	Role        string
	Locale      string
	DisplayName pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// Queries consumed by sqlc. The hand-rolled pgx code in infra/postgres.go
// mirrors these 1:1 — once `make gen-sqlc` runs they will replace the hand code.
func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.Locale,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, email, username, role, locale, display_name, created_at, updated_at
FROM users
WHERE username = $1
`

type FindUserByUsernameRow struct {
	ID          pgtype.UUID
	Email       pgtype.Text
	Username    string
	Role        string
	Locale      string
	DisplayName pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (FindUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i FindUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.Locale,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchOAuthTokens = `-- name: TouchOAuthTokens :exec
UPDATE oauth_accounts
   SET access_token_enc  = COALESCE($3, access_token_enc),
       refresh_token_enc = COALESCE($4, refresh_token_enc),
       token_expires_at  = COALESCE($5, token_expires_at)
 WHERE provider = $1 AND provider_user_id = $2
`

type TouchOAuthTokensParams struct {
	Provider        string
	ProviderUserID  string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	TokenExpiresAt  pgtype.Timestamptz
}

func (q *Queries) TouchOAuthTokens(ctx context.Context, arg TouchOAuthTokensParams) error {
	_, err := q.db.Exec(ctx, touchOAuthTokens,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.TokenExpiresAt,
	)
	return err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
