// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/repo_mock.go -source repo.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/daily/domain"
	enums "druz9/shared/enums"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
	isgomock struct{}
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockTaskRepo) GetByID(ctx context.Context, id uuid.UUID) (domain.TaskPublic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.TaskPublic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepo)(nil).GetByID), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockTaskRepo) GetBySlug(ctx context.Context, slug string) (domain.TaskPublic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(domain.TaskPublic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockTaskRepoMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockTaskRepo)(nil).GetBySlug), ctx, slug)
}

// ListActiveBySectionDifficulty mocks base method.
func (m *MockTaskRepo) ListActiveBySectionDifficulty(ctx context.Context, section enums.Section, diff enums.Difficulty) ([]domain.TaskPublic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveBySectionDifficulty", ctx, section, diff)
	ret0, _ := ret[0].([]domain.TaskPublic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveBySectionDifficulty indicates an expected call of ListActiveBySectionDifficulty.
func (mr *MockTaskRepoMockRecorder) ListActiveBySectionDifficulty(ctx, section, diff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveBySectionDifficulty", reflect.TypeOf((*MockTaskRepo)(nil).ListActiveBySectionDifficulty), ctx, section, diff)
}

// MockSkillRepo is a mock of SkillRepo interface.
type MockSkillRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSkillRepoMockRecorder
	isgomock struct{}
}

// MockSkillRepoMockRecorder is the mock recorder for MockSkillRepo.
type MockSkillRepoMockRecorder struct {
	mock *MockSkillRepo
}

// NewMockSkillRepo creates a new mock instance.
func NewMockSkillRepo(ctrl *gomock.Controller) *MockSkillRepo {
	mock := &MockSkillRepo{ctrl: ctrl}
	mock.recorder = &MockSkillRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillRepo) EXPECT() *MockSkillRepoMockRecorder {
	return m.recorder
}

// WeakestNode mocks base method.
func (m *MockSkillRepo) WeakestNode(ctx context.Context, userID uuid.UUID) (domain.NodeWeakness, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WeakestNode", ctx, userID)
	ret0, _ := ret[0].(domain.NodeWeakness)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WeakestNode indicates an expected call of WeakestNode.
func (mr *MockSkillRepoMockRecorder) WeakestNode(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WeakestNode", reflect.TypeOf((*MockSkillRepo)(nil).WeakestNode), ctx, userID)
}

// MockKataRepo is a mock of KataRepo interface.
type MockKataRepo struct {
	ctrl     *gomock.Controller
	recorder *MockKataRepoMockRecorder
	isgomock struct{}
}

// MockKataRepoMockRecorder is the mock recorder for MockKataRepo.
type MockKataRepoMockRecorder struct {
	mock *MockKataRepo
}

// NewMockKataRepo creates a new mock instance.
func NewMockKataRepo(ctrl *gomock.Controller) *MockKataRepo {
	mock := &MockKataRepo{ctrl: ctrl}
	mock.recorder = &MockKataRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKataRepo) EXPECT() *MockKataRepoMockRecorder {
	return m.recorder
}

// GetOrAssign mocks base method.
func (m *MockKataRepo) GetOrAssign(ctx context.Context, userID uuid.UUID, date time.Time, taskID uuid.UUID, isCursed, isWeeklyBoss bool) (domain.Assignment, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrAssign", ctx, userID, date, taskID, isCursed, isWeeklyBoss)
	ret0, _ := ret[0].(domain.Assignment)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrAssign indicates an expected call of GetOrAssign.
func (mr *MockKataRepoMockRecorder) GetOrAssign(ctx, userID, date, taskID, isCursed, isWeeklyBoss any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrAssign", reflect.TypeOf((*MockKataRepo)(nil).GetOrAssign), ctx, userID, date, taskID, isCursed, isWeeklyBoss)
}

// HistoryByYear mocks base method.
func (m *MockKataRepo) HistoryByYear(ctx context.Context, userID uuid.UUID, year int) ([]domain.HistoryEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HistoryByYear", ctx, userID, year)
	ret0, _ := ret[0].([]domain.HistoryEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HistoryByYear indicates an expected call of HistoryByYear.
func (mr *MockKataRepoMockRecorder) HistoryByYear(ctx, userID, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HistoryByYear", reflect.TypeOf((*MockKataRepo)(nil).HistoryByYear), ctx, userID, year)
}

// HistoryLast30 mocks base method.
func (m *MockKataRepo) HistoryLast30(ctx context.Context, userID uuid.UUID, today time.Time) ([]domain.HistoryEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HistoryLast30", ctx, userID, today)
	ret0, _ := ret[0].([]domain.HistoryEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HistoryLast30 indicates an expected call of HistoryLast30.
func (mr *MockKataRepoMockRecorder) HistoryLast30(ctx, userID, today any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HistoryLast30", reflect.TypeOf((*MockKataRepo)(nil).HistoryLast30), ctx, userID, today)
}

// MarkSubmitted mocks base method.
func (m *MockKataRepo) MarkSubmitted(ctx context.Context, userID uuid.UUID, date time.Time, passed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSubmitted", ctx, userID, date, passed)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSubmitted indicates an expected call of MarkSubmitted.
func (mr *MockKataRepoMockRecorder) MarkSubmitted(ctx, userID, date, passed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSubmitted", reflect.TypeOf((*MockKataRepo)(nil).MarkSubmitted), ctx, userID, date, passed)
}

// MockStreakRepo is a mock of StreakRepo interface.
type MockStreakRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStreakRepoMockRecorder
	isgomock struct{}
}

// MockStreakRepoMockRecorder is the mock recorder for MockStreakRepo.
type MockStreakRepoMockRecorder struct {
	mock *MockStreakRepo
}

// NewMockStreakRepo creates a new mock instance.
func NewMockStreakRepo(ctrl *gomock.Controller) *MockStreakRepo {
	mock := &MockStreakRepo{ctrl: ctrl}
	mock.recorder = &MockStreakRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreakRepo) EXPECT() *MockStreakRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStreakRepo) Get(ctx context.Context, userID uuid.UUID) (domain.StreakState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(domain.StreakState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStreakRepoMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStreakRepo)(nil).Get), ctx, userID)
}

// Update mocks base method.
func (m *MockStreakRepo) Update(ctx context.Context, userID uuid.UUID, s domain.StreakState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStreakRepoMockRecorder) Update(ctx, userID, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStreakRepo)(nil).Update), ctx, userID, s)
}

// MockJudge0Client is a mock of Judge0Client interface.
type MockJudge0Client struct {
	ctrl     *gomock.Controller
	recorder *MockJudge0ClientMockRecorder
	isgomock struct{}
}

// MockJudge0ClientMockRecorder is the mock recorder for MockJudge0Client.
type MockJudge0ClientMockRecorder struct {
	mock *MockJudge0Client
}

// NewMockJudge0Client creates a new mock instance.
func NewMockJudge0Client(ctrl *gomock.Controller) *MockJudge0Client {
	mock := &MockJudge0Client{ctrl: ctrl}
	mock.recorder = &MockJudge0ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJudge0Client) EXPECT() *MockJudge0ClientMockRecorder {
	return m.recorder
}

// Submit mocks base method.
func (m *MockJudge0Client) Submit(ctx context.Context, code, language string, task domain.TaskPublic) (bool, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, code, language, task)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Submit indicates an expected call of Submit.
func (mr *MockJudge0ClientMockRecorder) Submit(ctx, code, language, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockJudge0Client)(nil).Submit), ctx, code, language, task)
}

// MockTestCaseRepo is a mock of TestCaseRepo interface.
type MockTestCaseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTestCaseRepoMockRecorder
	isgomock struct{}
}

// MockTestCaseRepoMockRecorder is the mock recorder for MockTestCaseRepo.
type MockTestCaseRepoMockRecorder struct {
	mock *MockTestCaseRepo
}

// NewMockTestCaseRepo creates a new mock instance.
func NewMockTestCaseRepo(ctrl *gomock.Controller) *MockTestCaseRepo {
	mock := &MockTestCaseRepo{ctrl: ctrl}
	mock.recorder = &MockTestCaseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestCaseRepo) EXPECT() *MockTestCaseRepoMockRecorder {
	return m.recorder
}

// ListForTask mocks base method.
func (m *MockTestCaseRepo) ListForTask(ctx context.Context, taskID uuid.UUID) ([]domain.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForTask", ctx, taskID)
	ret0, _ := ret[0].([]domain.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForTask indicates an expected call of ListForTask.
func (mr *MockTestCaseRepoMockRecorder) ListForTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForTask", reflect.TypeOf((*MockTestCaseRepo)(nil).ListForTask), ctx, taskID)
}
