// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package podcastdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetPodcastByID(ctx context.Context, id pgtype.UUID) (Podcast, error)
	GetPodcastProgress(ctx context.Context, arg GetPodcastProgressParams) (PodcastProgress, error)
	// podcast queries consumed by sqlc (emitted into services/podcast/infra/db).
	// Catalog join: every published podcast + the requesting user's progress row
	// (if any). Optional section filter — when @filter_by_section = FALSE the
	// second predicate is a no-op so the query collapses to "everything".
	ListPodcastsWithProgress(ctx context.Context, arg ListPodcastsWithProgressParams) ([]ListPodcastsWithProgressRow, error)
	UpsertPodcastProgress(ctx context.Context, arg UpsertPodcastProgressParams) error
}

var _ Querier = (*Queries)(nil)
