// Code generated by MockGen. DO NOT EDIT.
// Source: memory.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/memory_mock.go -source memory.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/intelligence/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEpisodeRepo is a mock of EpisodeRepo interface.
type MockEpisodeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEpisodeRepoMockRecorder
	isgomock struct{}
}

// MockEpisodeRepoMockRecorder is the mock recorder for MockEpisodeRepo.
type MockEpisodeRepoMockRecorder struct {
	mock *MockEpisodeRepo
}

// NewMockEpisodeRepo creates a new mock instance.
func NewMockEpisodeRepo(ctrl *gomock.Controller) *MockEpisodeRepo {
	mock := &MockEpisodeRepo{ctrl: ctrl}
	mock.recorder = &MockEpisodeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEpisodeRepo) EXPECT() *MockEpisodeRepoMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockEpisodeRepo) Append(ctx context.Context, e domain.Episode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockEpisodeRepoMockRecorder) Append(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockEpisodeRepo)(nil).Append), ctx, e)
}

// CountByKindInRange mocks base method.
func (m *MockEpisodeRepo) CountByKindInRange(ctx context.Context, userID uuid.UUID, from, to time.Time) (map[domain.EpisodeKind]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByKindInRange", ctx, userID, from, to)
	ret0, _ := ret[0].(map[domain.EpisodeKind]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByKindInRange indicates an expected call of CountByKindInRange.
func (mr *MockEpisodeRepoMockRecorder) CountByKindInRange(ctx, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByKindInRange", reflect.TypeOf((*MockEpisodeRepo)(nil).CountByKindInRange), ctx, userID, from, to)
}

// DeleteOlderThan mocks base method.
func (m *MockEpisodeRepo) DeleteOlderThan(ctx context.Context, cutoff time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", ctx, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockEpisodeRepoMockRecorder) DeleteOlderThan(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockEpisodeRepo)(nil).DeleteOlderThan), ctx, cutoff)
}

// GetBriefRecommendations mocks base method.
func (m *MockEpisodeRepo) GetBriefRecommendations(ctx context.Context, userID, briefID uuid.UUID) ([]domain.Recommendation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBriefRecommendations", ctx, userID, briefID)
	ret0, _ := ret[0].([]domain.Recommendation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBriefRecommendations indicates an expected call of GetBriefRecommendations.
func (mr *MockEpisodeRepoMockRecorder) GetBriefRecommendations(ctx, userID, briefID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBriefRecommendations", reflect.TypeOf((*MockEpisodeRepo)(nil).GetBriefRecommendations), ctx, userID, briefID)
}

// HasWeeklySummary mocks base method.
func (m *MockEpisodeRepo) HasWeeklySummary(ctx context.Context, userID uuid.UUID, weekStart time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWeeklySummary", ctx, userID, weekStart)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasWeeklySummary indicates an expected call of HasWeeklySummary.
func (mr *MockEpisodeRepoMockRecorder) HasWeeklySummary(ctx, userID, weekStart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWeeklySummary", reflect.TypeOf((*MockEpisodeRepo)(nil).HasWeeklySummary), ctx, userID, weekStart)
}

// LatestByKind mocks base method.
func (m *MockEpisodeRepo) LatestByKind(ctx context.Context, userID uuid.UUID, kind domain.EpisodeKind, limit int) ([]domain.Episode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestByKind", ctx, userID, kind, limit)
	ret0, _ := ret[0].([]domain.Episode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestByKind indicates an expected call of LatestByKind.
func (mr *MockEpisodeRepoMockRecorder) LatestByKind(ctx, userID, kind, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestByKind", reflect.TypeOf((*MockEpisodeRepo)(nil).LatestByKind), ctx, userID, kind, limit)
}

// LatestByKinds mocks base method.
func (m *MockEpisodeRepo) LatestByKinds(ctx context.Context, userID uuid.UUID, kinds []domain.EpisodeKind, limit int) ([]domain.Episode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestByKinds", ctx, userID, kinds, limit)
	ret0, _ := ret[0].([]domain.Episode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestByKinds indicates an expected call of LatestByKinds.
func (mr *MockEpisodeRepoMockRecorder) LatestByKinds(ctx, userID, kinds, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestByKinds", reflect.TypeOf((*MockEpisodeRepo)(nil).LatestByKinds), ctx, userID, kinds, limit)
}

// LatestPerKind mocks base method.
func (m *MockEpisodeRepo) LatestPerKind(ctx context.Context, userID uuid.UUID, kinds []domain.EpisodeKind, perKindLimit int) ([]domain.Episode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestPerKind", ctx, userID, kinds, perKindLimit)
	ret0, _ := ret[0].([]domain.Episode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestPerKind indicates an expected call of LatestPerKind.
func (mr *MockEpisodeRepoMockRecorder) LatestPerKind(ctx, userID, kinds, perKindLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestPerKind", reflect.TypeOf((*MockEpisodeRepo)(nil).LatestPerKind), ctx, userID, kinds, perKindLimit)
}

// MarkStaleForReembed mocks base method.
func (m *MockEpisodeRepo) MarkStaleForReembed(ctx context.Context, currentModelName string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkStaleForReembed", ctx, currentModelName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkStaleForReembed indicates an expected call of MarkStaleForReembed.
func (mr *MockEpisodeRepoMockRecorder) MarkStaleForReembed(ctx, currentModelName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkStaleForReembed", reflect.TypeOf((*MockEpisodeRepo)(nil).MarkStaleForReembed), ctx, currentModelName)
}

// PendingEmbeddings mocks base method.
func (m *MockEpisodeRepo) PendingEmbeddings(ctx context.Context, limit int) ([]domain.Episode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingEmbeddings", ctx, limit)
	ret0, _ := ret[0].([]domain.Episode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingEmbeddings indicates an expected call of PendingEmbeddings.
func (mr *MockEpisodeRepoMockRecorder) PendingEmbeddings(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingEmbeddings", reflect.TypeOf((*MockEpisodeRepo)(nil).PendingEmbeddings), ctx, limit)
}

// SearchSimilar mocks base method.
func (m *MockEpisodeRepo) SearchSimilar(ctx context.Context, userID uuid.UUID, vec []float32, modelName string, kinds []domain.EpisodeKind, limit int) ([]domain.EpisodeWithScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSimilar", ctx, userID, vec, modelName, kinds, limit)
	ret0, _ := ret[0].([]domain.EpisodeWithScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSimilar indicates an expected call of SearchSimilar.
func (mr *MockEpisodeRepoMockRecorder) SearchSimilar(ctx, userID, vec, modelName, kinds, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSimilar", reflect.TypeOf((*MockEpisodeRepo)(nil).SearchSimilar), ctx, userID, vec, modelName, kinds, limit)
}

// SetEmbedding mocks base method.
func (m *MockEpisodeRepo) SetEmbedding(ctx context.Context, id uuid.UUID, vec []float32, model string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmbedding", ctx, id, vec, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEmbedding indicates an expected call of SetEmbedding.
func (mr *MockEpisodeRepoMockRecorder) SetEmbedding(ctx, id, vec, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmbedding", reflect.TypeOf((*MockEpisodeRepo)(nil).SetEmbedding), ctx, id, vec, model)
}

// Stats30d mocks base method.
func (m *MockEpisodeRepo) Stats30d(ctx context.Context, userID uuid.UUID) (domain.MemoryStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats30d", ctx, userID)
	ret0, _ := ret[0].(domain.MemoryStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats30d indicates an expected call of Stats30d.
func (mr *MockEpisodeRepoMockRecorder) Stats30d(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats30d", reflect.TypeOf((*MockEpisodeRepo)(nil).Stats30d), ctx, userID)
}
