// Code generated by MockGen. DO NOT EDIT.
// Source: embed_worker.go
//
// Generated by this command:
//
//	mockgen -package app -destination embed_worker_mock_test.go -source embed_worker.go EmbedQueue
//

// Package app is a generated GoMock package.
package app

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmbedQueue is a mock of EmbedQueue interface.
type MockEmbedQueue struct {
	ctrl     *gomock.Controller
	recorder *MockEmbedQueueMockRecorder
	isgomock struct{}
}

// MockEmbedQueueMockRecorder is the mock recorder for MockEmbedQueue.
type MockEmbedQueueMockRecorder struct {
	mock *MockEmbedQueue
}

// NewMockEmbedQueue creates a new mock instance.
func NewMockEmbedQueue(ctrl *gomock.Controller) *MockEmbedQueue {
	mock := &MockEmbedQueue{ctrl: ctrl}
	mock.recorder = &MockEmbedQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbedQueue) EXPECT() *MockEmbedQueueMockRecorder {
	return m.recorder
}

// Dequeue mocks base method.
func (m *MockEmbedQueue) Dequeue(ctx context.Context) (EmbedJobItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dequeue", ctx)
	ret0, _ := ret[0].(EmbedJobItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dequeue indicates an expected call of Dequeue.
func (mr *MockEmbedQueueMockRecorder) Dequeue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dequeue", reflect.TypeOf((*MockEmbedQueue)(nil).Dequeue), ctx)
}
