// WeeklyReportSharePage — публичная read-only страница /weekly/share/:token.
//
// Phase C killer-stats: токен выдаётся бэком из weekly_share_tokens (TTL 30d,
// см. backend/services/profile/infra/postgres.go IssueShareToken). Маршрут
// в publicPaths, авторизация не нужна. Никаких goals / AI insight refresh /
// edit-actions — share-страница только показывает агрегаты недели.
import { useEffect } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useWeeklyShareQuery } from '../lib/queries/profile'

function ShareHeader({ subtitle }: { subtitle: string }) {
  return (
    <header className="flex h-[72px] items-center justify-between border-b border-border bg-bg px-4 sm:px-8">
      <Link to="/" className="flex items-center gap-2.5">
        <span className="grid h-8 w-8 place-items-center rounded-md bg-gradient-to-br from-accent to-cyan font-display text-lg font-extrabold text-text-primary">
          9
        </span>
        <span className="font-display text-lg font-bold text-text-primary">druz9</span>
      </Link>
      <span className="font-mono text-[11px] text-text-muted">{subtitle}</span>
    </header>
  )
}

function MetricTile({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="flex flex-col gap-1.5 rounded-2xl bg-surface-2 p-5">
      <span className="font-mono text-[11px] font-semibold tracking-[0.08em] text-text-muted">{label}</span>
      <span className="font-display text-2xl font-extrabold text-text-primary">{value}</span>
      {sub && <span className="text-[11px] text-text-muted">{sub}</span>}
    </div>
  )
}

function SectionRow({
  letter,
  name,
  sub,
  delta,
  tone,
}: {
  letter: string
  name: string
  sub: string
  delta: string
  tone: 'success' | 'warn' | 'danger'
}) {
  const colors: Record<typeof tone, string> = {
    success: 'bg-success/20 text-success',
    warn: 'bg-warn/20 text-warn',
    danger: 'bg-danger/20 text-danger',
  }
  const deltaColors: Record<typeof tone, string> = {
    success: 'text-success',
    warn: 'text-warn',
    danger: 'text-danger',
  }
  return (
    <div className="flex items-center gap-3">
      <span className={`grid h-9 w-9 place-items-center rounded-full font-display text-sm font-bold ${colors[tone]}`}>
        {letter}
      </span>
      <div className="flex flex-1 flex-col">
        <span className="text-sm font-semibold text-text-primary">{name}</span>
        <span className="text-[11px] text-text-muted">{sub}</span>
      </div>
      <span className={`font-mono text-sm font-bold ${deltaColors[tone]}`}>{delta}</span>
    </div>
  )
}

const SECTION_LETTERS: Record<string, string> = {
  algorithms: 'A',
  sql: 'Q',
  go: 'G',
  system_design: 'S',
  behavioral: 'B',
}

const SECTION_NAMES: Record<string, string> = {
  algorithms: 'Algorithms',
  sql: 'SQL',
  go: 'Go',
  system_design: 'System Design',
  behavioral: 'Behavioral',
}

function fmtPeriod(weekStart: string, weekEnd: string): string {
  try {
    const start = new Date(weekStart)
    const end = new Date(weekEnd)
    const opts: Intl.DateTimeFormatOptions = { day: 'numeric', month: 'long' }
    const startStr = start.toLocaleDateString('ru', { day: 'numeric' })
    const endStr = end.toLocaleDateString('ru', opts)
    return `${startStr}–${endStr}`
  } catch {
    return `${weekStart} — ${weekEnd}`
  }
}

export default function WeeklyReportSharePage() {
  const { token } = useParams<{ token: string }>()
  useEffect(() => {
    document.body.classList.add('v2')
    return () => document.body.classList.remove('v2')
  }, [])
  const { data, isLoading, isError, error } = useWeeklyShareQuery(token)

  // 404 — токен протух или не существует. Anti-fallback: НЕ показываем
  // пустой отчёт, а сразу честную ошибку. Сетевая ошибка → общий retry-bann.
  const status = (error as { status?: number } | null)?.status
  if (isError && status === 404) {
    return (
      <div className="min-h-screen bg-bg text-text-primary">
        <ShareHeader subtitle="Generated by druz9.dev" />
        <main className="flex min-h-[calc(100vh-72px)] flex-col items-center justify-center gap-4 px-6 py-12 text-center">
          <div className="font-display text-5xl font-extrabold text-accent">404</div>
          <h1 className="font-display text-2xl font-bold text-text-primary">Ссылка устарела</h1>
          <p className="max-w-md text-sm text-text-secondary">
            Эта публичная ссылка на недельный отчёт больше не активна. Попроси автора
            сгенерировать новую на /weekly.
          </p>
          <Link to="/" className="font-mono text-[12px] text-accent underline">
            druz9.dev
          </Link>
        </main>
      </div>
    )
  }

  if (isLoading || !data) {
    return (
      <div className="min-h-screen bg-bg text-text-primary">
        <ShareHeader subtitle="Generated by druz9.dev" />
        <main className="flex min-h-[calc(100vh-72px)] items-center justify-center px-6 py-12">
          <span className="font-mono text-[12px] text-text-muted">Загружаем отчёт…</span>
        </main>
      </div>
    )
  }

  const m = data.metrics
  const period = fmtPeriod(data.week_start, data.week_end)

  return (
    <div className="min-h-screen bg-bg text-text-primary">
      <ShareHeader subtitle="Generated by druz9.dev" />
      <main className="mx-auto flex max-w-5xl flex-col gap-6 px-4 py-8 sm:px-8">
        <div className="flex flex-col gap-1.5">
          <h1 className="font-display text-2xl font-bold text-text-primary lg:text-[32px]">
            Weekly report · {period}
          </h1>
          <p className="text-sm text-text-secondary">
            Публичный недельный отчёт. Сгенерирован на{' '}
            <Link to="/" className="text-accent underline">
              druz9.dev
            </Link>
            .
          </p>
        </div>

        <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
          <MetricTile label="XP" value={String(m.xp_earned)} sub="за неделю" />
          <MetricTile label="МАТЧЕЙ ВЫИГРАНО" value={String(m.matches_won)} />
          <MetricTile
            label="СТРИК"
            value={String(data.streak_days ?? 0)}
            sub={`лучший: ${data.best_streak ?? 0}`}
          />
          <MetricTile label="LP" value={String(m.rating_change)} sub="изменение рейтинга" />
        </div>

        <div className="grid gap-5 lg:grid-cols-2">
          <div className="flex flex-col gap-3 rounded-2xl border border-success bg-surface-2 p-5">
            <h3 className="font-display text-sm font-bold text-text-primary">Сильные секции</h3>
            {(data.strong_sections ?? []).length === 0 ? (
              <p className="text-[12px] text-text-muted">Нет данных за неделю.</p>
            ) : (
              (data.strong_sections ?? []).map((s) => (
                <SectionRow
                  key={s.section}
                  letter={SECTION_LETTERS[s.section] ?? s.section.charAt(0).toUpperCase()}
                  name={SECTION_NAMES[s.section] ?? s.section}
                  sub={`${s.matches} матчей · ${s.win_rate_pct}% wr`}
                  delta={`${s.xp_delta >= 0 ? '+' : ''}${s.xp_delta} XP`}
                  tone="success"
                />
              ))
            )}
          </div>
          <div className="flex flex-col gap-3 rounded-2xl border border-danger bg-surface-2 p-5">
            <h3 className="font-display text-sm font-bold text-text-primary">Слабые секции</h3>
            {(data.weak_sections ?? []).length === 0 ? (
              <p className="text-[12px] text-text-muted">Слабых секций нет.</p>
            ) : (
              (data.weak_sections ?? []).map((s, idx) => (
                <SectionRow
                  key={s.section}
                  letter={SECTION_LETTERS[s.section] ?? s.section.charAt(0).toUpperCase()}
                  name={SECTION_NAMES[s.section] ?? s.section}
                  sub={`${s.matches} матчей · ${s.win_rate_pct}% wr`}
                  delta={`${s.xp_delta >= 0 ? '+' : ''}${s.xp_delta} XP`}
                  tone={idx === 0 ? 'danger' : 'warn'}
                />
              ))
            )}
          </div>
        </div>

        {data.stress_analysis && (
          <div className="rounded-2xl border border-accent-hover bg-gradient-to-br from-accent/20 to-pink/20 p-5">
            <h3 className="mb-2 font-display text-sm font-bold text-text-primary">Психологический паттерн</h3>
            <p className="text-xs leading-relaxed text-text-secondary">{data.stress_analysis}</p>
          </div>
        )}
      </main>
    </div>
  )
}
