// Code generated by MockGen. DO NOT EDIT.
// Source: dashboard.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/dashboard_mock.go -source dashboard.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/admin/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDashboardRepo is a mock of DashboardRepo interface.
type MockDashboardRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardRepoMockRecorder
	isgomock struct{}
}

// MockDashboardRepoMockRecorder is the mock recorder for MockDashboardRepo.
type MockDashboardRepoMockRecorder struct {
	mock *MockDashboardRepo
}

// NewMockDashboardRepo creates a new mock instance.
func NewMockDashboardRepo(ctrl *gomock.Controller) *MockDashboardRepo {
	mock := &MockDashboardRepo{ctrl: ctrl}
	mock.recorder = &MockDashboardRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardRepo) EXPECT() *MockDashboardRepoMockRecorder {
	return m.recorder
}

// Snapshot mocks base method.
func (m *MockDashboardRepo) Snapshot(ctx context.Context, now time.Time) (domain.AdminDashboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx, now)
	ret0, _ := ret[0].(domain.AdminDashboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockDashboardRepoMockRecorder) Snapshot(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockDashboardRepo)(nil).Snapshot), ctx, now)
}
