// Code generated by MockGen. DO NOT EDIT.
// Source: goal_preset.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/goal_preset_mock.go -source goal_preset.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/admin/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGoalPresetRepo is a mock of GoalPresetRepo interface.
type MockGoalPresetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGoalPresetRepoMockRecorder
	isgomock struct{}
}

// MockGoalPresetRepoMockRecorder is the mock recorder for MockGoalPresetRepo.
type MockGoalPresetRepoMockRecorder struct {
	mock *MockGoalPresetRepo
}

// NewMockGoalPresetRepo creates a new mock instance.
func NewMockGoalPresetRepo(ctrl *gomock.Controller) *MockGoalPresetRepo {
	mock := &MockGoalPresetRepo{ctrl: ctrl}
	mock.recorder = &MockGoalPresetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoalPresetRepo) EXPECT() *MockGoalPresetRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGoalPresetRepo) Create(ctx context.Context, in domain.GoalPresetUpsert) (domain.GoalPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(domain.GoalPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGoalPresetRepoMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGoalPresetRepo)(nil).Create), ctx, in)
}

// Deactivate mocks base method.
func (m *MockGoalPresetRepo) Deactivate(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockGoalPresetRepoMockRecorder) Deactivate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockGoalPresetRepo)(nil).Deactivate), ctx, id)
}

// GetByID mocks base method.
func (m *MockGoalPresetRepo) GetByID(ctx context.Context, id uuid.UUID) (domain.GoalPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.GoalPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGoalPresetRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGoalPresetRepo)(nil).GetByID), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockGoalPresetRepo) GetBySlug(ctx context.Context, slug string) (domain.GoalPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(domain.GoalPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockGoalPresetRepoMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockGoalPresetRepo)(nil).GetBySlug), ctx, slug)
}

// List mocks base method.
func (m *MockGoalPresetRepo) List(ctx context.Context, activeOnly bool) ([]domain.GoalPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, activeOnly)
	ret0, _ := ret[0].([]domain.GoalPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGoalPresetRepoMockRecorder) List(ctx, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGoalPresetRepo)(nil).List), ctx, activeOnly)
}

// Update mocks base method.
func (m *MockGoalPresetRepo) Update(ctx context.Context, id uuid.UUID, in domain.GoalPresetPatch) (domain.GoalPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, in)
	ret0, _ := ret[0].(domain.GoalPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGoalPresetRepoMockRecorder) Update(ctx, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGoalPresetRepo)(nil).Update), ctx, id, in)
}
