// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/repo_mock.go -source repo.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/admin/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
	isgomock struct{}
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTaskRepo) Create(ctx context.Context, in domain.TaskUpsert) (domain.AdminTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(domain.AdminTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepoMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepo)(nil).Create), ctx, in)
}

// GetByID mocks base method.
func (m *MockTaskRepo) GetByID(ctx context.Context, id uuid.UUID) (domain.AdminTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.AdminTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTaskRepo) List(ctx context.Context, f domain.TaskFilter) (domain.TaskPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, f)
	ret0, _ := ret[0].(domain.TaskPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTaskRepoMockRecorder) List(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepo)(nil).List), ctx, f)
}

// Update mocks base method.
func (m *MockTaskRepo) Update(ctx context.Context, id uuid.UUID, in domain.TaskUpsert) (domain.AdminTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, in)
	ret0, _ := ret[0].(domain.AdminTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepoMockRecorder) Update(ctx, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepo)(nil).Update), ctx, id, in)
}

// MockCompanyRepo is a mock of CompanyRepo interface.
type MockCompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyRepoMockRecorder
	isgomock struct{}
}

// MockCompanyRepoMockRecorder is the mock recorder for MockCompanyRepo.
type MockCompanyRepoMockRecorder struct {
	mock *MockCompanyRepo
}

// NewMockCompanyRepo creates a new mock instance.
func NewMockCompanyRepo(ctrl *gomock.Controller) *MockCompanyRepo {
	mock := &MockCompanyRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyRepo) EXPECT() *MockCompanyRepoMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockCompanyRepo) List(ctx context.Context) ([]domain.AdminCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.AdminCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCompanyRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCompanyRepo)(nil).List), ctx)
}

// Upsert mocks base method.
func (m *MockCompanyRepo) Upsert(ctx context.Context, in domain.CompanyUpsert) (domain.AdminCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, in)
	ret0, _ := ret[0].(domain.AdminCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCompanyRepoMockRecorder) Upsert(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCompanyRepo)(nil).Upsert), ctx, in)
}

// MockConfigRepo is a mock of ConfigRepo interface.
type MockConfigRepo struct {
	ctrl     *gomock.Controller
	recorder *MockConfigRepoMockRecorder
	isgomock struct{}
}

// MockConfigRepoMockRecorder is the mock recorder for MockConfigRepo.
type MockConfigRepoMockRecorder struct {
	mock *MockConfigRepo
}

// NewMockConfigRepo creates a new mock instance.
func NewMockConfigRepo(ctrl *gomock.Controller) *MockConfigRepo {
	mock := &MockConfigRepo{ctrl: ctrl}
	mock.recorder = &MockConfigRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigRepo) EXPECT() *MockConfigRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConfigRepo) Get(ctx context.Context, key string) (domain.ConfigEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(domain.ConfigEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfigRepoMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigRepo)(nil).Get), ctx, key)
}

// List mocks base method.
func (m *MockConfigRepo) List(ctx context.Context) ([]domain.ConfigEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.ConfigEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConfigRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConfigRepo)(nil).List), ctx)
}

// Upsert mocks base method.
func (m *MockConfigRepo) Upsert(ctx context.Context, entry domain.ConfigEntry, updatedBy *uuid.UUID) (domain.ConfigEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, entry, updatedBy)
	ret0, _ := ret[0].(domain.ConfigEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockConfigRepoMockRecorder) Upsert(ctx, entry, updatedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockConfigRepo)(nil).Upsert), ctx, entry, updatedBy)
}

// MockConfigBroadcaster is a mock of ConfigBroadcaster interface.
type MockConfigBroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockConfigBroadcasterMockRecorder
	isgomock struct{}
}

// MockConfigBroadcasterMockRecorder is the mock recorder for MockConfigBroadcaster.
type MockConfigBroadcasterMockRecorder struct {
	mock *MockConfigBroadcaster
}

// NewMockConfigBroadcaster creates a new mock instance.
func NewMockConfigBroadcaster(ctrl *gomock.Controller) *MockConfigBroadcaster {
	mock := &MockConfigBroadcaster{ctrl: ctrl}
	mock.recorder = &MockConfigBroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigBroadcaster) EXPECT() *MockConfigBroadcasterMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockConfigBroadcaster) Publish(ctx context.Context, entry domain.ConfigEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockConfigBroadcasterMockRecorder) Publish(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockConfigBroadcaster)(nil).Publish), ctx, entry)
}

// MockAnticheatRepo is a mock of AnticheatRepo interface.
type MockAnticheatRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAnticheatRepoMockRecorder
	isgomock struct{}
}

// MockAnticheatRepoMockRecorder is the mock recorder for MockAnticheatRepo.
type MockAnticheatRepoMockRecorder struct {
	mock *MockAnticheatRepo
}

// NewMockAnticheatRepo creates a new mock instance.
func NewMockAnticheatRepo(ctrl *gomock.Controller) *MockAnticheatRepo {
	mock := &MockAnticheatRepo{ctrl: ctrl}
	mock.recorder = &MockAnticheatRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnticheatRepo) EXPECT() *MockAnticheatRepoMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockAnticheatRepo) List(ctx context.Context, f domain.AnticheatFilter) ([]domain.AnticheatSignal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, f)
	ret0, _ := ret[0].([]domain.AnticheatSignal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAnticheatRepoMockRecorder) List(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAnticheatRepo)(nil).List), ctx, f)
}
