// Code generated by MockGen. DO NOT EDIT.
// Source: status.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/status_mock.go -source status.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/admin/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStatusProber is a mock of StatusProber interface.
type MockStatusProber struct {
	ctrl     *gomock.Controller
	recorder *MockStatusProberMockRecorder
	isgomock struct{}
}

// MockStatusProberMockRecorder is the mock recorder for MockStatusProber.
type MockStatusProberMockRecorder struct {
	mock *MockStatusProber
}

// NewMockStatusProber creates a new mock instance.
func NewMockStatusProber(ctrl *gomock.Controller) *MockStatusProber {
	mock := &MockStatusProber{ctrl: ctrl}
	mock.recorder = &MockStatusProberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusProber) EXPECT() *MockStatusProberMockRecorder {
	return m.recorder
}

// Probe mocks base method.
func (m *MockStatusProber) Probe(ctx context.Context) ([]domain.StatusServiceState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Probe", ctx)
	ret0, _ := ret[0].([]domain.StatusServiceState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Probe indicates an expected call of Probe.
func (mr *MockStatusProberMockRecorder) Probe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probe", reflect.TypeOf((*MockStatusProber)(nil).Probe), ctx)
}

// MockIncidentRepo is a mock of IncidentRepo interface.
type MockIncidentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentRepoMockRecorder
	isgomock struct{}
}

// MockIncidentRepoMockRecorder is the mock recorder for MockIncidentRepo.
type MockIncidentRepoMockRecorder struct {
	mock *MockIncidentRepo
}

// NewMockIncidentRepo creates a new mock instance.
func NewMockIncidentRepo(ctrl *gomock.Controller) *MockIncidentRepo {
	mock := &MockIncidentRepo{ctrl: ctrl}
	mock.recorder = &MockIncidentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentRepo) EXPECT() *MockIncidentRepoMockRecorder {
	return m.recorder
}

// DailyBuckets mocks base method.
func (m *MockIncidentRepo) DailyBuckets(ctx context.Context, slug string, days int, now time.Time) ([]domain.StatusDayBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DailyBuckets", ctx, slug, days, now)
	ret0, _ := ret[0].([]domain.StatusDayBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DailyBuckets indicates an expected call of DailyBuckets.
func (mr *MockIncidentRepoMockRecorder) DailyBuckets(ctx, slug, days, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DailyBuckets", reflect.TypeOf((*MockIncidentRepo)(nil).DailyBuckets), ctx, slug, days, now)
}

// DowntimeSeconds mocks base method.
func (m *MockIncidentRepo) DowntimeSeconds(ctx context.Context, window time.Duration, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DowntimeSeconds", ctx, window, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DowntimeSeconds indicates an expected call of DowntimeSeconds.
func (mr *MockIncidentRepoMockRecorder) DowntimeSeconds(ctx, window, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DowntimeSeconds", reflect.TypeOf((*MockIncidentRepo)(nil).DowntimeSeconds), ctx, window, now)
}

// Recent mocks base method.
func (m *MockIncidentRepo) Recent(ctx context.Context, limit int) ([]domain.StatusIncident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recent", ctx, limit)
	ret0, _ := ret[0].([]domain.StatusIncident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recent indicates an expected call of Recent.
func (mr *MockIncidentRepoMockRecorder) Recent(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recent", reflect.TypeOf((*MockIncidentRepo)(nil).Recent), ctx, limit)
}
