// Code generated by MockGen. DO NOT EDIT.
// Source: users.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/users_mock.go -source users.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/admin/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// Ban mocks base method.
func (m *MockUserRepo) Ban(ctx context.Context, in domain.BanInput) (domain.AdminUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ban", ctx, in)
	ret0, _ := ret[0].(domain.AdminUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ban indicates an expected call of Ban.
func (mr *MockUserRepoMockRecorder) Ban(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ban", reflect.TypeOf((*MockUserRepo)(nil).Ban), ctx, in)
}

// Get mocks base method.
func (m *MockUserRepo) Get(ctx context.Context, id uuid.UUID) (domain.AdminUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.AdminUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserRepo)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockUserRepo) List(ctx context.Context, f domain.UserListFilter) (domain.UserPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, f)
	ret0, _ := ret[0].(domain.UserPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserRepoMockRecorder) List(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepo)(nil).List), ctx, f)
}

// Unban mocks base method.
func (m *MockUserRepo) Unban(ctx context.Context, userID, liftedBy uuid.UUID) (domain.AdminUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unban", ctx, userID, liftedBy)
	ret0, _ := ret[0].(domain.AdminUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unban indicates an expected call of Unban.
func (mr *MockUserRepoMockRecorder) Unban(ctx, userID, liftedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unban", reflect.TypeOf((*MockUserRepo)(nil).Unban), ctx, userID, liftedBy)
}
