// Code generated by MockGen. DO NOT EDIT.
// Source: code_review.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/code_review_mock.go -source code_review.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/hone/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCodeReviewGrader is a mock of CodeReviewGrader interface.
type MockCodeReviewGrader struct {
	ctrl     *gomock.Controller
	recorder *MockCodeReviewGraderMockRecorder
	isgomock struct{}
}

// MockCodeReviewGraderMockRecorder is the mock recorder for MockCodeReviewGrader.
type MockCodeReviewGraderMockRecorder struct {
	mock *MockCodeReviewGrader
}

// NewMockCodeReviewGrader creates a new mock instance.
func NewMockCodeReviewGrader(ctrl *gomock.Controller) *MockCodeReviewGrader {
	mock := &MockCodeReviewGrader{ctrl: ctrl}
	mock.recorder = &MockCodeReviewGraderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeReviewGrader) EXPECT() *MockCodeReviewGraderMockRecorder {
	return m.recorder
}

// GradeReview mocks base method.
func (m *MockCodeReviewGrader) GradeReview(ctx context.Context, in domain.GradeCodeReviewInput) (domain.CodeReviewFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GradeReview", ctx, in)
	ret0, _ := ret[0].(domain.CodeReviewFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GradeReview indicates an expected call of GradeReview.
func (mr *MockCodeReviewGraderMockRecorder) GradeReview(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GradeReview", reflect.TypeOf((*MockCodeReviewGrader)(nil).GradeReview), ctx, in)
}
