// Code generated by MockGen. DO NOT EDIT.
// Source: day_shutdown.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/day_shutdown_mock.go -source day_shutdown.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/hone/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDayShutdownRepo is a mock of DayShutdownRepo interface.
type MockDayShutdownRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDayShutdownRepoMockRecorder
	isgomock struct{}
}

// MockDayShutdownRepoMockRecorder is the mock recorder for MockDayShutdownRepo.
type MockDayShutdownRepoMockRecorder struct {
	mock *MockDayShutdownRepo
}

// NewMockDayShutdownRepo creates a new mock instance.
func NewMockDayShutdownRepo(ctrl *gomock.Controller) *MockDayShutdownRepo {
	mock := &MockDayShutdownRepo{ctrl: ctrl}
	mock.recorder = &MockDayShutdownRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDayShutdownRepo) EXPECT() *MockDayShutdownRepoMockRecorder {
	return m.recorder
}

// GetForDate mocks base method.
func (m *MockDayShutdownRepo) GetForDate(ctx context.Context, userID uuid.UUID, date time.Time) (domain.DayShutdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForDate", ctx, userID, date)
	ret0, _ := ret[0].(domain.DayShutdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForDate indicates an expected call of GetForDate.
func (mr *MockDayShutdownRepoMockRecorder) GetForDate(ctx, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForDate", reflect.TypeOf((*MockDayShutdownRepo)(nil).GetForDate), ctx, userID, date)
}

// GetMostRecent mocks base method.
func (m *MockDayShutdownRepo) GetMostRecent(ctx context.Context, userID uuid.UUID) (domain.DayShutdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMostRecent", ctx, userID)
	ret0, _ := ret[0].(domain.DayShutdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMostRecent indicates an expected call of GetMostRecent.
func (mr *MockDayShutdownRepoMockRecorder) GetMostRecent(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMostRecent", reflect.TypeOf((*MockDayShutdownRepo)(nil).GetMostRecent), ctx, userID)
}

// Upsert mocks base method.
func (m *MockDayShutdownRepo) Upsert(ctx context.Context, s domain.DayShutdown) (domain.DayShutdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, s)
	ret0, _ := ret[0].(domain.DayShutdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDayShutdownRepoMockRecorder) Upsert(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDayShutdownRepo)(nil).Upsert), ctx, s)
}
