// Code generated by MockGen. DO NOT EDIT.
// Source: listening.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/listening_mock.go -source listening.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/hone/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockListeningRepo is a mock of ListeningRepo interface.
type MockListeningRepo struct {
	ctrl     *gomock.Controller
	recorder *MockListeningRepoMockRecorder
	isgomock struct{}
}

// MockListeningRepoMockRecorder is the mock recorder for MockListeningRepo.
type MockListeningRepoMockRecorder struct {
	mock *MockListeningRepo
}

// NewMockListeningRepo creates a new mock instance.
func NewMockListeningRepo(ctrl *gomock.Controller) *MockListeningRepo {
	mock := &MockListeningRepo{ctrl: ctrl}
	mock.recorder = &MockListeningRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListeningRepo) EXPECT() *MockListeningRepoMockRecorder {
	return m.recorder
}

// ArchiveMaterial mocks base method.
func (m *MockListeningRepo) ArchiveMaterial(ctx context.Context, userID, materialID uuid.UUID, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveMaterial", ctx, userID, materialID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveMaterial indicates an expected call of ArchiveMaterial.
func (mr *MockListeningRepoMockRecorder) ArchiveMaterial(ctx, userID, materialID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveMaterial", reflect.TypeOf((*MockListeningRepo)(nil).ArchiveMaterial), ctx, userID, materialID, now)
}

// CreateMaterial mocks base method.
func (m_2 *MockListeningRepo) CreateMaterial(ctx context.Context, m domain.ListeningMaterial) (domain.ListeningMaterial, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "CreateMaterial", ctx, m)
	ret0, _ := ret[0].(domain.ListeningMaterial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMaterial indicates an expected call of CreateMaterial.
func (mr *MockListeningRepoMockRecorder) CreateMaterial(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMaterial", reflect.TypeOf((*MockListeningRepo)(nil).CreateMaterial), ctx, m)
}

// GetMaterial mocks base method.
func (m *MockListeningRepo) GetMaterial(ctx context.Context, userID, materialID uuid.UUID) (domain.ListeningMaterial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterial", ctx, userID, materialID)
	ret0, _ := ret[0].(domain.ListeningMaterial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterial indicates an expected call of GetMaterial.
func (mr *MockListeningRepoMockRecorder) GetMaterial(ctx, userID, materialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterial", reflect.TypeOf((*MockListeningRepo)(nil).GetMaterial), ctx, userID, materialID)
}

// ListMaterials mocks base method.
func (m *MockListeningRepo) ListMaterials(ctx context.Context, userID uuid.UUID, limit int) ([]domain.ListeningMaterial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMaterials", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.ListeningMaterial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMaterials indicates an expected call of ListMaterials.
func (mr *MockListeningRepoMockRecorder) ListMaterials(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMaterials", reflect.TypeOf((*MockListeningRepo)(nil).ListMaterials), ctx, userID, limit)
}

// MockYouTubeFetcher is a mock of YouTubeFetcher interface.
type MockYouTubeFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockYouTubeFetcherMockRecorder
	isgomock struct{}
}

// MockYouTubeFetcherMockRecorder is the mock recorder for MockYouTubeFetcher.
type MockYouTubeFetcherMockRecorder struct {
	mock *MockYouTubeFetcher
}

// NewMockYouTubeFetcher creates a new mock instance.
func NewMockYouTubeFetcher(ctrl *gomock.Controller) *MockYouTubeFetcher {
	mock := &MockYouTubeFetcher{ctrl: ctrl}
	mock.recorder = &MockYouTubeFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYouTubeFetcher) EXPECT() *MockYouTubeFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockYouTubeFetcher) Fetch(ctx context.Context, url, languageHint string) (domain.YouTubeFetchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, url, languageHint)
	ret0, _ := ret[0].(domain.YouTubeFetchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockYouTubeFetcherMockRecorder) Fetch(ctx, url, languageHint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockYouTubeFetcher)(nil).Fetch), ctx, url, languageHint)
}
