// Code generated by MockGen. DO NOT EDIT.
// Source: memory_hook.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/memory_hook_mock.go -source memory_hook.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMemoryHook is a mock of MemoryHook interface.
type MockMemoryHook struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryHookMockRecorder
	isgomock struct{}
}

// MockMemoryHookMockRecorder is the mock recorder for MockMemoryHook.
type MockMemoryHookMockRecorder struct {
	mock *MockMemoryHook
}

// NewMockMemoryHook creates a new mock instance.
func NewMockMemoryHook(ctrl *gomock.Controller) *MockMemoryHook {
	mock := &MockMemoryHook{ctrl: ctrl}
	mock.recorder = &MockMemoryHookMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryHook) EXPECT() *MockMemoryHookMockRecorder {
	return m.recorder
}

// OnDailyNoteSaved mocks base method.
func (m *MockMemoryHook) OnDailyNoteSaved(ctx context.Context, userID, noteID uuid.UUID, title, body600 string, occurredAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnDailyNoteSaved", ctx, userID, noteID, title, body600, occurredAt)
}

// OnDailyNoteSaved indicates an expected call of OnDailyNoteSaved.
func (mr *MockMemoryHookMockRecorder) OnDailyNoteSaved(ctx, userID, noteID, title, body600, occurredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDailyNoteSaved", reflect.TypeOf((*MockMemoryHook)(nil).OnDailyNoteSaved), ctx, userID, noteID, title, body600, occurredAt)
}

// OnFocusSessionDone mocks base method.
func (m *MockMemoryHook) OnFocusSessionDone(ctx context.Context, userID uuid.UUID, pinnedTitle string, secondsFocused int, planItemID string, completedPomodoros int, occurredAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnFocusSessionDone", ctx, userID, pinnedTitle, secondsFocused, planItemID, completedPomodoros, occurredAt)
}

// OnFocusSessionDone indicates an expected call of OnFocusSessionDone.
func (mr *MockMemoryHookMockRecorder) OnFocusSessionDone(ctx, userID, pinnedTitle, secondsFocused, planItemID, completedPomodoros, occurredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnFocusSessionDone", reflect.TypeOf((*MockMemoryHook)(nil).OnFocusSessionDone), ctx, userID, pinnedTitle, secondsFocused, planItemID, completedPomodoros, occurredAt)
}

// OnNoteCreated mocks base method.
func (m *MockMemoryHook) OnNoteCreated(ctx context.Context, userID, noteID uuid.UUID, title, body200 string, occurredAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnNoteCreated", ctx, userID, noteID, title, body200, occurredAt)
}

// OnNoteCreated indicates an expected call of OnNoteCreated.
func (mr *MockMemoryHookMockRecorder) OnNoteCreated(ctx, userID, noteID, title, body200, occurredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnNoteCreated", reflect.TypeOf((*MockMemoryHook)(nil).OnNoteCreated), ctx, userID, noteID, title, body200, occurredAt)
}

// OnPlanCompleted mocks base method.
func (m *MockMemoryHook) OnPlanCompleted(ctx context.Context, userID uuid.UUID, title, skillKey string, occurredAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnPlanCompleted", ctx, userID, title, skillKey, occurredAt)
}

// OnPlanCompleted indicates an expected call of OnPlanCompleted.
func (mr *MockMemoryHookMockRecorder) OnPlanCompleted(ctx, userID, title, skillKey, occurredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPlanCompleted", reflect.TypeOf((*MockMemoryHook)(nil).OnPlanCompleted), ctx, userID, title, skillKey, occurredAt)
}

// OnPlanSkipped mocks base method.
func (m *MockMemoryHook) OnPlanSkipped(ctx context.Context, userID uuid.UUID, title, skillKey string, occurredAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnPlanSkipped", ctx, userID, title, skillKey, occurredAt)
}

// OnPlanSkipped indicates an expected call of OnPlanSkipped.
func (mr *MockMemoryHookMockRecorder) OnPlanSkipped(ctx, userID, title, skillKey, occurredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPlanSkipped", reflect.TypeOf((*MockMemoryHook)(nil).OnPlanSkipped), ctx, userID, title, skillKey, occurredAt)
}

// OnReflectionAdded mocks base method.
func (m *MockMemoryHook) OnReflectionAdded(ctx context.Context, userID uuid.UUID, reflection, planItemID string, seconds int, occurredAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnReflectionAdded", ctx, userID, reflection, planItemID, seconds, occurredAt)
}

// OnReflectionAdded indicates an expected call of OnReflectionAdded.
func (mr *MockMemoryHookMockRecorder) OnReflectionAdded(ctx, userID, reflection, planItemID, seconds, occurredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnReflectionAdded", reflect.TypeOf((*MockMemoryHook)(nil).OnReflectionAdded), ctx, userID, reflection, planItemID, seconds, occurredAt)
}

// OnStandupRecorded mocks base method.
func (m *MockMemoryHook) OnStandupRecorded(ctx context.Context, userID uuid.UUID, yesterday, today, blockers string, occurredAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStandupRecorded", ctx, userID, yesterday, today, blockers, occurredAt)
}

// OnStandupRecorded indicates an expected call of OnStandupRecorded.
func (mr *MockMemoryHookMockRecorder) OnStandupRecorded(ctx, userID, yesterday, today, blockers, occurredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStandupRecorded", reflect.TypeOf((*MockMemoryHook)(nil).OnStandupRecorded), ctx, userID, yesterday, today, blockers, occurredAt)
}
