// Code generated by MockGen. DO NOT EDIT.
// Source: reading.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/reading_mock.go -source reading.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/hone/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReadingRepo is a mock of ReadingRepo interface.
type MockReadingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockReadingRepoMockRecorder
	isgomock struct{}
}

// MockReadingRepoMockRecorder is the mock recorder for MockReadingRepo.
type MockReadingRepoMockRecorder struct {
	mock *MockReadingRepo
}

// NewMockReadingRepo creates a new mock instance.
func NewMockReadingRepo(ctrl *gomock.Controller) *MockReadingRepo {
	mock := &MockReadingRepo{ctrl: ctrl}
	mock.recorder = &MockReadingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadingRepo) EXPECT() *MockReadingRepoMockRecorder {
	return m.recorder
}

// AdvanceVocab mocks base method.
func (m *MockReadingRepo) AdvanceVocab(ctx context.Context, userID uuid.UUID, word string, correct bool, now time.Time) (domain.VocabEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdvanceVocab", ctx, userID, word, correct, now)
	ret0, _ := ret[0].(domain.VocabEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdvanceVocab indicates an expected call of AdvanceVocab.
func (mr *MockReadingRepoMockRecorder) AdvanceVocab(ctx, userID, word, correct, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdvanceVocab", reflect.TypeOf((*MockReadingRepo)(nil).AdvanceVocab), ctx, userID, word, correct, now)
}

// ArchiveMaterial mocks base method.
func (m *MockReadingRepo) ArchiveMaterial(ctx context.Context, userID, materialID uuid.UUID, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveMaterial", ctx, userID, materialID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveMaterial indicates an expected call of ArchiveMaterial.
func (mr *MockReadingRepoMockRecorder) ArchiveMaterial(ctx, userID, materialID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveMaterial", reflect.TypeOf((*MockReadingRepo)(nil).ArchiveMaterial), ctx, userID, materialID, now)
}

// CreateMaterial mocks base method.
func (m_2 *MockReadingRepo) CreateMaterial(ctx context.Context, m domain.ReadingMaterial) (domain.ReadingMaterial, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "CreateMaterial", ctx, m)
	ret0, _ := ret[0].(domain.ReadingMaterial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMaterial indicates an expected call of CreateMaterial.
func (mr *MockReadingRepoMockRecorder) CreateMaterial(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMaterial", reflect.TypeOf((*MockReadingRepo)(nil).CreateMaterial), ctx, m)
}

// EndSession mocks base method.
func (m *MockReadingRepo) EndSession(ctx context.Context, userID, sessionID uuid.UUID, charsRead int, summaryMD string, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndSession", ctx, userID, sessionID, charsRead, summaryMD, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndSession indicates an expected call of EndSession.
func (mr *MockReadingRepoMockRecorder) EndSession(ctx, userID, sessionID, charsRead, summaryMD, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndSession", reflect.TypeOf((*MockReadingRepo)(nil).EndSession), ctx, userID, sessionID, charsRead, summaryMD, now)
}

// GetMaterial mocks base method.
func (m *MockReadingRepo) GetMaterial(ctx context.Context, userID, materialID uuid.UUID) (domain.ReadingMaterial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterial", ctx, userID, materialID)
	ret0, _ := ret[0].(domain.ReadingMaterial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterial indicates an expected call of GetMaterial.
func (mr *MockReadingRepoMockRecorder) GetMaterial(ctx, userID, materialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterial", reflect.TypeOf((*MockReadingRepo)(nil).GetMaterial), ctx, userID, materialID)
}

// GetSession mocks base method.
func (m *MockReadingRepo) GetSession(ctx context.Context, userID, sessionID uuid.UUID) (domain.ReadingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, userID, sessionID)
	ret0, _ := ret[0].(domain.ReadingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockReadingRepoMockRecorder) GetSession(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockReadingRepo)(nil).GetSession), ctx, userID, sessionID)
}

// ListMaterials mocks base method.
func (m *MockReadingRepo) ListMaterials(ctx context.Context, userID uuid.UUID, limit int) ([]domain.ReadingMaterial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMaterials", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.ReadingMaterial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMaterials indicates an expected call of ListMaterials.
func (mr *MockReadingRepoMockRecorder) ListMaterials(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMaterials", reflect.TypeOf((*MockReadingRepo)(nil).ListMaterials), ctx, userID, limit)
}

// ListVocabBySourceMaterial mocks base method.
func (m *MockReadingRepo) ListVocabBySourceMaterial(ctx context.Context, userID, materialID uuid.UUID, limit int) ([]domain.VocabEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVocabBySourceMaterial", ctx, userID, materialID, limit)
	ret0, _ := ret[0].([]domain.VocabEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVocabBySourceMaterial indicates an expected call of ListVocabBySourceMaterial.
func (mr *MockReadingRepoMockRecorder) ListVocabBySourceMaterial(ctx, userID, materialID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVocabBySourceMaterial", reflect.TypeOf((*MockReadingRepo)(nil).ListVocabBySourceMaterial), ctx, userID, materialID, limit)
}

// ListVocabDue mocks base method.
func (m *MockReadingRepo) ListVocabDue(ctx context.Context, userID uuid.UUID, now time.Time, limit int) ([]domain.VocabEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVocabDue", ctx, userID, now, limit)
	ret0, _ := ret[0].([]domain.VocabEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVocabDue indicates an expected call of ListVocabDue.
func (mr *MockReadingRepoMockRecorder) ListVocabDue(ctx, userID, now, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVocabDue", reflect.TypeOf((*MockReadingRepo)(nil).ListVocabDue), ctx, userID, now, limit)
}

// SetAISummaryScore mocks base method.
func (m *MockReadingRepo) SetAISummaryScore(ctx context.Context, userID, sessionID uuid.UUID, score int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAISummaryScore", ctx, userID, sessionID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAISummaryScore indicates an expected call of SetAISummaryScore.
func (mr *MockReadingRepoMockRecorder) SetAISummaryScore(ctx, userID, sessionID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAISummaryScore", reflect.TypeOf((*MockReadingRepo)(nil).SetAISummaryScore), ctx, userID, sessionID, score)
}

// StartSession mocks base method.
func (m *MockReadingRepo) StartSession(ctx context.Context, userID, materialID uuid.UUID) (domain.ReadingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSession", ctx, userID, materialID)
	ret0, _ := ret[0].(domain.ReadingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartSession indicates an expected call of StartSession.
func (mr *MockReadingRepoMockRecorder) StartSession(ctx, userID, materialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockReadingRepo)(nil).StartSession), ctx, userID, materialID)
}

// UpdateBookProgress mocks base method.
func (m *MockReadingRepo) UpdateBookProgress(ctx context.Context, userID, materialID uuid.UUID, chapter, total *int) (domain.ReadingMaterial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookProgress", ctx, userID, materialID, chapter, total)
	ret0, _ := ret[0].(domain.ReadingMaterial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBookProgress indicates an expected call of UpdateBookProgress.
func (mr *MockReadingRepoMockRecorder) UpdateBookProgress(ctx, userID, materialID, chapter, total any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookProgress", reflect.TypeOf((*MockReadingRepo)(nil).UpdateBookProgress), ctx, userID, materialID, chapter, total)
}

// UpsertVocab mocks base method.
func (m *MockReadingRepo) UpsertVocab(ctx context.Context, e domain.VocabEntry) (domain.VocabEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertVocab", ctx, e)
	ret0, _ := ret[0].(domain.VocabEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertVocab indicates an expected call of UpsertVocab.
func (mr *MockReadingRepoMockRecorder) UpsertVocab(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertVocab", reflect.TypeOf((*MockReadingRepo)(nil).UpsertVocab), ctx, e)
}

// MockSummaryGrader is a mock of SummaryGrader interface.
type MockSummaryGrader struct {
	ctrl     *gomock.Controller
	recorder *MockSummaryGraderMockRecorder
	isgomock struct{}
}

// MockSummaryGraderMockRecorder is the mock recorder for MockSummaryGrader.
type MockSummaryGraderMockRecorder struct {
	mock *MockSummaryGrader
}

// NewMockSummaryGrader creates a new mock instance.
func NewMockSummaryGrader(ctrl *gomock.Controller) *MockSummaryGrader {
	mock := &MockSummaryGrader{ctrl: ctrl}
	mock.recorder = &MockSummaryGraderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummaryGrader) EXPECT() *MockSummaryGraderMockRecorder {
	return m.recorder
}

// GradeSummary mocks base method.
func (m *MockSummaryGrader) GradeSummary(ctx context.Context, in domain.GradeSummaryInput) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GradeSummary", ctx, in)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GradeSummary indicates an expected call of GradeSummary.
func (mr *MockSummaryGraderMockRecorder) GradeSummary(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GradeSummary", reflect.TypeOf((*MockSummaryGrader)(nil).GradeSummary), ctx, in)
}
