// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package seasondb

import (
	"context"
)

type Querier interface {
	// season queries consumed by sqlc (emitted into services/season/infra/db).
	GetCurrentSeason(ctx context.Context) (Season, error)
	GetSeasonProgress(ctx context.Context, arg GetSeasonProgressParams) (SeasonProgress, error)
	// Atomic SP bump. Creates the row at (points=delta, tier=0) when missing.
	// Returns the resulting points total so the caller can recompute the tier.
	IncrementSeasonPoints(ctx context.Context, arg IncrementSeasonPointsParams) (int32, error)
	UpdateSeasonTier(ctx context.Context, arg UpdateSeasonTierParams) error
	UpsertSeasonProgress(ctx context.Context, arg UpsertSeasonProgressParams) error
}

var _ Querier = (*Queries)(nil)
