// Code generated by MockGen. DO NOT EDIT.
// Source: log_resource.go
//
// Generated by this command:
//
//	mockgen -package app -destination log_resource_mock_test.go -source log_resource.go ResourceLogRepo
//

// Package app is a generated GoMock package.
package app

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResourceLogRepo is a mock of ResourceLogRepo interface.
type MockResourceLogRepo struct {
	ctrl     *gomock.Controller
	recorder *MockResourceLogRepoMockRecorder
	isgomock struct{}
}

// MockResourceLogRepoMockRecorder is the mock recorder for MockResourceLogRepo.
type MockResourceLogRepoMockRecorder struct {
	mock *MockResourceLogRepo
}

// NewMockResourceLogRepo creates a new mock instance.
func NewMockResourceLogRepo(ctrl *gomock.Controller) *MockResourceLogRepo {
	mock := &MockResourceLogRepo{ctrl: ctrl}
	mock.recorder = &MockResourceLogRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceLogRepo) EXPECT() *MockResourceLogRepoMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockResourceLogRepo) Insert(ctx context.Context, in ResourceLogEntry) (ResourceLogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, in)
	ret0, _ := ret[0].(ResourceLogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockResourceLogRepoMockRecorder) Insert(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockResourceLogRepo)(nil).Insert), ctx, in)
}
