// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ai_mockdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendMockMessage(ctx context.Context, arg AppendMockMessageParams) (MockMessage, error)
	// Queries consumed by sqlc; mirror hand-rolled pgx in infra/postgres.go.
	// CRITICAL: solution_hint is ONLY selected by GetTaskWithHint — never by any
	// query whose result is shown to the client.
	// RETURNING * so sqlc emits the canonical MockSession row type (no Row alias).
	CreateMockSession(ctx context.Context, arg CreateMockSessionParams) (MockSession, error)
	// Phase-4 ADR-001 (Wave 3) — drives copilot.CheckBlock. Returns the user's
	// live mock_sessions row when ai_assist=FALSE (strict mode). When the row
	// exists, copilot.Analyze must refuse the LLM call. Cross-service read by
	// design — copilot owns the gate logic but leans on ai_mock's table.
	GetActiveBlockingMockSession(ctx context.Context, userID pgtype.UUID) (GetActiveBlockingMockSessionRow, error)
	// companies перешёл на mock-interview shape (см. 00043). difficulty —
	// больше не колонка companies; для mock-flow'а сложность берётся с уровня
	// mock_tasks / pipeline_stages. Возвращаем basic identity (id+name)
	// + slug чтобы caller мог отрисовать logo по slug'у через статику.
	GetCompanyForMock(ctx context.Context, id pgtype.UUID) (GetCompanyForMockRow, error)
	GetMockSession(ctx context.Context, id pgtype.UUID) (MockSession, error)
	// Same caveat as PickTaskForSection — private to ai_mock's prompt builder.
	GetTaskWithHint(ctx context.Context, id pgtype.UUID) (GetTaskWithHintRow, error)
	GetUserSubscription(ctx context.Context, userID pgtype.UUID) (string, error)
	ListAllMockMessages(ctx context.Context, sessionID pgtype.UUID) ([]MockMessage, error)
	ListLastMockMessages(ctx context.Context, arg ListLastMockMessagesParams) ([]MockMessage, error)
	// Internal: returns the task PLUS solution_hint for LLM-only consumption.
	// Client-facing call sites MUST go through the domain's TaskRepo.PickForSession
	// which drops the hint via ToPublic before reaching any DTO.
	//
	// W13 audit: `ORDER BY random()` is normally an anti-pattern because it sorts
	// every matching row. Here it's acceptable because:
	//   * idx_tasks_section_diff is a *partial* index (WHERE is_active) on
	//     (section, difficulty), so the planner walks a tiny range (~10-100 rows
	//     per bucket given the curated catalog).
	//   * Called once per mock-session start (not per turn), so even O(N) sort
	//     is cheap at current N.
	// Revisit if any (section, difficulty) bucket grows past ~thousand active
	// rows — at that point switch to a `OFFSET floor(random()*N) LIMIT 1` two-step
	// with bucket-count cached, or add a `pickable_id INT8` random key column.
	PickTaskForSection(ctx context.Context, arg PickTaskForSectionParams) (PickTaskForSectionRow, error)
	UpdateMockSessionReport(ctx context.Context, arg UpdateMockSessionReportParams) (int64, error)
	// Вызывается фоновым compaction.Worker после суммаризации старых turns.
	// См. backend/shared/pkg/compaction/worker.go. Пишем атомарно поверх
	// любого предыдущего значения — решение о запуске принимает воркер.
	// summary_model — Phase II attribution.
	UpdateMockSessionRunningSummary(ctx context.Context, arg UpdateMockSessionRunningSummaryParams) (int64, error)
	UpdateMockSessionStatus(ctx context.Context, arg UpdateMockSessionStatusParams) (int64, error)
	UpdateMockSessionStress(ctx context.Context, arg UpdateMockSessionStressParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
