// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dailydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignDailyKata(ctx context.Context, arg AssignDailyKataParams) (AssignDailyKataRow, error)
	CreateAutopsy(ctx context.Context, arg CreateAutopsyParams) (InterviewAutopsy, error)
	GetActiveCalendar(ctx context.Context, arg GetActiveCalendarParams) (GetActiveCalendarRow, error)
	GetAutopsy(ctx context.Context, id pgtype.UUID) (InterviewAutopsy, error)
	GetDailyKata(ctx context.Context, arg GetDailyKataParams) (GetDailyKataRow, error)
	GetStreak(ctx context.Context, userID pgtype.UUID) (GetStreakRow, error)
	GetTaskPublic(ctx context.Context, id pgtype.UUID) (GetTaskPublicRow, error)
	// Queries consumed by sqlc; mirror hand-rolled pgx in infra/postgres.go.
	// CRITICAL: solution_hint is NEVER selected in the TaskPublic-shaped queries.
	ListActiveTasks(ctx context.Context, arg ListActiveTasksParams) ([]ListActiveTasksRow, error)
	ListKataHistory(ctx context.Context, arg ListKataHistoryParams) ([]ListKataHistoryRow, error)
	MarkAutopsyReady(ctx context.Context, arg MarkAutopsyReadyParams) (int64, error)
	MarkDailyKataSubmitted(ctx context.Context, arg MarkDailyKataSubmittedParams) (int64, error)
	UpsertCalendar(ctx context.Context, arg UpsertCalendarParams) (UpsertCalendarRow, error)
	UpsertStreak(ctx context.Context, arg UpsertStreakParams) error
	WeakestSkillNode(ctx context.Context, userID pgtype.UUID) (WeakestSkillNodeRow, error)
}

var _ Querier = (*Queries)(nil)
