// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_native.sql

package ai_nativedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNativeSession = `-- name: CreateNativeSession :one

INSERT INTO native_sessions (
    user_id, task_id, section, difficulty, llm_model
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, task_id, section, difficulty, llm_model,
          context_score, verification_score, judgment_score, delivery_score,
          started_at, finished_at
`

type CreateNativeSessionParams struct {
	UserID     pgtype.UUID
	TaskID     pgtype.UUID
	Section    string
	Difficulty string
	LlmModel   pgtype.Text
}

// Queries consumed by sqlc; mirror hand-rolled pgx in infra/postgres.go.
// CRITICAL: solution_hint is ONLY selected by GetNativeTaskWithHint — never
// by any query whose result is shown to the client.
func (q *Queries) CreateNativeSession(ctx context.Context, arg CreateNativeSessionParams) (NativeSession, error) {
	row := q.db.QueryRow(ctx, createNativeSession,
		arg.UserID,
		arg.TaskID,
		arg.Section,
		arg.Difficulty,
		arg.LlmModel,
	)
	var i NativeSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Section,
		&i.Difficulty,
		&i.LlmModel,
		&i.ContextScore,
		&i.VerificationScore,
		&i.JudgmentScore,
		&i.DeliveryScore,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getNativeProvenance = `-- name: GetNativeProvenance :one
SELECT id, session_id, parent_id, kind, snippet, ai_prompt,
       has_hallucination_trap, verified_at, created_at
  FROM native_provenance
 WHERE id = $1
`

func (q *Queries) GetNativeProvenance(ctx context.Context, id pgtype.UUID) (NativeProvenance, error) {
	row := q.db.QueryRow(ctx, getNativeProvenance, id)
	var i NativeProvenance
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.Kind,
		&i.Snippet,
		&i.AiPrompt,
		&i.HasHallucinationTrap,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNativeSession = `-- name: GetNativeSession :one
SELECT id, user_id, task_id, section, difficulty, llm_model,
       context_score, verification_score, judgment_score, delivery_score,
       started_at, finished_at
  FROM native_sessions
 WHERE id = $1
`

func (q *Queries) GetNativeSession(ctx context.Context, id pgtype.UUID) (NativeSession, error) {
	row := q.db.QueryRow(ctx, getNativeSession, id)
	var i NativeSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Section,
		&i.Difficulty,
		&i.LlmModel,
		&i.ContextScore,
		&i.VerificationScore,
		&i.JudgmentScore,
		&i.DeliveryScore,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getNativeTaskWithHint = `-- name: GetNativeTaskWithHint :one
SELECT id, slug, title_ru, description_ru, difficulty, section, solution_hint
  FROM tasks
 WHERE id = $1
`

type GetNativeTaskWithHintRow struct {
	ID            pgtype.UUID
	Slug          string
	TitleRu       string
	DescriptionRu string
	Difficulty    string
	Section       string
	SolutionHint  pgtype.Text
}

func (q *Queries) GetNativeTaskWithHint(ctx context.Context, id pgtype.UUID) (GetNativeTaskWithHintRow, error) {
	row := q.db.QueryRow(ctx, getNativeTaskWithHint, id)
	var i GetNativeTaskWithHintRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleRu,
		&i.DescriptionRu,
		&i.Difficulty,
		&i.Section,
		&i.SolutionHint,
	)
	return i, err
}

const getNativeUserSubscription = `-- name: GetNativeUserSubscription :one
SELECT plan
  FROM subscriptions
 WHERE user_id = $1
`

func (q *Queries) GetNativeUserSubscription(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getNativeUserSubscription, userID)
	var plan string
	err := row.Scan(&plan)
	return plan, err
}

const insertNativeProvenance = `-- name: InsertNativeProvenance :one
INSERT INTO native_provenance (
    session_id, parent_id, kind, snippet, ai_prompt, has_hallucination_trap
) VALUES ($1, $2, $3, $4, NULLIF($5::text, ''), $6)
RETURNING id, session_id, parent_id, kind, snippet, ai_prompt,
          has_hallucination_trap, verified_at, created_at
`

type InsertNativeProvenanceParams struct {
	SessionID            pgtype.UUID
	ParentID             pgtype.UUID
	Kind                 string
	Snippet              string
	Column5              string
	HasHallucinationTrap bool
}

func (q *Queries) InsertNativeProvenance(ctx context.Context, arg InsertNativeProvenanceParams) (NativeProvenance, error) {
	row := q.db.QueryRow(ctx, insertNativeProvenance,
		arg.SessionID,
		arg.ParentID,
		arg.Kind,
		arg.Snippet,
		arg.Column5,
		arg.HasHallucinationTrap,
	)
	var i NativeProvenance
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.Kind,
		&i.Snippet,
		&i.AiPrompt,
		&i.HasHallucinationTrap,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNativeProvenance = `-- name: ListNativeProvenance :many
SELECT id, session_id, parent_id, kind, snippet, ai_prompt,
       has_hallucination_trap, verified_at, created_at
  FROM native_provenance
 WHERE session_id = $1
 ORDER BY created_at ASC
`

func (q *Queries) ListNativeProvenance(ctx context.Context, sessionID pgtype.UUID) ([]NativeProvenance, error) {
	rows, err := q.db.Query(ctx, listNativeProvenance, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NativeProvenance{}
	for rows.Next() {
		var i NativeProvenance
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentID,
			&i.Kind,
			&i.Snippet,
			&i.AiPrompt,
			&i.HasHallucinationTrap,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNativeProvenanceVerified = `-- name: MarkNativeProvenanceVerified :execrows
UPDATE native_provenance
   SET kind        = $2,
       verified_at = now()
 WHERE id = $1
`

type MarkNativeProvenanceVerifiedParams struct {
	ID   pgtype.UUID
	Kind string
}

func (q *Queries) MarkNativeProvenanceVerified(ctx context.Context, arg MarkNativeProvenanceVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNativeProvenanceVerified, arg.ID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNativeSessionFinished = `-- name: MarkNativeSessionFinished :execrows
UPDATE native_sessions
   SET context_score      = $2,
       verification_score = $3,
       judgment_score     = $4,
       delivery_score     = $5,
       finished_at        = now()
 WHERE id = $1
   AND finished_at IS NULL
`

type MarkNativeSessionFinishedParams struct {
	ID                pgtype.UUID
	ContextScore      int32
	VerificationScore int32
	JudgmentScore     int32
	DeliveryScore     int32
}

func (q *Queries) MarkNativeSessionFinished(ctx context.Context, arg MarkNativeSessionFinishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNativeSessionFinished,
		arg.ID,
		arg.ContextScore,
		arg.VerificationScore,
		arg.JudgmentScore,
		arg.DeliveryScore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pickNativeTask = `-- name: PickNativeTask :one
SELECT id, slug, title_ru, description_ru, difficulty, section, solution_hint
  FROM tasks
 WHERE is_active = true AND section = $1 AND difficulty = $2
 ORDER BY random()
 LIMIT 1
`

type PickNativeTaskParams struct {
	Section    string
	Difficulty string
}

type PickNativeTaskRow struct {
	ID            pgtype.UUID
	Slug          string
	TitleRu       string
	DescriptionRu string
	Difficulty    string
	Section       string
	SolutionHint  pgtype.Text
}

// Internal: returns TaskWithHint. See ai_mock's equivalent for the same
// information-leak caveat.
func (q *Queries) PickNativeTask(ctx context.Context, arg PickNativeTaskParams) (PickNativeTaskRow, error) {
	row := q.db.QueryRow(ctx, pickNativeTask, arg.Section, arg.Difficulty)
	var i PickNativeTaskRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleRu,
		&i.DescriptionRu,
		&i.Difficulty,
		&i.Section,
		&i.SolutionHint,
	)
	return i, err
}

const updateNativeSessionScores = `-- name: UpdateNativeSessionScores :execrows
UPDATE native_sessions
   SET context_score      = $2,
       verification_score = $3,
       judgment_score     = $4,
       delivery_score     = $5
 WHERE id = $1
`

type UpdateNativeSessionScoresParams struct {
	ID                pgtype.UUID
	ContextScore      int32
	VerificationScore int32
	JudgmentScore     int32
	DeliveryScore     int32
}

func (q *Queries) UpdateNativeSessionScores(ctx context.Context, arg UpdateNativeSessionScoresParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNativeSessionScores,
		arg.ID,
		arg.ContextScore,
		arg.VerificationScore,
		arg.JudgmentScore,
		arg.DeliveryScore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
