// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/repo_mock.go -source repo.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/editor/domain"
	enums "druz9/shared/enums"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCodeRunner is a mock of CodeRunner interface.
type MockCodeRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCodeRunnerMockRecorder
	isgomock struct{}
}

// MockCodeRunnerMockRecorder is the mock recorder for MockCodeRunner.
type MockCodeRunnerMockRecorder struct {
	mock *MockCodeRunner
}

// NewMockCodeRunner creates a new mock instance.
func NewMockCodeRunner(ctrl *gomock.Controller) *MockCodeRunner {
	mock := &MockCodeRunner{ctrl: ctrl}
	mock.recorder = &MockCodeRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeRunner) EXPECT() *MockCodeRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockCodeRunner) Run(ctx context.Context, code string, language enums.Language) (domain.RunResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, code, language)
	ret0, _ := ret[0].(domain.RunResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockCodeRunnerMockRecorder) Run(ctx, code, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCodeRunner)(nil).Run), ctx, code, language)
}

// MockRoomRepo is a mock of RoomRepo interface.
type MockRoomRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRepoMockRecorder
	isgomock struct{}
}

// MockRoomRepoMockRecorder is the mock recorder for MockRoomRepo.
type MockRoomRepoMockRecorder struct {
	mock *MockRoomRepo
}

// NewMockRoomRepo creates a new mock instance.
func NewMockRoomRepo(ctrl *gomock.Controller) *MockRoomRepo {
	mock := &MockRoomRepo{ctrl: ctrl}
	mock.recorder = &MockRoomRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRepo) EXPECT() *MockRoomRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomRepo) Create(ctx context.Context, r domain.Room) (domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRoomRepoMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomRepo)(nil).Create), ctx, r)
}

// ExtendExpires mocks base method.
func (m *MockRoomRepo) ExtendExpires(ctx context.Context, id uuid.UUID, newExpires time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendExpires", ctx, id, newExpires)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtendExpires indicates an expected call of ExtendExpires.
func (mr *MockRoomRepoMockRecorder) ExtendExpires(ctx, id, newExpires any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendExpires", reflect.TypeOf((*MockRoomRepo)(nil).ExtendExpires), ctx, id, newExpires)
}

// Get mocks base method.
func (m *MockRoomRepo) Get(ctx context.Context, id uuid.UUID) (domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoomRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoomRepo)(nil).Get), ctx, id)
}

// SetVisibility mocks base method.
func (m *MockRoomRepo) SetVisibility(ctx context.Context, id uuid.UUID, v domain.Visibility) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVisibility", ctx, id, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVisibility indicates an expected call of SetVisibility.
func (mr *MockRoomRepoMockRecorder) SetVisibility(ctx, id, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVisibility", reflect.TypeOf((*MockRoomRepo)(nil).SetVisibility), ctx, id, v)
}

// UpdateFreeze mocks base method.
func (m *MockRoomRepo) UpdateFreeze(ctx context.Context, id uuid.UUID, frozen bool) (domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFreeze", ctx, id, frozen)
	ret0, _ := ret[0].(domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFreeze indicates an expected call of UpdateFreeze.
func (mr *MockRoomRepoMockRecorder) UpdateFreeze(ctx, id, frozen any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFreeze", reflect.TypeOf((*MockRoomRepo)(nil).UpdateFreeze), ctx, id, frozen)
}

// MockParticipantRepo is a mock of ParticipantRepo interface.
type MockParticipantRepo struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantRepoMockRecorder
	isgomock struct{}
}

// MockParticipantRepoMockRecorder is the mock recorder for MockParticipantRepo.
type MockParticipantRepoMockRecorder struct {
	mock *MockParticipantRepo
}

// NewMockParticipantRepo creates a new mock instance.
func NewMockParticipantRepo(ctrl *gomock.Controller) *MockParticipantRepo {
	mock := &MockParticipantRepo{ctrl: ctrl}
	mock.recorder = &MockParticipantRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantRepo) EXPECT() *MockParticipantRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockParticipantRepo) Add(ctx context.Context, p domain.Participant) (domain.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, p)
	ret0, _ := ret[0].(domain.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockParticipantRepoMockRecorder) Add(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockParticipantRepo)(nil).Add), ctx, p)
}

// GetRole mocks base method.
func (m *MockParticipantRepo) GetRole(ctx context.Context, roomID, userID uuid.UUID) (enums.EditorRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, roomID, userID)
	ret0, _ := ret[0].(enums.EditorRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockParticipantRepoMockRecorder) GetRole(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockParticipantRepo)(nil).GetRole), ctx, roomID, userID)
}

// List mocks base method.
func (m *MockParticipantRepo) List(ctx context.Context, roomID uuid.UUID) ([]domain.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, roomID)
	ret0, _ := ret[0].([]domain.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockParticipantRepoMockRecorder) List(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockParticipantRepo)(nil).List), ctx, roomID)
}

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
	isgomock struct{}
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockTaskRepo) GetByID(ctx context.Context, id uuid.UUID) (domain.TaskPublic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.TaskPublic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepo)(nil).GetByID), ctx, id)
}

// MockReplayUploader is a mock of ReplayUploader interface.
type MockReplayUploader struct {
	ctrl     *gomock.Controller
	recorder *MockReplayUploaderMockRecorder
	isgomock struct{}
}

// MockReplayUploaderMockRecorder is the mock recorder for MockReplayUploader.
type MockReplayUploaderMockRecorder struct {
	mock *MockReplayUploader
}

// NewMockReplayUploader creates a new mock instance.
func NewMockReplayUploader(ctrl *gomock.Controller) *MockReplayUploader {
	mock := &MockReplayUploader{ctrl: ctrl}
	mock.recorder = &MockReplayUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplayUploader) EXPECT() *MockReplayUploaderMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockReplayUploader) Upload(ctx context.Context, roomID uuid.UUID, payload []byte) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, roomID, payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Upload indicates an expected call of Upload.
func (mr *MockReplayUploaderMockRecorder) Upload(ctx, roomID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockReplayUploader)(nil).Upload), ctx, roomID, payload)
}

// MockTokenVerifier is a mock of TokenVerifier interface.
type MockTokenVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockTokenVerifierMockRecorder
	isgomock struct{}
}

// MockTokenVerifierMockRecorder is the mock recorder for MockTokenVerifier.
type MockTokenVerifierMockRecorder struct {
	mock *MockTokenVerifier
}

// NewMockTokenVerifier creates a new mock instance.
func NewMockTokenVerifier(ctrl *gomock.Controller) *MockTokenVerifier {
	mock := &MockTokenVerifier{ctrl: ctrl}
	mock.recorder = &MockTokenVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenVerifier) EXPECT() *MockTokenVerifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockTokenVerifier) Verify(raw string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", raw)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockTokenVerifierMockRecorder) Verify(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockTokenVerifier)(nil).Verify), raw)
}

// VerifyScoped mocks base method.
func (m *MockTokenVerifier) VerifyScoped(raw, expectedScope string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyScoped", raw, expectedScope)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyScoped indicates an expected call of VerifyScoped.
func (mr *MockTokenVerifierMockRecorder) VerifyScoped(raw, expectedScope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyScoped", reflect.TypeOf((*MockTokenVerifier)(nil).VerifyScoped), raw, expectedScope)
}
