#!/bin/bash
# Generate per-service .go-arch-lint.yml based on which dirs actually exist.
set -e
SERVICES=/Users/sedorofeevd/Desktop/druzya/backend/services

for svc in "$SERVICES"/*/; do
  name=$(basename "$svc")
  cfg="$svc.go-arch-lint.yml"

  has_domain=$([ -d "$svc/domain" ] && echo y || echo n)
  has_mocks=$([ -d "$svc/domain/mocks" ] && echo y || echo n)
  has_app=$([ -d "$svc/app" ] && echo y || echo n)
  has_infra=$([ -d "$svc/infra" ] && echo y || echo n)
  has_ports=$([ -d "$svc/ports" ] && echo y || echo n)

  {
    echo "# Hexagonal layering rules — generated by tools/gen_arch_configs.sh"
    echo "# Allowed dependency direction:"
    echo "#   domain ← (leaf, no internal deps)"
    echo "#   app    → domain"
    echo "#   infra  → domain  (infra includes sub-packages: db, parsers, cache, etc.)"
    echo "#   ports  → app, domain"
    echo "version: 3"
    echo "workdir: ."
    echo ""
    echo "allow:"
    echo "  depOnAnyVendor: true"
    echo ""
    echo "excludeFiles:"
    echo "  - \".*_test\\\\.go\$\""
    echo ""
    echo "components:"
    [ "$has_domain" = y ] && { echo "  domain:"; echo "    in:"; echo "      - domain"; }
    [ "$has_mocks" = y ]  && { echo "  mocks:"; echo "    in: domain/mocks"; }
    [ "$has_app" = y ]    && { echo "  app:"; echo "    in:"; echo "      - app"; echo "      - app/**"; }
    if [ "$has_infra" = y ]; then
      echo "  infra:"
      echo "    in:"
      echo "      - infra"
      echo "      - infra/**"
    fi
    [ "$has_ports" = y ]  && { echo "  ports:"; echo "    in:"; echo "      - ports"; echo "      - ports/**"; }
    echo ""
    echo "deps:"
    if [ "$has_domain" = y ]; then
      echo "  domain:"
      echo "    anyProjectDeps: true"
      echo "    mayDependOn: []"
    fi
    if [ "$has_mocks" = y ]; then
      echo "  mocks:"
      echo "    mayDependOn: [domain]"
    fi
    if [ "$has_app" = y ]; then
      echo "  app:"
      [ "$has_domain" = y ] && echo "    mayDependOn: [domain]" || echo "    mayDependOn: []"
    fi
    if [ "$has_infra" = y ]; then
      echo "  infra:"
      # Self-dep is needed because infra/db, infra/cache, infra/parsers/* are
      # treated as separate import paths even though they map to component infra.
      [ "$has_domain" = y ] && echo "    mayDependOn: [domain, infra]" || echo "    mayDependOn: [infra]"
    fi
    if [ "$has_ports" = y ]; then
      echo "  ports:"
      deps=""
      [ "$has_app" = y ] && deps="app"
      [ "$has_domain" = y ] && deps="${deps:+$deps, }domain"
      [ -n "$deps" ] && echo "    mayDependOn: [$deps]" || echo "    mayDependOn: []"
    fi
  } > "$cfg"
done
echo "Generated configs for $(ls $SERVICES/*/.go-arch-lint.yml | wc -l) services"
