// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/repo_mock.go -source repo.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/podcast/domain"
	enums "druz9/shared/enums"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPodcastRepo is a mock of PodcastRepo interface.
type MockPodcastRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPodcastRepoMockRecorder
	isgomock struct{}
}

// MockPodcastRepoMockRecorder is the mock recorder for MockPodcastRepo.
type MockPodcastRepoMockRecorder struct {
	mock *MockPodcastRepo
}

// NewMockPodcastRepo creates a new mock instance.
func NewMockPodcastRepo(ctrl *gomock.Controller) *MockPodcastRepo {
	mock := &MockPodcastRepo{ctrl: ctrl}
	mock.recorder = &MockPodcastRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodcastRepo) EXPECT() *MockPodcastRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockPodcastRepo) GetByID(ctx context.Context, podcastID uuid.UUID) (domain.Podcast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, podcastID)
	ret0, _ := ret[0].(domain.Podcast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPodcastRepoMockRecorder) GetByID(ctx, podcastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPodcastRepo)(nil).GetByID), ctx, podcastID)
}

// GetProgress mocks base method.
func (m *MockPodcastRepo) GetProgress(ctx context.Context, userID, podcastID uuid.UUID) (domain.Progress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProgress", ctx, userID, podcastID)
	ret0, _ := ret[0].(domain.Progress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProgress indicates an expected call of GetProgress.
func (mr *MockPodcastRepoMockRecorder) GetProgress(ctx, userID, podcastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProgress", reflect.TypeOf((*MockPodcastRepo)(nil).GetProgress), ctx, userID, podcastID)
}

// ListForUser mocks base method.
func (m *MockPodcastRepo) ListForUser(ctx context.Context, userID uuid.UUID, section *enums.Section) ([]domain.Listing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForUser", ctx, userID, section)
	ret0, _ := ret[0].([]domain.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForUser indicates an expected call of ListForUser.
func (mr *MockPodcastRepoMockRecorder) ListForUser(ctx, userID, section any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForUser", reflect.TypeOf((*MockPodcastRepo)(nil).ListForUser), ctx, userID, section)
}

// UpsertProgress mocks base method.
func (m *MockPodcastRepo) UpsertProgress(ctx context.Context, p domain.Progress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProgress", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertProgress indicates an expected call of UpsertProgress.
func (mr *MockPodcastRepoMockRecorder) UpsertProgress(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProgress", reflect.TypeOf((*MockPodcastRepo)(nil).UpsertProgress), ctx, p)
}

// MockAudioSigner is a mock of AudioSigner interface.
type MockAudioSigner struct {
	ctrl     *gomock.Controller
	recorder *MockAudioSignerMockRecorder
	isgomock struct{}
}

// MockAudioSignerMockRecorder is the mock recorder for MockAudioSigner.
type MockAudioSignerMockRecorder struct {
	mock *MockAudioSigner
}

// NewMockAudioSigner creates a new mock instance.
func NewMockAudioSigner(ctrl *gomock.Controller) *MockAudioSigner {
	mock := &MockAudioSigner{ctrl: ctrl}
	mock.recorder = &MockAudioSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioSigner) EXPECT() *MockAudioSignerMockRecorder {
	return m.recorder
}

// Sign mocks base method.
func (m *MockAudioSigner) Sign(ctx context.Context, audioKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", ctx, audioKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MockAudioSignerMockRecorder) Sign(ctx, audioKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockAudioSigner)(nil).Sign), ctx, audioKey)
}
