// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package copilotdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Queries consumed by sqlc; mirror hand-rolled pgx in infra/postgres.go.
	// Screenshot bytes are NEVER persisted — the `has_screenshot` flag on
	// copilot_messages is the only record of an image attachment.
	// =============================================================================
	// Conversations
	// =============================================================================
	CreateCopilotConversation(ctx context.Context, arg CreateCopilotConversationParams) (CopilotConversation, error)
	DeleteCopilotConversation(ctx context.Context, arg DeleteCopilotConversationParams) (int64, error)
	GetCopilotConversation(ctx context.Context, id pgtype.UUID) (CopilotConversation, error)
	// Used by the app layer to enforce ownership before calling RateCopilotMessage.
	// Returns the user_id of the conversation that owns this message.
	GetCopilotMessageOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// =============================================================================
	// Quotas
	// =============================================================================
	GetCopilotQuota(ctx context.Context, userID pgtype.UUID) (CopilotQuota, error)
	// Called inside the Analyze / Chat transaction after a successful LLM call.
	// The app layer checks (requests_used < requests_cap OR requests_cap < 0)
	// before calling.
	IncrementCopilotQuotaUsage(ctx context.Context, userID pgtype.UUID) (int64, error)
	// =============================================================================
	// Messages
	// =============================================================================
	InsertCopilotMessage(ctx context.Context, arg InsertCopilotMessageParams) (CopilotMessage, error)
	// Keyset pagination by updated_at DESC, id DESC (stable order).
	// Passing zero-value cursor (cursor_updated_at = 'epoch', cursor_id = all-zeros
	// UUID) returns the newest page. The $4 epoch flag lets the caller request
	// "page 1" without synthesizing a bogus timestamp.
	ListCopilotConversationsForUser(ctx context.Context, arg ListCopilotConversationsForUserParams) ([]ListCopilotConversationsForUserRow, error)
	ListCopilotMessagesForConversation(ctx context.Context, conversationID pgtype.UUID) ([]CopilotMessage, error)
	// Updates the rating on an assistant message. user_id guard is enforced by
	// joining to the parent conversation — sqlc cannot express that in one query,
	// so the app layer calls GetCopilotMessageOwner first.
	RateCopilotMessage(ctx context.Context, arg RateCopilotMessageParams) (int64, error)
	// Called when `now() >= resets_at`. Resets the counter and shifts the window
	// forward by 24h (the window length is plan-agnostic for MVP).
	ResetCopilotQuotaWindow(ctx context.Context, userID pgtype.UUID) (int64, error)
	TouchCopilotConversation(ctx context.Context, id pgtype.UUID) (int64, error)
	// Called when the streaming completion finishes to commit the final assistant
	// text + token accounting onto the placeholder row created at stream start.
	UpdateCopilotAssistantMessage(ctx context.Context, arg UpdateCopilotAssistantMessageParams) (int64, error)
	UpdateCopilotConversationTitle(ctx context.Context, arg UpdateCopilotConversationTitleParams) (int64, error)
	// Called by the billing service (or admin tool) when a user's subscription
	// changes. Caps and allowed models are plan-derived — callers pass the full
	// target state.
	UpdateCopilotQuotaPlan(ctx context.Context, arg UpdateCopilotQuotaPlanParams) (int64, error)
	// Lazily creates a free-tier quota row on first use. Idempotent: if a row
	// already exists, returns it unchanged.
	UpsertCopilotQuotaDefault(ctx context.Context, userID pgtype.UUID) (CopilotQuota, error)
}

var _ Querier = (*Queries)(nil)
