// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cohortdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetCohort(ctx context.Context, id pgtype.UUID) (GetCohortRow, error)
	GetCohortMember(ctx context.Context, arg GetCohortMemberParams) (GetCohortMemberRow, error)
	// A war is "current" for a cohort when the given instant falls between its
	// week_start (inclusive) and week_end (exclusive). We cast `now` to a DATE
	// because the migration stores week bounds as DATE, not TIMESTAMPTZ.
	GetCurrentWarForCohort(ctx context.Context, arg GetCurrentWarForCohortParams) (CohortWar, error)
	// Resolve the single cohort a user belongs to (cohort_members has a UNIQUE index
	// on user_id, so at most one row matches).
	GetMyCohort(ctx context.Context, userID pgtype.UUID) (GetMyCohortRow, error)
	GetWar(ctx context.Context, id pgtype.UUID) (CohortWar, error)
	ListCohortMembers(ctx context.Context, cohortID pgtype.UUID) ([]ListCohortMembersRow, error)
	// Global cohort leaderboard. We surface the existing cohort_elo column as the
	// primary ranking metric (the bible's "elo_total" — cohorts carry a single
	// ELO, members aren't summed, so this is the right pivot). members_count is
	// a simple correlated count. wars_won counts every cohort_wars row where
	// this cohort is the recorded winner. The ORDER BY is deterministic on ties
	// (elo desc, id asc) so the cache is consistent across reads.
	ListTopCohorts(ctx context.Context, limit int32) ([]ListTopCohortsRow, error)
	SetWarWinner(ctx context.Context, arg SetWarWinnerParams) (int64, error)
	// cohort queries consumed by sqlc (emitted into services/cohort/infra/db).
	// Contribution row storage is STUBBED in-memory at the infra layer — the
	// current migration does not have a war_contributions table. The queries
	// below cover what the domain persists on Postgres today.
	UpsertCohort(ctx context.Context, arg UpsertCohortParams) (UpsertCohortRow, error)
	// Add `delta` to scores_a[section] (JSONB). COALESCE handles first-write.
	UpsertWarScoreA(ctx context.Context, arg UpsertWarScoreAParams) (int64, error)
	UpsertWarScoreB(ctx context.Context, arg UpsertWarScoreBParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
