// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/repo_mock.go -source repo.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "druz9/cohort/domain"
	enums "druz9/shared/enums"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCohortRepo is a mock of CohortRepo interface.
type MockCohortRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCohortRepoMockRecorder
	isgomock struct{}
}

// MockCohortRepoMockRecorder is the mock recorder for MockCohortRepo.
type MockCohortRepoMockRecorder struct {
	mock *MockCohortRepo
}

// NewMockCohortRepo creates a new mock instance.
func NewMockCohortRepo(ctrl *gomock.Controller) *MockCohortRepo {
	mock := &MockCohortRepo{ctrl: ctrl}
	mock.recorder = &MockCohortRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCohortRepo) EXPECT() *MockCohortRepoMockRecorder {
	return m.recorder
}

// GetCohort mocks base method.
func (m *MockCohortRepo) GetCohort(ctx context.Context, id uuid.UUID) (domain.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCohort", ctx, id)
	ret0, _ := ret[0].(domain.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCohort indicates an expected call of GetCohort.
func (mr *MockCohortRepoMockRecorder) GetCohort(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCohort", reflect.TypeOf((*MockCohortRepo)(nil).GetCohort), ctx, id)
}

// GetMember mocks base method.
func (m *MockCohortRepo) GetMember(ctx context.Context, cohortID, userID uuid.UUID) (domain.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", ctx, cohortID, userID)
	ret0, _ := ret[0].(domain.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockCohortRepoMockRecorder) GetMember(ctx, cohortID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockCohortRepo)(nil).GetMember), ctx, cohortID, userID)
}

// GetMyCohort mocks base method.
func (m *MockCohortRepo) GetMyCohort(ctx context.Context, userID uuid.UUID) (domain.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyCohort", ctx, userID)
	ret0, _ := ret[0].(domain.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyCohort indicates an expected call of GetMyCohort.
func (mr *MockCohortRepoMockRecorder) GetMyCohort(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyCohort", reflect.TypeOf((*MockCohortRepo)(nil).GetMyCohort), ctx, userID)
}

// ListCohortMembers mocks base method.
func (m *MockCohortRepo) ListCohortMembers(ctx context.Context, cohortID uuid.UUID) ([]domain.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCohortMembers", ctx, cohortID)
	ret0, _ := ret[0].([]domain.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCohortMembers indicates an expected call of ListCohortMembers.
func (mr *MockCohortRepoMockRecorder) ListCohortMembers(ctx, cohortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCohortMembers", reflect.TypeOf((*MockCohortRepo)(nil).ListCohortMembers), ctx, cohortID)
}

// ListTopCohorts mocks base method.
func (m *MockCohortRepo) ListTopCohorts(ctx context.Context, limit int) ([]domain.TopCohortSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopCohorts", ctx, limit)
	ret0, _ := ret[0].([]domain.TopCohortSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopCohorts indicates an expected call of ListTopCohorts.
func (mr *MockCohortRepoMockRecorder) ListTopCohorts(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopCohorts", reflect.TypeOf((*MockCohortRepo)(nil).ListTopCohorts), ctx, limit)
}

// UpsertCohort mocks base method.
func (m *MockCohortRepo) UpsertCohort(ctx context.Context, g domain.Cohort) (domain.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCohort", ctx, g)
	ret0, _ := ret[0].(domain.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCohort indicates an expected call of UpsertCohort.
func (mr *MockCohortRepoMockRecorder) UpsertCohort(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCohort", reflect.TypeOf((*MockCohortRepo)(nil).UpsertCohort), ctx, g)
}

// MockWarRepo is a mock of WarRepo interface.
type MockWarRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWarRepoMockRecorder
	isgomock struct{}
}

// MockWarRepoMockRecorder is the mock recorder for MockWarRepo.
type MockWarRepoMockRecorder struct {
	mock *MockWarRepo
}

// NewMockWarRepo creates a new mock instance.
func NewMockWarRepo(ctrl *gomock.Controller) *MockWarRepo {
	mock := &MockWarRepo{ctrl: ctrl}
	mock.recorder = &MockWarRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarRepo) EXPECT() *MockWarRepoMockRecorder {
	return m.recorder
}

// GetCurrentWarForCohort mocks base method.
func (m *MockWarRepo) GetCurrentWarForCohort(ctx context.Context, cohortID uuid.UUID, now time.Time) (domain.War, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentWarForCohort", ctx, cohortID, now)
	ret0, _ := ret[0].(domain.War)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentWarForCohort indicates an expected call of GetCurrentWarForCohort.
func (mr *MockWarRepoMockRecorder) GetCurrentWarForCohort(ctx, cohortID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentWarForCohort", reflect.TypeOf((*MockWarRepo)(nil).GetCurrentWarForCohort), ctx, cohortID, now)
}

// GetWar mocks base method.
func (m *MockWarRepo) GetWar(ctx context.Context, warID uuid.UUID) (domain.War, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWar", ctx, warID)
	ret0, _ := ret[0].(domain.War)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWar indicates an expected call of GetWar.
func (mr *MockWarRepoMockRecorder) GetWar(ctx, warID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWar", reflect.TypeOf((*MockWarRepo)(nil).GetWar), ctx, warID)
}

// InsertContribution mocks base method.
func (m *MockWarRepo) InsertContribution(ctx context.Context, c domain.Contribution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertContribution", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertContribution indicates an expected call of InsertContribution.
func (mr *MockWarRepoMockRecorder) InsertContribution(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertContribution", reflect.TypeOf((*MockWarRepo)(nil).InsertContribution), ctx, c)
}

// ListContributions mocks base method.
func (m *MockWarRepo) ListContributions(ctx context.Context, warID uuid.UUID) ([]domain.Contribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContributions", ctx, warID)
	ret0, _ := ret[0].([]domain.Contribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContributions indicates an expected call of ListContributions.
func (mr *MockWarRepoMockRecorder) ListContributions(ctx, warID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContributions", reflect.TypeOf((*MockWarRepo)(nil).ListContributions), ctx, warID)
}

// SetWinner mocks base method.
func (m *MockWarRepo) SetWinner(ctx context.Context, warID uuid.UUID, winner *uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWinner", ctx, warID, winner)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWinner indicates an expected call of SetWinner.
func (mr *MockWarRepoMockRecorder) SetWinner(ctx, warID, winner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWinner", reflect.TypeOf((*MockWarRepo)(nil).SetWinner), ctx, warID, winner)
}

// UpsertWarScore mocks base method.
func (m *MockWarRepo) UpsertWarScore(ctx context.Context, warID uuid.UUID, section enums.Section, side domain.Side, delta int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWarScore", ctx, warID, section, side, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWarScore indicates an expected call of UpsertWarScore.
func (mr *MockWarRepoMockRecorder) UpsertWarScore(ctx, warID, section, side, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWarScore", reflect.TypeOf((*MockWarRepo)(nil).UpsertWarScore), ctx, warID, section, side, delta)
}

// MockJudge0Client is a mock of Judge0Client interface.
type MockJudge0Client struct {
	ctrl     *gomock.Controller
	recorder *MockJudge0ClientMockRecorder
	isgomock struct{}
}

// MockJudge0ClientMockRecorder is the mock recorder for MockJudge0Client.
type MockJudge0ClientMockRecorder struct {
	mock *MockJudge0Client
}

// NewMockJudge0Client creates a new mock instance.
func NewMockJudge0Client(ctrl *gomock.Controller) *MockJudge0Client {
	mock := &MockJudge0Client{ctrl: ctrl}
	mock.recorder = &MockJudge0ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJudge0Client) EXPECT() *MockJudge0ClientMockRecorder {
	return m.recorder
}

// Submit mocks base method.
func (m *MockJudge0Client) Submit(ctx context.Context, code, language string, section enums.Section) (domain.Judge0Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, code, language, section)
	ret0, _ := ret[0].(domain.Judge0Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockJudge0ClientMockRecorder) Submit(ctx, code, language, section any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockJudge0Client)(nil).Submit), ctx, code, language, section)
}
