// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: announcement.sql

package announcementdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReaction = `-- name: AddReaction :exec
INSERT INTO cohort_announcement_reactions(announcement_id, user_id, emoji)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddReactionParams struct {
	AnnouncementID pgtype.UUID
	UserID         pgtype.UUID
	Emoji          string
}

// Idempotent — duplicate (announcement, user, emoji) silently no-ops.
func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.Exec(ctx, addReaction, arg.AnnouncementID, arg.UserID, arg.Emoji)
	return err
}

const countReactions = `-- name: CountReactions :one
SELECT COUNT(*)::int FROM cohort_announcement_reactions
 WHERE announcement_id = $1 AND emoji = $2
`

type CountReactionsParams struct {
	AnnouncementID pgtype.UUID
	Emoji          string
}

func (q *Queries) CountReactions(ctx context.Context, arg CountReactionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReactions, arg.AnnouncementID, arg.Emoji)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one

INSERT INTO cohort_announcements(cohort_id, author_id, body, pinned, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, cohort_id, author_id, body, pinned, created_at, updated_at
`

type CreateAnnouncementParams struct {
	CohortID pgtype.UUID
	AuthorID pgtype.UUID
	Body     string
	Pinned   bool
}

// Cohort announcement feed queries (sqlc → infra/db).
func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (CohortAnnouncement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.CohortID,
		arg.AuthorID,
		arg.Body,
		arg.Pinned,
	)
	var i CohortAnnouncement
	err := row.Scan(
		&i.ID,
		&i.CohortID,
		&i.AuthorID,
		&i.Body,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :execrows
DELETE FROM cohort_announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnouncement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
SELECT a.id, a.cohort_id, a.author_id, a.body, a.pinned, a.created_at, a.updated_at,
       COALESCE(u.username, '')::text     AS author_username,
       COALESCE(u.display_name, '')::text AS author_display_name
  FROM cohort_announcements a
  LEFT JOIN users u ON u.id = a.author_id
 WHERE a.id = $1
`

type GetAnnouncementByIDRow struct {
	ID                pgtype.UUID
	CohortID          pgtype.UUID
	AuthorID          pgtype.UUID
	Body              string
	Pinned            bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	AuthorUsername    string
	AuthorDisplayName string
}

func (q *Queries) GetAnnouncementByID(ctx context.Context, id pgtype.UUID) (GetAnnouncementByIDRow, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, id)
	var i GetAnnouncementByIDRow
	err := row.Scan(
		&i.ID,
		&i.CohortID,
		&i.AuthorID,
		&i.Body,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorDisplayName,
	)
	return i, err
}

const listAnnouncementsByCohort = `-- name: ListAnnouncementsByCohort :many
SELECT a.id, a.cohort_id, a.author_id, a.body, a.pinned, a.created_at, a.updated_at,
       COALESCE(u.username, '')::text     AS author_username,
       COALESCE(u.display_name, '')::text AS author_display_name
  FROM cohort_announcements a
  LEFT JOIN users u ON u.id = a.author_id
 WHERE a.cohort_id = $1
 ORDER BY a.pinned DESC, a.created_at DESC
 LIMIT $2
`

type ListAnnouncementsByCohortParams struct {
	CohortID pgtype.UUID
	Limit    int32
}

type ListAnnouncementsByCohortRow struct {
	ID                pgtype.UUID
	CohortID          pgtype.UUID
	AuthorID          pgtype.UUID
	Body              string
	Pinned            bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	AuthorUsername    string
	AuthorDisplayName string
}

// Pinned first then newest. Limit is server-capped in app layer.
func (q *Queries) ListAnnouncementsByCohort(ctx context.Context, arg ListAnnouncementsByCohortParams) ([]ListAnnouncementsByCohortRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsByCohort, arg.CohortID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementsByCohortRow{}
	for rows.Next() {
		var i ListAnnouncementsByCohortRow
		if err := rows.Scan(
			&i.ID,
			&i.CohortID,
			&i.AuthorID,
			&i.Body,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsForAnnouncements = `-- name: ListReactionsForAnnouncements :many
SELECT r.announcement_id, r.emoji,
       COUNT(*)::int                                                AS total,
       BOOL_OR(r.user_id = $2)                                      AS viewer_reacted
  FROM cohort_announcement_reactions r
 WHERE r.announcement_id = ANY($1::uuid[])
 GROUP BY r.announcement_id, r.emoji
 ORDER BY r.announcement_id, total DESC
`

type ListReactionsForAnnouncementsParams struct {
	Column1 []pgtype.UUID
	UserID  pgtype.UUID
}

type ListReactionsForAnnouncementsRow struct {
	AnnouncementID pgtype.UUID
	Emoji          string
	Total          int32
	ViewerReacted  bool
}

// Aggregated reactions for a batch of announcement_ids. Returns one row
// per (announcement_id, emoji) with the total count + a bool of whether
// the viewer themselves reacted with that emoji.
func (q *Queries) ListReactionsForAnnouncements(ctx context.Context, arg ListReactionsForAnnouncementsParams) ([]ListReactionsForAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, listReactionsForAnnouncements, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsForAnnouncementsRow{}
	for rows.Next() {
		var i ListReactionsForAnnouncementsRow
		if err := rows.Scan(
			&i.AnnouncementID,
			&i.Emoji,
			&i.Total,
			&i.ViewerReacted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :execrows
DELETE FROM cohort_announcement_reactions
 WHERE announcement_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	AnnouncementID pgtype.UUID
	UserID         pgtype.UUID
	Emoji          string
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReaction, arg.AnnouncementID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
