// Code generated by MockGen. DO NOT EDIT.
// Source: orchestrator.go
//
// Generated by this command:
//
//	mockgen -package app -destination strictness_resolver_mock_test.go -source orchestrator.go StrictnessResolver
//

// Package app is a generated GoMock package.
package app

import (
	context "context"
	domain "druz9/mock_interview/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStrictnessResolver is a mock of StrictnessResolver interface.
type MockStrictnessResolver struct {
	ctrl     *gomock.Controller
	recorder *MockStrictnessResolverMockRecorder
	isgomock struct{}
}

// MockStrictnessResolverMockRecorder is the mock recorder for MockStrictnessResolver.
type MockStrictnessResolverMockRecorder struct {
	mock *MockStrictnessResolver
}

// NewMockStrictnessResolver creates a new mock instance.
func NewMockStrictnessResolver(ctrl *gomock.Controller) *MockStrictnessResolver {
	mock := &MockStrictnessResolver{ctrl: ctrl}
	mock.recorder = &MockStrictnessResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrictnessResolver) EXPECT() *MockStrictnessResolverMockRecorder {
	return m.recorder
}

// ResolveStrictness mocks base method.
func (m *MockStrictnessResolver) ResolveStrictness(ctx context.Context, taskID uuid.UUID, companyID *uuid.UUID, stage domain.StageKind) (domain.AIStrictnessProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveStrictness", ctx, taskID, companyID, stage)
	ret0, _ := ret[0].(domain.AIStrictnessProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveStrictness indicates an expected call of ResolveStrictness.
func (mr *MockStrictnessResolverMockRecorder) ResolveStrictness(ctx, taskID, companyID, stage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveStrictness", reflect.TypeOf((*MockStrictnessResolver)(nil).ResolveStrictness), ctx, taskID, companyID, stage)
}
