/**
 * @generated by design/tokens/emit.mjs — DO NOT EDIT.
 * Edit design/tokens/source.mjs, then run `make tokens`.
 */

export const motion = {
  dur: {
    micro: 80,
    small: 160,
    medium: 240,
    large: 360,
    xlarge: 520,
    xxlarge: 720,
    cinematic: 1100,
  },
  ease: {
    standard: 'cubic-bezier(0.2, 0.7, 0.2, 1)',
    emphasized: 'cubic-bezier(0.16, 1, 0.3, 1)',
    decelerate: 'cubic-bezier(0, 0, 0.2, 1)',
    accelerate: 'cubic-bezier(0.4, 0, 1, 1)',
  },
} as const;

export const focusRing = '0 0 0 1.5px rgba(255, 255, 255, 0.85), 0 0 0 4px rgba(255, 255, 255, 0.08)' as const;

export const density = {
  compact: {
    gapRow: 4,
    gapSection: 12,
    padInline: 8,
    padBlock: 6,
    padContainer: 12,
    radiusInner: 6,
    radiusOuter: 10,
    lineHeightBody: 1.4,
    minRowHeight: 28,
  },
  comfortable: {
    gapRow: 8,
    gapSection: 24,
    padInline: 16,
    padBlock: 12,
    padContainer: 32,
    radiusInner: 10,
    radiusOuter: 14,
    lineHeightBody: 1.55,
    minRowHeight: 36,
  },
  spacious: {
    gapRow: 12,
    gapSection: 40,
    padInline: 24,
    padBlock: 20,
    padContainer: 64,
    radiusInner: 14,
    radiusOuter: 18,
    lineHeightBody: 1.7,
    minRowHeight: 48,
  },
} as const;

export const breakpoints = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  '2xl': 1536,
  '3xl': 1920,
  '4xl': 2560,
} as const;

export const typography = {
  display: { size: 56, lh: 1.05, ls: '-0.025em', weight: 300 },
  h1: { size: 40, lh: 1.1, ls: '-0.022em', weight: 600 },
  h2: { size: 28, lh: 1.2, ls: '-0.018em', weight: 600 },
  h3: { size: 20, lh: 1.3, ls: '-0.012em', weight: 600 },
  body: { size: 15, lh: 1.55, ls: '-0.005em', weight: 400 },
  caption: { size: 12, lh: 1.4, ls: '0.010em', weight: 500 },
} as const;

export type MotionDuration = keyof typeof motion.dur;
export type MotionEase = keyof typeof motion.ease;
export type DensityMode = keyof typeof density;
export type Breakpoint = keyof typeof breakpoints;
export type TypoSlot = keyof typeof typography;
