// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package reviewdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// review queries (sqlc → services/review/infra/db).
	// Booking_id is the PK so a duplicate INSERT raises a unique-violation that
	// the app layer maps to ErrAlreadyReviewed.
	CreateReview(ctx context.Context, arg CreateReviewParams) (CreateReviewRow, error)
	// avg_rating is 0 when there are no reviews — caller decides whether to
	// surface the stat or treat zero as "no data" (slot does the latter).
	GetInterviewerStats(ctx context.Context, interviewerID pgtype.UUID) (GetInterviewerStatsRow, error)
	GetReviewByBooking(ctx context.Context, bookingID pgtype.UUID) (GetReviewByBookingRow, error)
	ListReviewsByInterviewer(ctx context.Context, arg ListReviewsByInterviewerParams) ([]ListReviewsByInterviewerRow, error)
}

var _ Querier = (*Queries)(nil)
