// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package reviewdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// review queries (sqlc → services/review/infra/db).
	// (booking_id, direction) is the composite PK; a duplicate raises
	// 23505 which the app layer maps to ErrAlreadyReviewed.
	CreateReview(ctx context.Context, arg CreateReviewParams) (CreateReviewRow, error)
	GetReviewByBookingDirection(ctx context.Context, arg GetReviewByBookingDirectionParams) (GetReviewByBookingDirectionRow, error)
	// avg_rating is 0 when there are no reviews — caller decides whether to
	// surface the stat or treat zero as "no data" (slot does the latter).
	GetSubjectStats(ctx context.Context, subjectID pgtype.UUID) (GetSubjectStatsRow, error)
	// Filters on subject_id (denormalized) so the same query backs both the
	// interviewer's public card and the candidate's own card.
	ListReviewsBySubject(ctx context.Context, arg ListReviewsBySubjectParams) ([]ListReviewsBySubjectRow, error)
}

var _ Querier = (*Queries)(nil)
