// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review.sql

package reviewdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one

INSERT INTO reviews(booking_id, reviewer_id, interviewer_id, rating, feedback, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING booking_id, reviewer_id, interviewer_id, rating, feedback, created_at, updated_at
`

type CreateReviewParams struct {
	BookingID     pgtype.UUID
	ReviewerID    pgtype.UUID
	InterviewerID pgtype.UUID
	Rating        int32
	Feedback      pgtype.Text
}

type CreateReviewRow struct {
	BookingID     pgtype.UUID
	ReviewerID    pgtype.UUID
	InterviewerID pgtype.UUID
	Rating        int32
	Feedback      pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// review queries (sqlc → services/review/infra/db).
// Booking_id is the PK so a duplicate INSERT raises a unique-violation that
// the app layer maps to ErrAlreadyReviewed.
func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (CreateReviewRow, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.BookingID,
		arg.ReviewerID,
		arg.InterviewerID,
		arg.Rating,
		arg.Feedback,
	)
	var i CreateReviewRow
	err := row.Scan(
		&i.BookingID,
		&i.ReviewerID,
		&i.InterviewerID,
		&i.Rating,
		&i.Feedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInterviewerStats = `-- name: GetInterviewerStats :one
SELECT COALESCE(AVG(rating)::float8, 0)::float8 AS avg_rating,
       COUNT(*)::int                            AS reviews_count
  FROM reviews
 WHERE interviewer_id = $1
`

type GetInterviewerStatsRow struct {
	AvgRating    float64
	ReviewsCount int32
}

// avg_rating is 0 when there are no reviews — caller decides whether to
// surface the stat or treat zero as "no data" (slot does the latter).
func (q *Queries) GetInterviewerStats(ctx context.Context, interviewerID pgtype.UUID) (GetInterviewerStatsRow, error) {
	row := q.db.QueryRow(ctx, getInterviewerStats, interviewerID)
	var i GetInterviewerStatsRow
	err := row.Scan(&i.AvgRating, &i.ReviewsCount)
	return i, err
}

const getReviewByBooking = `-- name: GetReviewByBooking :one
SELECT booking_id, reviewer_id, interviewer_id, rating, feedback, created_at, updated_at
  FROM reviews WHERE booking_id = $1
`

type GetReviewByBookingRow struct {
	BookingID     pgtype.UUID
	ReviewerID    pgtype.UUID
	InterviewerID pgtype.UUID
	Rating        int32
	Feedback      pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetReviewByBooking(ctx context.Context, bookingID pgtype.UUID) (GetReviewByBookingRow, error) {
	row := q.db.QueryRow(ctx, getReviewByBooking, bookingID)
	var i GetReviewByBookingRow
	err := row.Scan(
		&i.BookingID,
		&i.ReviewerID,
		&i.InterviewerID,
		&i.Rating,
		&i.Feedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewsByInterviewer = `-- name: ListReviewsByInterviewer :many
SELECT booking_id, reviewer_id, interviewer_id, rating, feedback, created_at, updated_at
  FROM reviews
 WHERE interviewer_id = $1
 ORDER BY created_at DESC
 LIMIT $2
`

type ListReviewsByInterviewerParams struct {
	InterviewerID pgtype.UUID
	Limit         int32
}

type ListReviewsByInterviewerRow struct {
	BookingID     pgtype.UUID
	ReviewerID    pgtype.UUID
	InterviewerID pgtype.UUID
	Rating        int32
	Feedback      pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListReviewsByInterviewer(ctx context.Context, arg ListReviewsByInterviewerParams) ([]ListReviewsByInterviewerRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByInterviewer, arg.InterviewerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByInterviewerRow{}
	for rows.Next() {
		var i ListReviewsByInterviewerRow
		if err := rows.Scan(
			&i.BookingID,
			&i.ReviewerID,
			&i.InterviewerID,
			&i.Rating,
			&i.Feedback,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
